version: 0.7
cluster_id: dpv2-quickwit
node_id: dpv2-quickwit-0
enabled_services:
  - control_plane
  - indexer
  - janitor
  - metastore
  - searcher
listen_address: 0.0.0.0
data_dir: /quickwit/qwdata
metastore_uri: s3://quickwit/metastore
default_index_root_uri: s3://quickwit/indexes
rest:
  listen_port: 7280
storage:
  s3:
    flavor: minio
    region: us-east-1
    endpoint: http://minio:9000
indexer:
  split_store_max_num_bytes: 8G
  split_store_max_num_splits: 1000
ingest_api:
  max_queue_memory_usage: 256MiB
  max_queue_disk_usage: 512MiB
searcher:
  fast_field_cache_capacity: 128M
  split_footer_cache_capacity: 128M
  partial_request_cache_capacity: 64M
