// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/proto/whitelist/v1/whitelist.proto

package whitelistv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhitelistService_AddToWhitelist_FullMethodName      = "/coresystem.gateway.whitelist.v1.WhitelistService/AddToWhitelist"
	WhitelistService_RemoveFromWhitelist_FullMethodName = "/coresystem.gateway.whitelist.v1.WhitelistService/RemoveFromWhitelist"
	WhitelistService_GetWhitelist_FullMethodName        = "/coresystem.gateway.whitelist.v1.WhitelistService/GetWhitelist"
	WhitelistService_AddToBlacklist_FullMethodName      = "/coresystem.gateway.whitelist.v1.WhitelistService/AddToBlacklist"
	WhitelistService_RemoveFromBlacklist_FullMethodName = "/coresystem.gateway.whitelist.v1.WhitelistService/RemoveFromBlacklist"
	WhitelistService_GetBlacklist_FullMethodName        = "/coresystem.gateway.whitelist.v1.WhitelistService/GetBlacklist"
	WhitelistService_IsAllowed_FullMethodName           = "/coresystem.gateway.whitelist.v1.WhitelistService/IsAllowed"
	WhitelistService_CleanupExpired_FullMethodName      = "/coresystem.gateway.whitelist.v1.WhitelistService/CleanupExpired"
)

// WhitelistServiceClient is the client API for WhitelistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WhitelistService provides IP whitelist/blacklist management for internal microservices
type WhitelistServiceClient interface {
	// AddToWhitelist adds an IP/CIDR to the whitelist
	AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error)
	// RemoveFromWhitelist removes an IP/CIDR from the whitelist
	RemoveFromWhitelist(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error)
	// GetWhitelist returns all whitelisted IPs
	GetWhitelist(ctx context.Context, in *GetWhitelistRequest, opts ...grpc.CallOption) (*GetWhitelistResponse, error)
	// AddToBlacklist adds an IP/CIDR to the blacklist
	AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error)
	// RemoveFromBlacklist removes an IP/CIDR from the blacklist
	RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error)
	// GetBlacklist returns all blacklisted IPs
	GetBlacklist(ctx context.Context, in *GetBlacklistRequest, opts ...grpc.CallOption) (*GetBlacklistResponse, error)
	// IsAllowed checks if an IP is allowed (not blacklisted and whitelisted)
	IsAllowed(ctx context.Context, in *IsAllowedRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error)
	// CleanupExpired removes expired whitelist/blacklist entries
	CleanupExpired(ctx context.Context, in *CleanupExpiredRequest, opts ...grpc.CallOption) (*CleanupExpiredResponse, error)
}

type whitelistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhitelistServiceClient(cc grpc.ClientConnInterface) WhitelistServiceClient {
	return &whitelistServiceClient{cc}
}

func (c *whitelistServiceClient) AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToWhitelistResponse)
	err := c.cc.Invoke(ctx, WhitelistService_AddToWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) RemoveFromWhitelist(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromWhitelistResponse)
	err := c.cc.Invoke(ctx, WhitelistService_RemoveFromWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) GetWhitelist(ctx context.Context, in *GetWhitelistRequest, opts ...grpc.CallOption) (*GetWhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWhitelistResponse)
	err := c.cc.Invoke(ctx, WhitelistService_GetWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToBlacklistResponse)
	err := c.cc.Invoke(ctx, WhitelistService_AddToBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromBlacklistResponse)
	err := c.cc.Invoke(ctx, WhitelistService_RemoveFromBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) GetBlacklist(ctx context.Context, in *GetBlacklistRequest, opts ...grpc.CallOption) (*GetBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlacklistResponse)
	err := c.cc.Invoke(ctx, WhitelistService_GetBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) IsAllowed(ctx context.Context, in *IsAllowedRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAllowedResponse)
	err := c.cc.Invoke(ctx, WhitelistService_IsAllowed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) CleanupExpired(ctx context.Context, in *CleanupExpiredRequest, opts ...grpc.CallOption) (*CleanupExpiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupExpiredResponse)
	err := c.cc.Invoke(ctx, WhitelistService_CleanupExpired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhitelistServiceServer is the server API for WhitelistService service.
// All implementations must embed UnimplementedWhitelistServiceServer
// for forward compatibility.
//
// WhitelistService provides IP whitelist/blacklist management for internal microservices
type WhitelistServiceServer interface {
	// AddToWhitelist adds an IP/CIDR to the whitelist
	AddToWhitelist(context.Context, *AddToWhitelistRequest) (*AddToWhitelistResponse, error)
	// RemoveFromWhitelist removes an IP/CIDR from the whitelist
	RemoveFromWhitelist(context.Context, *RemoveFromWhitelistRequest) (*RemoveFromWhitelistResponse, error)
	// GetWhitelist returns all whitelisted IPs
	GetWhitelist(context.Context, *GetWhitelistRequest) (*GetWhitelistResponse, error)
	// AddToBlacklist adds an IP/CIDR to the blacklist
	AddToBlacklist(context.Context, *AddToBlacklistRequest) (*AddToBlacklistResponse, error)
	// RemoveFromBlacklist removes an IP/CIDR from the blacklist
	RemoveFromBlacklist(context.Context, *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error)
	// GetBlacklist returns all blacklisted IPs
	GetBlacklist(context.Context, *GetBlacklistRequest) (*GetBlacklistResponse, error)
	// IsAllowed checks if an IP is allowed (not blacklisted and whitelisted)
	IsAllowed(context.Context, *IsAllowedRequest) (*IsAllowedResponse, error)
	// CleanupExpired removes expired whitelist/blacklist entries
	CleanupExpired(context.Context, *CleanupExpiredRequest) (*CleanupExpiredResponse, error)
	mustEmbedUnimplementedWhitelistServiceServer()
}

// UnimplementedWhitelistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhitelistServiceServer struct{}

func (UnimplementedWhitelistServiceServer) AddToWhitelist(context.Context, *AddToWhitelistRequest) (*AddToWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhitelist not implemented")
}
func (UnimplementedWhitelistServiceServer) RemoveFromWhitelist(context.Context, *RemoveFromWhitelistRequest) (*RemoveFromWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromWhitelist not implemented")
}
func (UnimplementedWhitelistServiceServer) GetWhitelist(context.Context, *GetWhitelistRequest) (*GetWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWhitelist not implemented")
}
func (UnimplementedWhitelistServiceServer) AddToBlacklist(context.Context, *AddToBlacklistRequest) (*AddToBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (UnimplementedWhitelistServiceServer) RemoveFromBlacklist(context.Context, *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromBlacklist not implemented")
}
func (UnimplementedWhitelistServiceServer) GetBlacklist(context.Context, *GetBlacklistRequest) (*GetBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlacklist not implemented")
}
func (UnimplementedWhitelistServiceServer) IsAllowed(context.Context, *IsAllowedRequest) (*IsAllowedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAllowed not implemented")
}
func (UnimplementedWhitelistServiceServer) CleanupExpired(context.Context, *CleanupExpiredRequest) (*CleanupExpiredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanupExpired not implemented")
}
func (UnimplementedWhitelistServiceServer) mustEmbedUnimplementedWhitelistServiceServer() {}
func (UnimplementedWhitelistServiceServer) testEmbeddedByValue()                          {}

// UnsafeWhitelistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhitelistServiceServer will
// result in compilation errors.
type UnsafeWhitelistServiceServer interface {
	mustEmbedUnimplementedWhitelistServiceServer()
}

func RegisterWhitelistServiceServer(s grpc.ServiceRegistrar, srv WhitelistServiceServer) {
	// If the following call pancis, it indicates UnimplementedWhitelistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhitelistService_ServiceDesc, srv)
}

func _WhitelistService_AddToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).AddToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_AddToWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).AddToWhitelist(ctx, req.(*AddToWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_RemoveFromWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).RemoveFromWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_RemoveFromWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).RemoveFromWhitelist(ctx, req.(*RemoveFromWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_GetWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).GetWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_GetWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).GetWhitelist(ctx, req.(*GetWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_AddToBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).AddToBlacklist(ctx, req.(*AddToBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_RemoveFromBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).RemoveFromBlacklist(ctx, req.(*RemoveFromBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_GetBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).GetBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_GetBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).GetBlacklist(ctx, req.(*GetBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_IsAllowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAllowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).IsAllowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_IsAllowed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).IsAllowed(ctx, req.(*IsAllowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_CleanupExpired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupExpiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).CleanupExpired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_CleanupExpired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).CleanupExpired(ctx, req.(*CleanupExpiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhitelistService_ServiceDesc is the grpc.ServiceDesc for WhitelistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhitelistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coresystem.gateway.whitelist.v1.WhitelistService",
	HandlerType: (*WhitelistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToWhitelist",
			Handler:    _WhitelistService_AddToWhitelist_Handler,
		},
		{
			MethodName: "RemoveFromWhitelist",
			Handler:    _WhitelistService_RemoveFromWhitelist_Handler,
		},
		{
			MethodName: "GetWhitelist",
			Handler:    _WhitelistService_GetWhitelist_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _WhitelistService_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _WhitelistService_RemoveFromBlacklist_Handler,
		},
		{
			MethodName: "GetBlacklist",
			Handler:    _WhitelistService_GetBlacklist_Handler,
		},
		{
			MethodName: "IsAllowed",
			Handler:    _WhitelistService_IsAllowed_Handler,
		},
		{
			MethodName: "CleanupExpired",
			Handler:    _WhitelistService_CleanupExpired_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/whitelist/v1/whitelist.proto",
}
