// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/whitelist/v1/whitelist.proto

package whitelistv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddToWhitelistRequest contains IP to whitelist
type AddToWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // IP address or CIDR notation
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AddedBy       string                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Optional expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToWhitelistRequest) Reset() {
	*x = AddToWhitelistRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWhitelistRequest) ProtoMessage() {}

func (x *AddToWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWhitelistRequest.ProtoReflect.Descriptor instead.
func (*AddToWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{0}
}

func (x *AddToWhitelistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddToWhitelistRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddToWhitelistRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *AddToWhitelistRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// AddToWhitelistResponse confirms whitelist addition
type AddToWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Entry         *IPEntry               `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToWhitelistResponse) Reset() {
	*x = AddToWhitelistResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWhitelistResponse) ProtoMessage() {}

func (x *AddToWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWhitelistResponse.ProtoReflect.Descriptor instead.
func (*AddToWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{1}
}

func (x *AddToWhitelistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToWhitelistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddToWhitelistResponse) GetEntry() *IPEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// RemoveFromWhitelistRequest contains IP to remove
type RemoveFromWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromWhitelistRequest) Reset() {
	*x = RemoveFromWhitelistRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWhitelistRequest) ProtoMessage() {}

func (x *RemoveFromWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWhitelistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFromWhitelistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// RemoveFromWhitelistResponse confirms removal
type RemoveFromWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromWhitelistResponse) Reset() {
	*x = RemoveFromWhitelistResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWhitelistResponse) ProtoMessage() {}

func (x *RemoveFromWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWhitelistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFromWhitelistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFromWhitelistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetWhitelistRequest is empty
type GetWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWhitelistRequest) Reset() {
	*x = GetWhitelistRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWhitelistRequest) ProtoMessage() {}

func (x *GetWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWhitelistRequest.ProtoReflect.Descriptor instead.
func (*GetWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{4}
}

// GetWhitelistResponse contains all whitelisted IPs
type GetWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*IPEntry             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWhitelistResponse) Reset() {
	*x = GetWhitelistResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWhitelistResponse) ProtoMessage() {}

func (x *GetWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWhitelistResponse.ProtoReflect.Descriptor instead.
func (*GetWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{5}
}

func (x *GetWhitelistResponse) GetEntries() []*IPEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// AddToBlacklistRequest contains IP to blacklist
type AddToBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AddedBy       string                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBlacklistRequest) Reset() {
	*x = AddToBlacklistRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBlacklistRequest) ProtoMessage() {}

func (x *AddToBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBlacklistRequest.ProtoReflect.Descriptor instead.
func (*AddToBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{6}
}

func (x *AddToBlacklistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddToBlacklistRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddToBlacklistRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *AddToBlacklistRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// AddToBlacklistResponse confirms blacklist addition
type AddToBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Entry         *IPEntry               `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBlacklistResponse) Reset() {
	*x = AddToBlacklistResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBlacklistResponse) ProtoMessage() {}

func (x *AddToBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBlacklistResponse.ProtoReflect.Descriptor instead.
func (*AddToBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{7}
}

func (x *AddToBlacklistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToBlacklistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddToBlacklistResponse) GetEntry() *IPEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// RemoveFromBlacklistRequest contains IP to remove
type RemoveFromBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBlacklistRequest) Reset() {
	*x = RemoveFromBlacklistRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBlacklistRequest) ProtoMessage() {}

func (x *RemoveFromBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBlacklistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFromBlacklistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// RemoveFromBlacklistResponse confirms removal
type RemoveFromBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBlacklistResponse) Reset() {
	*x = RemoveFromBlacklistResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBlacklistResponse) ProtoMessage() {}

func (x *RemoveFromBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBlacklistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFromBlacklistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFromBlacklistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetBlacklistRequest is empty
type GetBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlacklistRequest) Reset() {
	*x = GetBlacklistRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlacklistRequest) ProtoMessage() {}

func (x *GetBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlacklistRequest.ProtoReflect.Descriptor instead.
func (*GetBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{10}
}

// GetBlacklistResponse contains all blacklisted IPs
type GetBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*IPEntry             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlacklistResponse) Reset() {
	*x = GetBlacklistResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlacklistResponse) ProtoMessage() {}

func (x *GetBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlacklistResponse.ProtoReflect.Descriptor instead.
func (*GetBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlacklistResponse) GetEntries() []*IPEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// IsAllowedRequest checks if IP is allowed
type IsAllowedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAllowedRequest) Reset() {
	*x = IsAllowedRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAllowedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedRequest) ProtoMessage() {}

func (x *IsAllowedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedRequest.ProtoReflect.Descriptor instead.
func (*IsAllowedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{12}
}

func (x *IsAllowedRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// IsAllowedResponse indicates if IP is allowed
type IsAllowedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Explanation if not allowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAllowedResponse) Reset() {
	*x = IsAllowedResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAllowedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedResponse) ProtoMessage() {}

func (x *IsAllowedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedResponse.ProtoReflect.Descriptor instead.
func (*IsAllowedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{13}
}

func (x *IsAllowedResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *IsAllowedResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CleanupExpiredRequest is empty
type CleanupExpiredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupExpiredRequest) Reset() {
	*x = CleanupExpiredRequest{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredRequest) ProtoMessage() {}

func (x *CleanupExpiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredRequest.ProtoReflect.Descriptor instead.
func (*CleanupExpiredRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{14}
}

// CleanupExpiredResponse confirms cleanup
type CleanupExpiredResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WhitelistRemoved int32                  `protobuf:"varint,1,opt,name=whitelist_removed,json=whitelistRemoved,proto3" json:"whitelist_removed,omitempty"`
	BlacklistRemoved int32                  `protobuf:"varint,2,opt,name=blacklist_removed,json=blacklistRemoved,proto3" json:"blacklist_removed,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CleanupExpiredResponse) Reset() {
	*x = CleanupExpiredResponse{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredResponse) ProtoMessage() {}

func (x *CleanupExpiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredResponse.ProtoReflect.Descriptor instead.
func (*CleanupExpiredResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{15}
}

func (x *CleanupExpiredResponse) GetWhitelistRemoved() int32 {
	if x != nil {
		return x.WhitelistRemoved
	}
	return 0
}

func (x *CleanupExpiredResponse) GetBlacklistRemoved() int32 {
	if x != nil {
		return x.BlacklistRemoved
	}
	return 0
}

func (x *CleanupExpiredResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// IPEntry represents a whitelist or blacklist entry
type IPEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AddedBy       string                 `protobuf:"bytes,3,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Expired       bool                   `protobuf:"varint,6,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPEntry) Reset() {
	*x = IPEntry{}
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPEntry) ProtoMessage() {}

func (x *IPEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_whitelist_v1_whitelist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPEntry.ProtoReflect.Descriptor instead.
func (*IPEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP(), []int{16}
}

func (x *IPEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IPEntry) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *IPEntry) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

func (x *IPEntry) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *IPEntry) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

var File_api_proto_whitelist_v1_whitelist_proto protoreflect.FileDescriptor

const file_api_proto_whitelist_v1_whitelist_proto_rawDesc = "" +
	"\n" +
	"&api/proto/whitelist/v1/whitelist.proto\x12\x1ccoresystem.gateway.whitelist.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x15AddToWhitelistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\tR\aaddedBy\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x89\x01\n" +
	"\x16AddToWhitelistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x05entry\x18\x03 \x01(\v2%.coresystem.gateway.whitelist.v1.IPEntryR\x05entry\",\n" +
	"\x1aRemoveFromWhitelistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"Q\n" +
	"\x1bRemoveFromWhitelistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13GetWhitelistRequest\"W\n" +
	"\x14GetWhitelistResponse\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.coresystem.gateway.whitelist.v1.IPEntryR\aentries\"\x9f\x01\n" +
	"\x15AddToBlacklistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\tR\aaddedBy\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x89\x01\n" +
	"\x16AddToBlacklistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x05entry\x18\x03 \x01(\v2%.coresystem.gateway.whitelist.v1.IPEntryR\x05entry\",\n" +
	"\x1aRemoveFromBlacklistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"Q\n" +
	"\x1bRemoveFromBlacklistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13GetBlacklistRequest\"W\n" +
	"\x14GetBlacklistResponse\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.coresystem.gateway.whitelist.v1.IPEntryR\aentries\"\"\n" +
	"\x10IsAllowedRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"E\n" +
	"\x11IsAllowedResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x17\n" +
	"\x15CleanupExpiredRequest\"\x8c\x01\n" +
	"\x16CleanupExpiredResponse\x12+\n" +
	"\x11whitelist_removed\x18\x01 \x01(\x05R\x10whitelistRemoved\x12+\n" +
	"\x11blacklist_removed\x18\x02 \x01(\x05R\x10blacklistRemoved\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe2\x01\n" +
	"\aIPEntry\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\badded_by\x18\x03 \x01(\tR\aaddedBy\x125\n" +
	"\badded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\aexpired\x18\x06 \x01(\bR\aexpired2\xff\a\n" +
	"\x10WhitelistService\x12{\n" +
	"\x0eAddToWhitelist\x123.coresystem.gateway.whitelist.v1.AddToWhitelistRequest\x1a4.coresystem.gateway.whitelist.v1.AddToWhitelistResponse\x12\x8a\x01\n" +
	"\x13RemoveFromWhitelist\x128.coresystem.gateway.whitelist.v1.RemoveFromWhitelistRequest\x1a9.coresystem.gateway.whitelist.v1.RemoveFromWhitelistResponse\x12u\n" +
	"\fGetWhitelist\x121.coresystem.gateway.whitelist.v1.GetWhitelistRequest\x1a2.coresystem.gateway.whitelist.v1.GetWhitelistResponse\x12{\n" +
	"\x0eAddToBlacklist\x123.coresystem.gateway.whitelist.v1.AddToBlacklistRequest\x1a4.coresystem.gateway.whitelist.v1.AddToBlacklistResponse\x12\x8a\x01\n" +
	"\x13RemoveFromBlacklist\x128.coresystem.gateway.whitelist.v1.RemoveFromBlacklistRequest\x1a9.coresystem.gateway.whitelist.v1.RemoveFromBlacklistResponse\x12u\n" +
	"\fGetBlacklist\x121.coresystem.gateway.whitelist.v1.GetBlacklistRequest\x1a2.coresystem.gateway.whitelist.v1.GetBlacklistResponse\x12l\n" +
	"\tIsAllowed\x12..coresystem.gateway.whitelist.v1.IsAllowedRequest\x1a/.coresystem.gateway.whitelist.v1.IsAllowedResponse\x12{\n" +
	"\x0eCleanupExpired\x123.coresystem.gateway.whitelist.v1.CleanupExpiredRequest\x1a4.coresystem.gateway.whitelist.v1.CleanupExpiredResponseBKZIgithub.com/coresystem/integration-gateway/api/proto/whitelist/v1;whitelistv1b\x06proto3"

var (
	file_api_proto_whitelist_v1_whitelist_proto_rawDescOnce sync.Once
	file_api_proto_whitelist_v1_whitelist_proto_rawDescData []byte
)

func file_api_proto_whitelist_v1_whitelist_proto_rawDescGZIP() []byte {
	file_api_proto_whitelist_v1_whitelist_proto_rawDescOnce.Do(func() {
		file_api_proto_whitelist_v1_whitelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_whitelist_v1_whitelist_proto_rawDesc), len(file_api_proto_whitelist_v1_whitelist_proto_rawDesc)))
	})
	return file_api_proto_whitelist_v1_whitelist_proto_rawDescData
}

var file_api_proto_whitelist_v1_whitelist_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_whitelist_v1_whitelist_proto_goTypes = []any{
	(*AddToWhitelistRequest)(nil),       // 0: coresystem.gateway.whitelist.v1.AddToWhitelistRequest
	(*AddToWhitelistResponse)(nil),      // 1: coresystem.gateway.whitelist.v1.AddToWhitelistResponse
	(*RemoveFromWhitelistRequest)(nil),  // 2: coresystem.gateway.whitelist.v1.RemoveFromWhitelistRequest
	(*RemoveFromWhitelistResponse)(nil), // 3: coresystem.gateway.whitelist.v1.RemoveFromWhitelistResponse
	(*GetWhitelistRequest)(nil),         // 4: coresystem.gateway.whitelist.v1.GetWhitelistRequest
	(*GetWhitelistResponse)(nil),        // 5: coresystem.gateway.whitelist.v1.GetWhitelistResponse
	(*AddToBlacklistRequest)(nil),       // 6: coresystem.gateway.whitelist.v1.AddToBlacklistRequest
	(*AddToBlacklistResponse)(nil),      // 7: coresystem.gateway.whitelist.v1.AddToBlacklistResponse
	(*RemoveFromBlacklistRequest)(nil),  // 8: coresystem.gateway.whitelist.v1.RemoveFromBlacklistRequest
	(*RemoveFromBlacklistResponse)(nil), // 9: coresystem.gateway.whitelist.v1.RemoveFromBlacklistResponse
	(*GetBlacklistRequest)(nil),         // 10: coresystem.gateway.whitelist.v1.GetBlacklistRequest
	(*GetBlacklistResponse)(nil),        // 11: coresystem.gateway.whitelist.v1.GetBlacklistResponse
	(*IsAllowedRequest)(nil),            // 12: coresystem.gateway.whitelist.v1.IsAllowedRequest
	(*IsAllowedResponse)(nil),           // 13: coresystem.gateway.whitelist.v1.IsAllowedResponse
	(*CleanupExpiredRequest)(nil),       // 14: coresystem.gateway.whitelist.v1.CleanupExpiredRequest
	(*CleanupExpiredResponse)(nil),      // 15: coresystem.gateway.whitelist.v1.CleanupExpiredResponse
	(*IPEntry)(nil),                     // 16: coresystem.gateway.whitelist.v1.IPEntry
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
}
var file_api_proto_whitelist_v1_whitelist_proto_depIdxs = []int32{
	17, // 0: coresystem.gateway.whitelist.v1.AddToWhitelistRequest.expires_at:type_name -> google.protobuf.Timestamp
	16, // 1: coresystem.gateway.whitelist.v1.AddToWhitelistResponse.entry:type_name -> coresystem.gateway.whitelist.v1.IPEntry
	16, // 2: coresystem.gateway.whitelist.v1.GetWhitelistResponse.entries:type_name -> coresystem.gateway.whitelist.v1.IPEntry
	17, // 3: coresystem.gateway.whitelist.v1.AddToBlacklistRequest.expires_at:type_name -> google.protobuf.Timestamp
	16, // 4: coresystem.gateway.whitelist.v1.AddToBlacklistResponse.entry:type_name -> coresystem.gateway.whitelist.v1.IPEntry
	16, // 5: coresystem.gateway.whitelist.v1.GetBlacklistResponse.entries:type_name -> coresystem.gateway.whitelist.v1.IPEntry
	17, // 6: coresystem.gateway.whitelist.v1.IPEntry.added_at:type_name -> google.protobuf.Timestamp
	17, // 7: coresystem.gateway.whitelist.v1.IPEntry.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 8: coresystem.gateway.whitelist.v1.WhitelistService.AddToWhitelist:input_type -> coresystem.gateway.whitelist.v1.AddToWhitelistRequest
	2,  // 9: coresystem.gateway.whitelist.v1.WhitelistService.RemoveFromWhitelist:input_type -> coresystem.gateway.whitelist.v1.RemoveFromWhitelistRequest
	4,  // 10: coresystem.gateway.whitelist.v1.WhitelistService.GetWhitelist:input_type -> coresystem.gateway.whitelist.v1.GetWhitelistRequest
	6,  // 11: coresystem.gateway.whitelist.v1.WhitelistService.AddToBlacklist:input_type -> coresystem.gateway.whitelist.v1.AddToBlacklistRequest
	8,  // 12: coresystem.gateway.whitelist.v1.WhitelistService.RemoveFromBlacklist:input_type -> coresystem.gateway.whitelist.v1.RemoveFromBlacklistRequest
	10, // 13: coresystem.gateway.whitelist.v1.WhitelistService.GetBlacklist:input_type -> coresystem.gateway.whitelist.v1.GetBlacklistRequest
	12, // 14: coresystem.gateway.whitelist.v1.WhitelistService.IsAllowed:input_type -> coresystem.gateway.whitelist.v1.IsAllowedRequest
	14, // 15: coresystem.gateway.whitelist.v1.WhitelistService.CleanupExpired:input_type -> coresystem.gateway.whitelist.v1.CleanupExpiredRequest
	1,  // 16: coresystem.gateway.whitelist.v1.WhitelistService.AddToWhitelist:output_type -> coresystem.gateway.whitelist.v1.AddToWhitelistResponse
	3,  // 17: coresystem.gateway.whitelist.v1.WhitelistService.RemoveFromWhitelist:output_type -> coresystem.gateway.whitelist.v1.RemoveFromWhitelistResponse
	5,  // 18: coresystem.gateway.whitelist.v1.WhitelistService.GetWhitelist:output_type -> coresystem.gateway.whitelist.v1.GetWhitelistResponse
	7,  // 19: coresystem.gateway.whitelist.v1.WhitelistService.AddToBlacklist:output_type -> coresystem.gateway.whitelist.v1.AddToBlacklistResponse
	9,  // 20: coresystem.gateway.whitelist.v1.WhitelistService.RemoveFromBlacklist:output_type -> coresystem.gateway.whitelist.v1.RemoveFromBlacklistResponse
	11, // 21: coresystem.gateway.whitelist.v1.WhitelistService.GetBlacklist:output_type -> coresystem.gateway.whitelist.v1.GetBlacklistResponse
	13, // 22: coresystem.gateway.whitelist.v1.WhitelistService.IsAllowed:output_type -> coresystem.gateway.whitelist.v1.IsAllowedResponse
	15, // 23: coresystem.gateway.whitelist.v1.WhitelistService.CleanupExpired:output_type -> coresystem.gateway.whitelist.v1.CleanupExpiredResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_whitelist_v1_whitelist_proto_init() }
func file_api_proto_whitelist_v1_whitelist_proto_init() {
	if File_api_proto_whitelist_v1_whitelist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_whitelist_v1_whitelist_proto_rawDesc), len(file_api_proto_whitelist_v1_whitelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_whitelist_v1_whitelist_proto_goTypes,
		DependencyIndexes: file_api_proto_whitelist_v1_whitelist_proto_depIdxs,
		MessageInfos:      file_api_proto_whitelist_v1_whitelist_proto_msgTypes,
	}.Build()
	File_api_proto_whitelist_v1_whitelist_proto = out.File
	file_api_proto_whitelist_v1_whitelist_proto_goTypes = nil
	file_api_proto_whitelist_v1_whitelist_proto_depIdxs = nil
}
