/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface AiChatRequest
 */
export interface AiChatRequest {
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof AiChatRequest
     */
    messages: Array<ChatMessage>;
    /**
     * 
     * @type {string}
     * @memberof AiChatRequest
     */
    model?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AiChatRequest
     */
    stream?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AiChatRequest
     */
    structuredOutputSchema?: string;
}

/**
 * Check if a given object implements the AiChatRequest interface.
 */
export function instanceOfAiChatRequest(value: object): value is AiChatRequest {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function AiChatRequestFromJSON(json: any): AiChatRequest {
    return AiChatRequestFromJSONTyped(json, false);
}

export function AiChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(ChatMessageFromJSON)),
        'model': json['model'] == null ? undefined : json['model'],
        'stream': json['stream'] == null ? undefined : json['stream'],
        'structuredOutputSchema': json['structured_output_schema'] == null ? undefined : json['structured_output_schema'],
    };
}

export function AiChatRequestToJSON(json: any): AiChatRequest {
    return AiChatRequestToJSONTyped(json, false);
}

export function AiChatRequestToJSONTyped(value?: AiChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(ChatMessageToJSON)),
        'model': value['model'],
        'stream': value['stream'],
        'structured_output_schema': value['structuredOutputSchema'],
    };
}

