/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiDocumentsRequest
 */
export interface AiDocumentsRequest {
    /**
     * 
     * @type {string}
     * @memberof AiDocumentsRequest
     */
    url: string;
}

/**
 * Check if a given object implements the AiDocumentsRequest interface.
 */
export function instanceOfAiDocumentsRequest(value: object): value is AiDocumentsRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function AiDocumentsRequestFromJSON(json: any): AiDocumentsRequest {
    return AiDocumentsRequestFromJSONTyped(json, false);
}

export function AiDocumentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiDocumentsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function AiDocumentsRequestToJSON(json: any): AiDocumentsRequest {
    return AiDocumentsRequestToJSONTyped(json, false);
}

export function AiDocumentsRequestToJSONTyped(value?: AiDocumentsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

