/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiSpeechRequest
 */
export interface AiSpeechRequest {
    /**
     * 
     * @type {string}
     * @memberof AiSpeechRequest
     */
    input: string;
    /**
     * 
     * @type {string}
     * @memberof AiSpeechRequest
     */
    voice?: string;
    /**
     * 
     * @type {string}
     * @memberof AiSpeechRequest
     */
    model?: string;
}

/**
 * Check if a given object implements the AiSpeechRequest interface.
 */
export function instanceOfAiSpeechRequest(value: object): value is AiSpeechRequest {
    if (!('input' in value) || value['input'] === undefined) return false;
    return true;
}

export function AiSpeechRequestFromJSON(json: any): AiSpeechRequest {
    return AiSpeechRequestFromJSONTyped(json, false);
}

export function AiSpeechRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiSpeechRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'],
        'voice': json['voice'] == null ? undefined : json['voice'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function AiSpeechRequestToJSON(json: any): AiSpeechRequest {
    return AiSpeechRequestToJSONTyped(json, false);
}

export function AiSpeechRequestToJSONTyped(value?: AiSpeechRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'voice': value['voice'],
        'model': value['model'],
    };
}

