/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Capability
 */
export interface Capability {
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    riskLevel?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Capability
     */
    lazyLoad?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    scope?: string;
}

/**
 * Check if a given object implements the Capability interface.
 */
export function instanceOfCapability(value: object): value is Capability {
    return true;
}

export function CapabilityFromJSON(json: any): Capability {
    return CapabilityFromJSONTyped(json, false);
}

export function CapabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Capability {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'version': json['version'] == null ? undefined : json['version'],
        'description': json['description'] == null ? undefined : json['description'],
        'riskLevel': json['risk_level'] == null ? undefined : json['risk_level'],
        'lazyLoad': json['lazy_load'] == null ? undefined : json['lazy_load'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function CapabilityToJSON(json: any): Capability {
    return CapabilityToJSONTyped(json, false);
}

export function CapabilityToJSONTyped(value?: Capability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'kind': value['kind'],
        'version': value['version'],
        'description': value['description'],
        'risk_level': value['riskLevel'],
        'lazy_load': value['lazyLoad'],
        'scope': value['scope'],
    };
}

