/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Plan } from './Plan';
import {
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
    PlanToJSONTyped,
} from './Plan';

/**
 * 
 * @export
 * @interface GetPlan200Response
 */
export interface GetPlan200Response {
    /**
     * 
     * @type {Plan}
     * @memberof GetPlan200Response
     */
    plan?: Plan;
}

/**
 * Check if a given object implements the GetPlan200Response interface.
 */
export function instanceOfGetPlan200Response(value: object): value is GetPlan200Response {
    return true;
}

export function GetPlan200ResponseFromJSON(json: any): GetPlan200Response {
    return GetPlan200ResponseFromJSONTyped(json, false);
}

export function GetPlan200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlan200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'plan': json['plan'] == null ? undefined : PlanFromJSON(json['plan']),
    };
}

export function GetPlan200ResponseToJSON(json: any): GetPlan200Response {
    return GetPlan200ResponseToJSONTyped(json, false);
}

export function GetPlan200ResponseToJSONTyped(value?: GetPlan200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plan': PlanToJSON(value['plan']),
    };
}

