/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubagentLineage } from './SubagentLineage';
import {
    SubagentLineageFromJSON,
    SubagentLineageFromJSONTyped,
    SubagentLineageToJSON,
    SubagentLineageToJSONTyped,
} from './SubagentLineage';

/**
 * 
 * @export
 * @interface GetSubagentLineage200Response
 */
export interface GetSubagentLineage200Response {
    /**
     * 
     * @type {SubagentLineage}
     * @memberof GetSubagentLineage200Response
     */
    lineage?: SubagentLineage;
}

/**
 * Check if a given object implements the GetSubagentLineage200Response interface.
 */
export function instanceOfGetSubagentLineage200Response(value: object): value is GetSubagentLineage200Response {
    return true;
}

export function GetSubagentLineage200ResponseFromJSON(json: any): GetSubagentLineage200Response {
    return GetSubagentLineage200ResponseFromJSONTyped(json, false);
}

export function GetSubagentLineage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubagentLineage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'lineage': json['lineage'] == null ? undefined : SubagentLineageFromJSON(json['lineage']),
    };
}

export function GetSubagentLineage200ResponseToJSON(json: any): GetSubagentLineage200Response {
    return GetSubagentLineage200ResponseToJSONTyped(json, false);
}

export function GetSubagentLineage200ResponseToJSONTyped(value?: GetSubagentLineage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lineage': SubagentLineageToJSON(value['lineage']),
    };
}

