/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Todo } from './Todo';
import {
    TodoFromJSON,
    TodoFromJSONTyped,
    TodoToJSON,
    TodoToJSONTyped,
} from './Todo';

/**
 * 
 * @export
 * @interface GetTodo200Response
 */
export interface GetTodo200Response {
    /**
     * 
     * @type {Todo}
     * @memberof GetTodo200Response
     */
    todo?: Todo;
}

/**
 * Check if a given object implements the GetTodo200Response interface.
 */
export function instanceOfGetTodo200Response(value: object): value is GetTodo200Response {
    return true;
}

export function GetTodo200ResponseFromJSON(json: any): GetTodo200Response {
    return GetTodo200ResponseFromJSONTyped(json, false);
}

export function GetTodo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTodo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'todo': json['todo'] == null ? undefined : TodoFromJSON(json['todo']),
    };
}

export function GetTodo200ResponseToJSON(json: any): GetTodo200Response {
    return GetTodo200ResponseToJSONTyped(json, false);
}

export function GetTodo200ResponseToJSONTyped(value?: GetTodo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'todo': TodoToJSON(value['todo']),
    };
}

