/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvokeRequest
 */
export interface InvokeRequest {
    /**
     * User message content (max 100 KB)
     * @type {string}
     * @memberof InvokeRequest
     */
    content: string;
    /**
     * Model identifier. Falls back to DEFAULT_MODEL env.
     * @type {string}
     * @memberof InvokeRequest
     */
    model?: string;
    /**
     * Optional session key for context continuity.
     * @type {string}
     * @memberof InvokeRequest
     */
    sessionKey?: string;
    /**
     * Optional thread ID for conversation threading.
     * @type {string}
     * @memberof InvokeRequest
     */
    threadId?: string;
    /**
     * JSON Schema string for structured output.
     * @type {string}
     * @memberof InvokeRequest
     */
    structuredOutputSchema?: string;
    /**
     * Zero data retention — if true, no data is persisted.
     * @type {boolean}
     * @memberof InvokeRequest
     */
    zdr?: boolean;
    /**
     * Maximum cost in USD for this request.
     * @type {number}
     * @memberof InvokeRequest
     */
    maxCostUsd?: number;
    /**
     * Maximum output tokens.
     * @type {number}
     * @memberof InvokeRequest
     */
    maxTokens?: number;
}

/**
 * Check if a given object implements the InvokeRequest interface.
 */
export function instanceOfInvokeRequest(value: object): value is InvokeRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function InvokeRequestFromJSON(json: any): InvokeRequest {
    return InvokeRequestFromJSONTyped(json, false);
}

export function InvokeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvokeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'model': json['model'] == null ? undefined : json['model'],
        'sessionKey': json['session_key'] == null ? undefined : json['session_key'],
        'threadId': json['thread_id'] == null ? undefined : json['thread_id'],
        'structuredOutputSchema': json['structured_output_schema'] == null ? undefined : json['structured_output_schema'],
        'zdr': json['zdr'] == null ? undefined : json['zdr'],
        'maxCostUsd': json['max_cost_usd'] == null ? undefined : json['max_cost_usd'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
    };
}

export function InvokeRequestToJSON(json: any): InvokeRequest {
    return InvokeRequestToJSONTyped(json, false);
}

export function InvokeRequestToJSONTyped(value?: InvokeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'model': value['model'],
        'session_key': value['sessionKey'],
        'thread_id': value['threadId'],
        'structured_output_schema': value['structuredOutputSchema'],
        'zdr': value['zdr'],
        'max_cost_usd': value['maxCostUsd'],
        'max_tokens': value['maxTokens'],
    };
}

