/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Plan } from './Plan';
import {
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
    PlanToJSONTyped,
} from './Plan';

/**
 * 
 * @export
 * @interface ListPlans200Response
 */
export interface ListPlans200Response {
    /**
     * 
     * @type {Array<Plan>}
     * @memberof ListPlans200Response
     */
    plans?: Array<Plan>;
}

/**
 * Check if a given object implements the ListPlans200Response interface.
 */
export function instanceOfListPlans200Response(value: object): value is ListPlans200Response {
    return true;
}

export function ListPlans200ResponseFromJSON(json: any): ListPlans200Response {
    return ListPlans200ResponseFromJSONTyped(json, false);
}

export function ListPlans200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPlans200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'plans': json['plans'] == null ? undefined : ((json['plans'] as Array<any>).map(PlanFromJSON)),
    };
}

export function ListPlans200ResponseToJSON(json: any): ListPlans200Response {
    return ListPlans200ResponseToJSONTyped(json, false);
}

export function ListPlans200ResponseToJSONTyped(value?: ListPlans200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plans': value['plans'] == null ? undefined : ((value['plans'] as Array<any>).map(PlanToJSON)),
    };
}

