/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlanState = {
    Unspecified: 'UNSPECIFIED',
    Draft: 'DRAFT',
    Proposed: 'PROPOSED',
    Approved: 'APPROVED',
    Executing: 'EXECUTING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Rejected: 'REJECTED',
    Superseded: 'SUPERSEDED',
    Archived: 'ARCHIVED'
} as const;
export type PlanState = typeof PlanState[keyof typeof PlanState];


export function instanceOfPlanState(value: any): boolean {
    for (const key in PlanState) {
        if (Object.prototype.hasOwnProperty.call(PlanState, key)) {
            if (PlanState[key as keyof typeof PlanState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlanStateFromJSON(json: any): PlanState {
    return PlanStateFromJSONTyped(json, false);
}

export function PlanStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanState {
    return json as PlanState;
}

export function PlanStateToJSON(value?: PlanState | null): any {
    return value as any;
}

export function PlanStateToJSONTyped(value: any, ignoreDiscriminator: boolean): PlanState {
    return value as PlanState;
}

