/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanState } from './PlanState';
import {
    PlanStateFromJSON,
    PlanStateFromJSONTyped,
    PlanStateToJSON,
    PlanStateToJSONTyped,
} from './PlanState';
import type { PlanStep } from './PlanStep';
import {
    PlanStepFromJSON,
    PlanStepFromJSONTyped,
    PlanStepToJSON,
    PlanStepToJSONTyped,
} from './PlanStep';

/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    runId?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    threadId?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    author?: string;
    /**
     * 
     * @type {PlanState}
     * @memberof Plan
     */
    state?: PlanState;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    summary?: string;
    /**
     * 
     * @type {Array<PlanStep>}
     * @memberof Plan
     */
    steps?: Array<PlanStep>;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    supersedes?: string;
}



/**
 * Check if a given object implements the Plan interface.
 */
export function instanceOfPlan(value: object): value is Plan {
    return true;
}

export function PlanFromJSON(json: any): Plan {
    return PlanFromJSONTyped(json, false);
}

export function PlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'threadId': json['thread_id'] == null ? undefined : json['thread_id'],
        'author': json['author'] == null ? undefined : json['author'],
        'state': json['state'] == null ? undefined : PlanStateFromJSON(json['state']),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(PlanStepFromJSON)),
        'supersedes': json['supersedes'] == null ? undefined : json['supersedes'],
    };
}

export function PlanToJSON(json: any): Plan {
    return PlanToJSONTyped(json, false);
}

export function PlanToJSONTyped(value?: Plan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'run_id': value['runId'],
        'thread_id': value['threadId'],
        'author': value['author'],
        'state': PlanStateToJSON(value['state']),
        'summary': value['summary'],
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(PlanStepToJSON)),
        'supersedes': value['supersedes'],
    };
}

