/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Acknowledgement for async/queued AI modality requests.
 * @export
 * @interface QueuedResponse
 */
export interface QueuedResponse {
    /**
     * 
     * @type {string}
     * @memberof QueuedResponse
     */
    id?: string;
    /**
     * 
     * @type {QueuedResponseStatusEnum}
     * @memberof QueuedResponse
     */
    status?: QueuedResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof QueuedResponse
     */
    note?: string;
}


/**
 * @export
 */
export const QueuedResponseStatusEnum = {
    Queued: 'queued',
    NotImplemented: 'not_implemented'
} as const;
export type QueuedResponseStatusEnum = typeof QueuedResponseStatusEnum[keyof typeof QueuedResponseStatusEnum];


/**
 * Check if a given object implements the QueuedResponse interface.
 */
export function instanceOfQueuedResponse(value: object): value is QueuedResponse {
    return true;
}

export function QueuedResponseFromJSON(json: any): QueuedResponse {
    return QueuedResponseFromJSONTyped(json, false);
}

export function QueuedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueuedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function QueuedResponseToJSON(json: any): QueuedResponse {
    return QueuedResponseToJSONTyped(json, false);
}

export function QueuedResponseToJSONTyped(value?: QueuedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'note': value['note'],
    };
}

