/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single chunk in the invoke/stream SSE response.
 * @export
 * @interface SseChunk
 */
export interface SseChunk {
    /**
     * 
     * @type {string}
     * @memberof SseChunk
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof SseChunk
     */
    delta?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SseChunk
     */
    done?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SseChunk
     */
    modelUsed?: string;
    /**
     * 
     * @type {number}
     * @memberof SseChunk
     */
    inputTokens?: number;
    /**
     * 
     * @type {number}
     * @memberof SseChunk
     */
    outputTokens?: number;
}

/**
 * Check if a given object implements the SseChunk interface.
 */
export function instanceOfSseChunk(value: object): value is SseChunk {
    return true;
}

export function SseChunkFromJSON(json: any): SseChunk {
    return SseChunkFromJSONTyped(json, false);
}

export function SseChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): SseChunk {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'delta': json['delta'] == null ? undefined : json['delta'],
        'done': json['done'] == null ? undefined : json['done'],
        'modelUsed': json['model_used'] == null ? undefined : json['model_used'],
        'inputTokens': json['input_tokens'] == null ? undefined : json['input_tokens'],
        'outputTokens': json['output_tokens'] == null ? undefined : json['output_tokens'],
    };
}

export function SseChunkToJSON(json: any): SseChunk {
    return SseChunkToJSONTyped(json, false);
}

export function SseChunkToJSONTyped(value?: SseChunk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_id': value['requestId'],
        'delta': value['delta'],
        'done': value['done'],
        'model_used': value['modelUsed'],
        'input_tokens': value['inputTokens'],
        'output_tokens': value['outputTokens'],
    };
}

