/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoState } from './TodoState';
import {
    TodoStateFromJSON,
    TodoStateFromJSONTyped,
    TodoStateToJSON,
    TodoStateToJSONTyped,
} from './TodoState';

/**
 * 
 * @export
 * @interface Todo
 */
export interface Todo {
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    threadId?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    runId?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    assignee?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    description?: string;
    /**
     * 
     * @type {TodoState}
     * @memberof Todo
     */
    state?: TodoState;
    /**
     * 
     * @type {TodoPriorityEnum}
     * @memberof Todo
     */
    priority?: TodoPriorityEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Todo
     */
    blockedBy?: Array<string>;
}


/**
 * @export
 */
export const TodoPriorityEnum = {
    Unspecified: 'UNSPECIFIED',
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type TodoPriorityEnum = typeof TodoPriorityEnum[keyof typeof TodoPriorityEnum];


/**
 * Check if a given object implements the Todo interface.
 */
export function instanceOfTodo(value: object): value is Todo {
    return true;
}

export function TodoFromJSON(json: any): Todo {
    return TodoFromJSONTyped(json, false);
}

export function TodoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Todo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'threadId': json['thread_id'] == null ? undefined : json['thread_id'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'assignee': json['assignee'] == null ? undefined : json['assignee'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'state': json['state'] == null ? undefined : TodoStateFromJSON(json['state']),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'blockedBy': json['blocked_by'] == null ? undefined : json['blocked_by'],
    };
}

export function TodoToJSON(json: any): Todo {
    return TodoToJSONTyped(json, false);
}

export function TodoToJSONTyped(value?: Todo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'thread_id': value['threadId'],
        'run_id': value['runId'],
        'assignee': value['assignee'],
        'title': value['title'],
        'description': value['description'],
        'state': TodoStateToJSON(value['state']),
        'priority': value['priority'],
        'blocked_by': value['blockedBy'],
    };
}

