/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanState } from './PlanState';
import {
    PlanStateFromJSON,
    PlanStateFromJSONTyped,
    PlanStateToJSON,
    PlanStateToJSONTyped,
} from './PlanState';

/**
 * 
 * @export
 * @interface TransitionPlanBody
 */
export interface TransitionPlanBody {
    /**
     * 
     * @type {PlanState}
     * @memberof TransitionPlanBody
     */
    targetState: PlanState;
    /**
     * 
     * @type {string}
     * @memberof TransitionPlanBody
     */
    reason?: string;
}



/**
 * Check if a given object implements the TransitionPlanBody interface.
 */
export function instanceOfTransitionPlanBody(value: object): value is TransitionPlanBody {
    if (!('targetState' in value) || value['targetState'] === undefined) return false;
    return true;
}

export function TransitionPlanBodyFromJSON(json: any): TransitionPlanBody {
    return TransitionPlanBodyFromJSONTyped(json, false);
}

export function TransitionPlanBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitionPlanBody {
    if (json == null) {
        return json;
    }
    return {
        
        'targetState': PlanStateFromJSON(json['target_state']),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function TransitionPlanBodyToJSON(json: any): TransitionPlanBody {
    return TransitionPlanBodyToJSONTyped(json, false);
}

export function TransitionPlanBodyToJSONTyped(value?: TransitionPlanBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_state': PlanStateToJSON(value['targetState']),
        'reason': value['reason'],
    };
}

