/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoState } from './TodoState';
import {
    TodoStateFromJSON,
    TodoStateFromJSONTyped,
    TodoStateToJSON,
    TodoStateToJSONTyped,
} from './TodoState';

/**
 * 
 * @export
 * @interface TransitionTodoBody
 */
export interface TransitionTodoBody {
    /**
     * 
     * @type {TodoState}
     * @memberof TransitionTodoBody
     */
    status: TodoState;
    /**
     * 
     * @type {string}
     * @memberof TransitionTodoBody
     */
    reason?: string;
}



/**
 * Check if a given object implements the TransitionTodoBody interface.
 */
export function instanceOfTransitionTodoBody(value: object): value is TransitionTodoBody {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TransitionTodoBodyFromJSON(json: any): TransitionTodoBody {
    return TransitionTodoBodyFromJSONTyped(json, false);
}

export function TransitionTodoBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitionTodoBody {
    if (json == null) {
        return json;
    }
    return {
        
        'status': TodoStateFromJSON(json['status']),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function TransitionTodoBodyToJSON(json: any): TransitionTodoBody {
    return TransitionTodoBodyToJSONTyped(json, false);
}

export function TransitionTodoBodyToJSONTyped(value?: TransitionTodoBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': TodoStateToJSON(value['status']),
        'reason': value['reason'],
    };
}

