#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "$0")/../.." && pwd)
runner="$root/tests/scripts/run-isolated-real-authority.sh"
compose="$root/tests/e2e/isolated/real-authority-compose.yml"
fixture="$root/tests/e2e/isolated/real-authority-fixture.mjs"
tls_fixture="$root/tests/e2e/isolated/generate-user-core-grpc-tls.sh"

for file in "$runner" "$compose" "$fixture" "$tls_fixture"; do
  [ -f "$file" ] || { echo "FAIL: missing real-authority fixture $file" >&2; exit 1; }
done

# Runtime isolation and cleanup must be generated by the harness, never selected
# by a caller or inherited from a shared Control/Data compose project.
rg -Fq 'dpv2-real-authority-e2e-' "$runner"
! rg -q 'REAL_AUTHORITY_(PROJECT|SUFFIX)|container_name:|ports:' "$compose" "$runner"
rg -Fq 'umask 077' "$runner"
rg -Fq 'chmod 700 "$runtime_dir"' "$runner"
rg -Fq 'REAL_AUTHORITY_FIXTURE_OUTPUT_DIR="$runtime_dir"' "$runner"
rg -Fq 'export DOCUMENTS_GDPR_NATS_PASSWORD=' "$runner"
rg -Fq 'trap cleanup EXIT' "$runner"
rg -Fq 'down --volumes --remove-orphans' "$runner"
rg -Fq 'refusing collision with existing isolated project resources' "$runner"
rg -Fq '[ "$bus_network" != "inter-plane-bus" ]' "$runner"
rg -Fq 'config --quiet' "$runner"
rg -Fq 'readonly -a compose' "$runner"
! rg -q 'docker logs|set -x|set -o xtrace' "$runner"

# Auth and User Core use distinct databases on the disposable Postgres and are
# reachable only by aliases on the per-run networks.
rg -Fq '/auth_service?sslmode=disable' "$compose"
rg -Fq '/user_service?sslmode=disable' "$compose"
rg -Fq 'AUTH_DATABASE_URL:' "$compose"
rg -Fq 'authority-db-init:' "$compose"
rg -Fq 'createdb --host=postgres' "$compose"
rg -Fq 'pg_isready --host=postgres' "$compose"
rg -Fq 'authority-db-init:' "$compose"
test "$(rg -c 'authority-db-init:' "$compose")" -ge 3
rg -Fq 'aliases: ["auth-core"]' "$compose"
rg -Fq 'aliases: ["user-core"]' "$compose"
rg -Fq 'profiles: ["mock-authority"]' "$compose"
rg -Fq 'http://auth-core:3011/api/convex-auth' "$compose"
rg -Fq 'NATS_ALLOW_TOKEN_FALLBACK: "1"' "$compose"
rg -Fq 'NATS_SHARED_ALLOW_TOKEN_FALLBACK: "0"' "$compose"
rg -Fq 'AUTH_CORE_JWT_PUBLIC_KEY_FILE: /app/keys/convex-auth.pub' "$compose"
rg -Fq 'BEARER_TOKEN_ENABLED: "true"' "$compose"
rg -Fq 'ALLOW_USER_CREATE_ORG: "true"' "$compose"
rg -Fq 'subjectAltName=DNS:user-core' "$tls_fixture"

# Auth gRPC starts with a generated, audience/scope-bound credential registry.
# The disposable retrieval principal gets token validation only and receives a
# token generated independently of any legacy internal compatibility key.
rg -Fq 'AUTH_GRPC_SERVICE_CREDENTIALS_FILE: /run/secrets/auth-grpc-service-credentials.json' "$compose"
rg -Fq '${REAL_AUTHORITY_AUTH_GRPC_CREDENTIALS_FILE:?required}:/run/secrets/auth-grpc-service-credentials.json:ro' "$compose"
rg -Fq 'REAL_AUTHORITY_AUTH_GRPC_RETRIEVAL_TOKEN=' "$runner"
rg -Fq 'REAL_AUTHORITY_AUTH_GRPC_CREDENTIALS_FILE="$runtime_dir/auth-grpc-service-credentials.json"' "$runner"
rg -Fq 'credentialId: "retrieval-primary"' "$runner"
rg -Fq 'principal: "retrieval-engine"' "$runner"
rg -Fq 'audience: "auth-core"' "$runner"
rg -Fq 'scopes: ["auth:token:validate"]' "$runner"
rg -Fq 'mode: 0o600' "$runner"
! rg -Fq 'REAL_AUTHORITY_AUTH_GRPC_RETRIEVAL_TOKEN="$REAL_AUTHORITY_INTERNAL_' "$runner"

# Auth and User use reciprocal, file-backed service-principal tuples. The Auth
# client and User registry share exactly one generated token, while the reverse
# User-to-Auth contract receives a different generated token and bounded scopes.
rg -Fq 'USER_CORE_GRPC_CLIENT_CREDENTIAL_FILE: /run/secrets/auth-user-grpc-client.json' "$compose"
rg -Fq 'USER_CORE_GRPC_SERVICE_CREDENTIALS_FILE: /run/secrets/user-grpc-service-credentials.json' "$compose"
rg -Fq 'USER_CORE_GRPC_TLS_CA_FILE: /run/secrets/user-grpc-tls-ca.pem' "$compose"
rg -Fq 'USER_CORE_GRPC_TLS_CERT_FILE: /run/secrets/user-grpc-tls-server.pem' "$compose"
rg -Fq 'USER_CORE_GRPC_TLS_KEY_FILE: /run/secrets/user-grpc-tls-server-key.pem' "$compose"
rg -Fq 'USER_AUTH_INTERNAL_CLIENT_CREDENTIAL_FILE: /run/secrets/user-auth-internal-client.json' "$compose"
rg -Fq 'AUTH_INTERNAL_SERVICE_CREDENTIALS_FILE: /run/secrets/auth-internal-service-credentials.json' "$compose"
for file in \
  auth-user-grpc-client.json \
  user-grpc-service-credentials.json \
  user-auth-internal-client.json \
  auth-internal-service-credentials.json; do
  rg -Fq "$file:ro" "$compose"
done
rg -Fq 'REAL_AUTHORITY_USER_GRPC_TOKEN=$(openssl rand -hex 32)' "$runner"
rg -Fq 'REAL_AUTHORITY_USER_AUTH_INTERNAL_TOKEN=$(openssl rand -hex 32)' "$runner"
rg -Fq 'credentialId: "auth-core-isolated"' "$runner"
rg -Fq 'audience: "user-core-grpc"' "$runner"
for method in CreateUser UpdateUser GetUserByEmail CreateSession GetUser DeleteUser HealthCheck; do
  rg -Fq "/user.v1.UserService/$method" "$runner"
done
rg -Fq 'credentialId: "user-core-isolated"' "$runner"
rg -Fq 'principal: "user-core"' "$runner"
rg -Fq 'audience: "auth-core-internal"' "$runner"
for scope in oauth:token:read oauth:token:refresh nats:authenticate auth:admin; do
  rg -Fq "$scope" "$runner"
done
! rg -Fq 'REAL_AUTHORITY_USER_GRPC_TOKEN="$REAL_AUTHORITY_USER_AUTH_INTERNAL_TOKEN"' "$runner"
rg -Fq 'generate-user-core-grpc-tls.sh' "$runner"
rg -Fq 'REAL_AUTHORITY_USER_GRPC_TLS_CA_FILE=' "$runner"
rg -Fq 'REAL_AUTHORITY_USER_GRPC_TLS_CERT_FILE=' "$runner"
rg -Fq 'REAL_AUTHORITY_USER_GRPC_TLS_KEY_FILE=' "$runner"
rg -Fq 'assert_plaintext_user_grpc_rejected' "$runner"
rg -Fq 'grpc.credentials.createInsecure()' "$runner"

# Readiness is the usable JWKS document, not merely a running process.
rg -Fq 'healthcheck:' "$compose"
rg -Fq '/api/convex-auth/jwks' "$compose"
rg -Fq 'condition: service_healthy' "$compose"

# The service-token audit stream is deliberately bounded and provisioned before
# Auth starts. No global/destructive broker operations are permitted.
rg -Fq 'provision-audit' "$compose"
rg -Fq 'condition: service_completed_successfully' "$compose"
rg -Fq 'subjects: ["verevon.audit.v2.control.auth-core.>"]' "$fixture"
rg -Fq 'max_msgs: 10_000' "$fixture"
rg -Fq 'max_bytes: 8 * 1024 * 1024' "$fixture"
rg -Fq 'max_age: nanos(60 * 60 * 1_000)' "$fixture"
! rg -qi 'stream.*(purge|delete)|consumer.*delete|jsm\.streams\.delete' "$fixture"

# The live fixture must use supported contracts and prove both positive and
# negative authority decisions without exposing response bodies or credentials.
for contract in \
  '/api/auth/sign-up/email' \
  '/api/auth/sign-in/email' \
  '/api/auth/organization/create' \
  '/api/auth/organization/set-active' \
  '/api/auth/get-session' \
  '/api/data-plane/token' \
  '/api/data-plane/internal-token' \
  '/api/convex-auth/jwks' \
  '/api/v1/me/session-context' \
  '/api/v1/users/onboarding/complete' \
  '/api/v1/internal/membership/decision' \
  '/api/v1/internal/authz/visible' \
  '/api/control-policy/internal-token' \
  '/api/v1/internal/authorization/data-plane/decision'; do
  rg -Fq "$contract" "$fixture"
done
rg -Fq 'users.length !== 2' "$fixture"
rg -Fq 'ownDecision.data?.reason !==' "$fixture"
rg -Fq 'control-policy member allow decision was invalid' "$fixture"
rg -Fq 'denied.data?.reason !==' "$fixture"
rg -Fq 'control-policy non-member denial was invalid' "$fixture"
rg -Fq 'cross-tenant policy request was not rejected' "$fixture"
rg -Fq 'visibility tenant mismatch was not rejected' "$fixture"
rg -Fq 'JWKS does not match the mounted Auth public key' "$fixture"
rg -Fq 'set-auth-token' "$fixture"
rg -Fq 'Authorization: `Bearer ${sessionToken}`' "$fixture"
rg -Fq 'writeFixtureOutput' "$fixture"
rg -Fq 'persistentDataPlaneToken' "$fixture"
rg -Fq 'persistentClaims.zdr !== false' "$fixture"
rg -Fq 'requestWhenDurableAuditReady' "$fixture"
rg -Fq 'expected: [200, 201, 503]' "$fixture"
rg -Fq 'verifyDurableTokenAudit' "$fixture"
rg -Fq 'AbortSignal.timeout' "$fixture"
rg -Fq 'assertExactScopes' "$fixture"
rg -Fq 'header.alg !== "RS256"' "$fixture"
rg -Fq 'completedSessionContext.data?.onboardingStatus !== "COMPLETED"' "$fixture"
rg -Fq 'allowPersistentData' "$runner"
rg -Fq 'mode: 0o600' "$fixture"
! rg -q 'console\.(log|error).*?(token|cookie|password|secret|credential|body|payload)' "$fixture"

bash -n "$runner"
node --check "$fixture"

# Parse the additive YAML without contacting the Docker daemon. The real runner
# performs Docker Compose's authoritative config validation immediately before
# startup, with all interpolated output suppressed.
ruby -e 'require "yaml"; doc = YAML.safe_load(File.read(ARGV.fetch(0)), aliases: true); abort "missing services" unless doc.fetch("services").is_a?(Hash)' "$compose"

echo "PASS: isolated real Auth/User/Control authority harness contract"
