# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.plan_state import PlanState

class TestPlanState(unittest.TestCase):
    """PlanState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlanState(self):
        """Test PlanState"""
        # inst = PlanState()

if __name__ == '__main__':
    unittest.main()
