# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.decide_approval_body import DecideApprovalBody

class TestDecideApprovalBody(unittest.TestCase):
    """DecideApprovalBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecideApprovalBody:
        """Test DecideApprovalBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecideApprovalBody`
        """
        model = DecideApprovalBody()
        if include_optional:
            return DecideApprovalBody(
                decision = 'approve',
                reason = ''
            )
        else:
            return DecideApprovalBody(
                decision = 'approve',
        )
        """

    def testDecideApprovalBody(self):
        """Test DecideApprovalBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
