# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.resume_run200_response import ResumeRun200Response

class TestResumeRun200Response(unittest.TestCase):
    """ResumeRun200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResumeRun200Response:
        """Test ResumeRun200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResumeRun200Response`
        """
        model = ResumeRun200Response()
        if include_optional:
            return ResumeRun200Response(
                run_id = '',
                status = 'resume_requested'
            )
        else:
            return ResumeRun200Response(
        )
        """

    def testResumeRun200Response(self):
        """Test ResumeRun200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
