# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.todo_state import TodoState

class TestTodoState(unittest.TestCase):
    """TodoState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTodoState(self):
        """Test TodoState"""
        # inst = TodoState()

if __name__ == '__main__':
    unittest.main()
