# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.invoke_request import InvokeRequest

class TestInvokeRequest(unittest.TestCase):
    """InvokeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvokeRequest:
        """Test InvokeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvokeRequest`
        """
        model = InvokeRequest()
        if include_optional:
            return InvokeRequest(
                content = '',
                model = '',
                session_key = '',
                thread_id = '',
                structured_output_schema = '',
                zdr = True,
                max_cost_usd = 0,
                max_tokens = 0
            )
        else:
            return InvokeRequest(
                content = '',
        )
        """

    def testInvokeRequest(self):
        """Test InvokeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
