# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.plan_step import PlanStep

class TestPlanStep(unittest.TestCase):
    """PlanStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanStep:
        """Test PlanStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanStep`
        """
        model = PlanStep()
        if include_optional:
            return PlanStep(
                id = '',
                title = '',
                operation = '',
                state = 'UNSPECIFIED'
            )
        else:
            return PlanStep(
        )
        """

    def testPlanStep(self):
        """Test PlanStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
