# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.list_capabilities200_response import ListCapabilities200Response

class TestListCapabilities200Response(unittest.TestCase):
    """ListCapabilities200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCapabilities200Response:
        """Test ListCapabilities200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCapabilities200Response`
        """
        model = ListCapabilities200Response()
        if include_optional:
            return ListCapabilities200Response(
                capabilities = [
                    model_plane_sdk.models.capability.Capability(
                        id = '', 
                        name = '', 
                        kind = '', 
                        version = '', 
                        description = '', 
                        risk_level = '', 
                        lazy_load = True, 
                        scope = '', )
                    ],
                has_more = True
            )
        else:
            return ListCapabilities200Response(
        )
        """

    def testListCapabilities200Response(self):
        """Test ListCapabilities200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
