# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.api.capabilities_api import CapabilitiesApi


class TestCapabilitiesApi(unittest.TestCase):
    """CapabilitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CapabilitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_capability(self) -> None:
        """Test case for get_capability

        Get a capability by ID
        """
        pass

    def test_list_capabilities(self) -> None:
        """Test case for list_capabilities

        List registered capabilities
        """
        pass


if __name__ == '__main__':
    unittest.main()
