# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from model_plane_sdk.models.get_plan200_response import GetPlan200Response

class TestGetPlan200Response(unittest.TestCase):
    """GetPlan200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPlan200Response:
        """Test GetPlan200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPlan200Response`
        """
        model = GetPlan200Response()
        if include_optional:
            return GetPlan200Response(
                plan = model_plane_sdk.models.plan.Plan(
                    id = '', 
                    run_id = '', 
                    thread_id = '', 
                    author = '', 
                    state = 'UNSPECIFIED', 
                    summary = '', 
                    steps = [
                        model_plane_sdk.models.plan_step.PlanStep(
                            id = '', 
                            title = '', 
                            operation = '', )
                        ], 
                    supersedes = '', )
            )
        else:
            return GetPlan200Response(
        )
        """

    def testGetPlan200Response(self):
        """Test GetPlan200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
