# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_plane/v1/ids.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'model_plane/v1/ids.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18model_plane/v1/ids.proto\x12\x0emodel_plane.v1\"\x1f\n\x07\x41gentId\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\" \n\x08ThreadId\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"\"\n\nSessionKey\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"\x1d\n\x05RunId\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"\x1e\n\x06StepId\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"$\n\x0c\x43heckpointId\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"&\n\x0eSandboxLeaseId\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"&\n\x0e\x42rowserLeaseId\x12\x14\n\x05value\x18\x01 \x01(\tR\x05valueB\xb0\x01\n\x12\x63om.model_plane.v1B\x08IdsProtoP\x01Z;github.com/triodelab/model-plane/gen/go/model_plane/v1;mpv1\xa2\x02\x03MXX\xaa\x02\rModelPlane.V1\xca\x02\rModelPlane\\V1\xe2\x02\x19ModelPlane\\V1\\GPBMetadata\xea\x02\x0eModelPlane::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_plane.v1.ids_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.model_plane.v1B\010IdsProtoP\001Z;github.com/triodelab/model-plane/gen/go/model_plane/v1;mpv1\242\002\003MXX\252\002\rModelPlane.V1\312\002\rModelPlane\\V1\342\002\031ModelPlane\\V1\\GPBMetadata\352\002\016ModelPlane::V1'
  _globals['_AGENTID']._serialized_start=44
  _globals['_AGENTID']._serialized_end=75
  _globals['_THREADID']._serialized_start=77
  _globals['_THREADID']._serialized_end=109
  _globals['_SESSIONKEY']._serialized_start=111
  _globals['_SESSIONKEY']._serialized_end=145
  _globals['_RUNID']._serialized_start=147
  _globals['_RUNID']._serialized_end=176
  _globals['_STEPID']._serialized_start=178
  _globals['_STEPID']._serialized_end=208
  _globals['_CHECKPOINTID']._serialized_start=210
  _globals['_CHECKPOINTID']._serialized_end=246
  _globals['_SANDBOXLEASEID']._serialized_start=248
  _globals['_SANDBOXLEASEID']._serialized_end=286
  _globals['_BROWSERLEASEID']._serialized_start=288
  _globals['_BROWSERLEASEID']._serialized_end=326
# @@protoc_insertion_point(module_scope)
