# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_plane/v1/sandboxes.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'model_plane/v1/sandboxes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emodel_plane/v1/sandboxes.proto\x12\x0emodel_plane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x93\x01\n\x13\x41\x63quireLeaseRequest\x12\x19\n\x08scope_id\x18\x01 \x01(\tR\x07scopeId\x12\x1d\n\nscope_type\x18\x02 \x01(\tR\tscopeType\x12+\n\x03ttl\x18\x03 \x01(\x0b\x32\x19.google.protobuf.DurationR\x03ttl\x12\x15\n\x06org_id\x18\x04 \x01(\tR\x05orgId\"\x88\x01\n\x14\x41\x63quireLeaseResponse\x12\x19\n\x08lease_id\x18\x01 \x01(\tR\x07leaseId\x12\x1a\n\x08\x65ndpoint\x18\x02 \x01(\tR\x08\x65ndpoint\x12\x39\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\texpiresAt\"0\n\x13ReleaseLeaseRequest\x12\x19\n\x08lease_id\x18\x01 \x01(\tR\x07leaseId\"2\n\x14ReleaseLeaseResponse\x12\x1a\n\x08released\x18\x01 \x01(\x08R\x08released\"B\n\x0fSnapshotRequest\x12\x19\n\x08lease_id\x18\x01 \x01(\tR\x07leaseId\x12\x14\n\x05label\x18\x02 \x01(\tR\x05label\"R\n\x10SnapshotResponse\x12\x1f\n\x0bsnapshot_id\x18\x01 \x01(\tR\nsnapshotId\x12\x1d\n\nobject_key\x18\x02 \x01(\tR\tobjectKey\"\x16\n\x14SandboxHealthRequest\"/\n\x15SandboxHealthResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status2\xf3\x02\n\x0eSandboxManager\x12Y\n\x0c\x41\x63quireLease\x12#.model_plane.v1.AcquireLeaseRequest\x1a$.model_plane.v1.AcquireLeaseResponse\x12Y\n\x0cReleaseLease\x12#.model_plane.v1.ReleaseLeaseRequest\x1a$.model_plane.v1.ReleaseLeaseResponse\x12T\n\x0fSnapshotSandbox\x12\x1f.model_plane.v1.SnapshotRequest\x1a .model_plane.v1.SnapshotResponse\x12U\n\x06Health\x12$.model_plane.v1.SandboxHealthRequest\x1a%.model_plane.v1.SandboxHealthResponseB\xb6\x01\n\x12\x63om.model_plane.v1B\x0eSandboxesProtoP\x01Z;github.com/triodelab/model-plane/gen/go/model_plane/v1;mpv1\xa2\x02\x03MXX\xaa\x02\rModelPlane.V1\xca\x02\rModelPlane\\V1\xe2\x02\x19ModelPlane\\V1\\GPBMetadata\xea\x02\x0eModelPlane::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_plane.v1.sandboxes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.model_plane.v1B\016SandboxesProtoP\001Z;github.com/triodelab/model-plane/gen/go/model_plane/v1;mpv1\242\002\003MXX\252\002\rModelPlane.V1\312\002\rModelPlane\\V1\342\002\031ModelPlane\\V1\\GPBMetadata\352\002\016ModelPlane::V1'
  _globals['_ACQUIRELEASEREQUEST']._serialized_start=116
  _globals['_ACQUIRELEASEREQUEST']._serialized_end=263
  _globals['_ACQUIRELEASERESPONSE']._serialized_start=266
  _globals['_ACQUIRELEASERESPONSE']._serialized_end=402
  _globals['_RELEASELEASEREQUEST']._serialized_start=404
  _globals['_RELEASELEASEREQUEST']._serialized_end=452
  _globals['_RELEASELEASERESPONSE']._serialized_start=454
  _globals['_RELEASELEASERESPONSE']._serialized_end=504
  _globals['_SNAPSHOTREQUEST']._serialized_start=506
  _globals['_SNAPSHOTREQUEST']._serialized_end=572
  _globals['_SNAPSHOTRESPONSE']._serialized_start=574
  _globals['_SNAPSHOTRESPONSE']._serialized_end=656
  _globals['_SANDBOXHEALTHREQUEST']._serialized_start=658
  _globals['_SANDBOXHEALTHREQUEST']._serialized_end=680
  _globals['_SANDBOXHEALTHRESPONSE']._serialized_start=682
  _globals['_SANDBOXHEALTHRESPONSE']._serialized_end=729
  _globals['_SANDBOXMANAGER']._serialized_start=732
  _globals['_SANDBOXMANAGER']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
