export type ModulePhoto = {
	image: string;
	imageAlt: string;
	imagePosition: string;
	imageWidth: number;
	imageHeight: number;
	source: string;
	credit: string;
	note: string;
};

const crosswalkPhoto = {
	image: "/verevon-mood/modules/crosswalk-motion-user.png",
	imageAlt: "En tydelig person med veske krysser et fotgjengerfelt blant mennesker i bevegelsesuskarphet, i svart-hvitt",
	imagePosition: "center",
	imageWidth: 1024,
	imageHeight: 1536,
	source: "/verevon-mood/modules/crosswalk-motion-user.png",
	credit: "Lokalt bilde fra deg",
} as const;

// User-supplied shortlist, reviewed in the carousel's 4:5 crop.
// Homepage selections live in feature-workflow-cards.ts; compare alternatives at /dev/module-photos.
export const modulePhotoOptions = {
	knowledge: [
		{
			image: "https://images.pexels.com/photos/8371734/pexels-photo-8371734.jpeg",
			imageAlt: "En person undersøker dokumenter og mapper ved et opplyst arbeidsbord, sett ovenfra",
			imagePosition: "15% center",
			imageWidth: 5160,
			imageHeight: 3440,
			source: "https://www.pexels.com/photo/high-angle-shot-of-men-working-in-front-of-a-table-8371734/",
			credit: "cottonbro studio / Pexels",
			note: "Kilder i aktiv bruk. Varmt bordlys og en rolig, konsentrert situasjon.",
		},
		{
			image: "https://images.pexels.com/photos/6538616/pexels-photo-6538616.jpeg",
			imageAlt: "En kvinne holder en stor stabel med mapper og løse dokumenter",
			imagePosition: "center",
			imageWidth: 4039,
			imageHeight: 6059,
			source: "https://www.pexels.com/photo/a-woman-holding-a-pile-of-file-folders-6538616/",
			credit: "cottonbro studio / Pexels",
			note: "Lysere og kjøligere. Viser dokumentmengden tydelig, men handler mer om arbeidsbyrde enn undersøkelse.",
		},
		{
			image: "https://images.unsplash.com/photo-1565449446922-702749bcaf1b?auto=format&fit=max&q=90",
			imageAlt: "Et lyst bibliotek med bokhyller og åpne etasjer rundt et stort atrium",
			imagePosition: "center",
			imageWidth: 4592,
			imageHeight: 2584,
			source: "https://unsplash.com/photos/white-concrete-building-SiOJXlWeWc0",
			credit: "Kumas Taverne / Unsplash",
			note: "Lys bibliotekarkitektur og tydelig struktur. Et romlig alternativ til nærbildene av dokumenter.",
		},
		{
			image: "https://images.pexels.com/photos/15361514/pexels-photo-15361514.jpeg",
			imageAlt: "En mann leser en bok i et stille bibliotek omgitt av bokhyller",
			imagePosition: "center",
			imageWidth: 3264,
			imageHeight: 4896,
			source: "https://www.pexels.com/nb-no/bilde/mann-avslapping-boker-lese-15361514/",
			credit: "miniperde / Pexels",
			note: "En person fordypet i en bok, omgitt av kilder. Varme bruntoner og et stille bibliotek gir motivet ro.",
		},
		{
			image: "/verevon-mood/problem-research/active/knowledge-library-reader.jpg",
			imageAlt: "En person undersøker bøker foran høye, tettfylte bokhyller",
			imagePosition: "50% 100%",
			imageWidth: 4000,
			imageHeight: 6000,
			source: "/verevon-mood/problem-research/active/knowledge-library-reader.jpg",
			credit: "Fra det lokale bildebiblioteket",
			note: "Fra listen din. En person leter blant kilder. Et tydeligere bilde på søk og kunnskap, med rolige, varme materialer.",
		},
		{
			image: "/verevon-mood/problem-research/active/knowledge-books-people.jpg",
			imageAlt: "Mennesker undersøker bøker i en bokhandel, sett ovenfra mellom hyllene",
			imagePosition: "center",
			imageWidth: 3000,
			imageHeight: 4503,
			source: "/verevon-mood/problem-research/active/knowledge-books-people.jpg",
			credit: "Fra det lokale bildebiblioteket",
			note: "Fra listen din. Kilder blir aktivt undersøkt, med dagslys og flere lag i motivet. Litt mer visuelt innhold enn bibliotekleseren.",
		},
		{
			image: "https://images.pexels.com/photos/4943605/pexels-photo-4943605.jpeg",
			imageAlt: "To personer leser og undersøker en bok sammen, sett gjennom et stort vindu",
			imagePosition: "50% 65%",
			imageWidth: 3574,
			imageHeight: 5361,
			source: "https://www.pexels.com/photo/women-reading-a-book-near-glass-windows-4943605/",
			credit: "Nataliya Vaitkevich / Pexels",
			note: "Nytt forslag gjennom glass. En felles kilde og konsentrert lesing gjør kunnskapsarbeidet synlig. Lysere og roligere enn kontormotivene.",
		},
		{
			image: "https://images.pexels.com/photos/7083902/pexels-photo-7083902.jpeg",
			imageAlt: "To personer undersøker dokumenter og et nettbrett ved et bord, sett gjennom glass ovenfra",
			imagePosition: "center",
			imageWidth: 6000,
			imageHeight: 4000,
			source: "https://www.pexels.com/photo/male-business-partners-working-with-documents-7083902/",
			credit: "Laura Tancredi / Pexels",
			note: "Nytt forslag gjennom glass. Papir og digitale kilder vurderes sammen. Nærmere bedriftsarbeid, men ligner mer på håndmotivet i Arbeidsflate.",
		},
		{
			image: "https://images.pexels.com/photos/8371731/pexels-photo-8371731.jpeg",
			imageAlt: "En person undersøker dokumenter i en arkivboks i varmt arbeidslys",
			imagePosition: "center",
			imageWidth: 4167,
			imageHeight: 6251,
			source: "https://www.pexels.com/photo/detective-with-a-box-of-files-8371731/",
			credit: "cottonbro studio / Pexels",
			note: "Uten glass. En person leter aktivt i dokumenter. Varme papirtoner og konsentrert lys gjør både mennesket og kildene tydelige.",
		},
		{
			image: "https://images.unsplash.com/photo-1695388474402-ed805a890d8d?auto=format&fit=max&q=90",
			imageAlt: "En person leser og sammenligner papirer ved et bord i mykt dagslys",
			imagePosition: "center",
			imageWidth: 5616,
			imageHeight: 3744,
			source: "https://unsplash.com/photos/a-woman-sitting-at-a-table-reading-a-paper-ecHGTPfjNfA",
			credit: "Anastassia Anufrieva / Unsplash",
			note: "Uten glass. Nært på selve kildearbeidet, med papirer og hender i dagslys. Et roligere utsnitt som lar materialet dominere.",
		},
	],
	agents: [
		{
			image: "https://images.unsplash.com/photo-1682074902179-079c3dc75fc9?auto=format&fit=max&q=90",
			imageAlt: "Personer på en rulletrapp, med diagonal bevegelse og uskarphet rundt en tydelig skikkelse",
			imagePosition: "center",
			imageWidth: 4480,
			imageHeight: 6720,
			source: "https://unsplash.com/photos/a-person-riding-an-escalator-with-a-skateboard-ALLdonCL0yA",
			credit: "fabian jones / Unsplash",
			note: "Rulletrappen gir retning og fremdrift. Mørke, kjølige toner og naturlig bevegelsesuskarphet.",
		},
		{
			image: "https://images.unsplash.com/photo-1548783300-70b41bc84f56?auto=format&fit=max&q=90",
			imageAlt: "En person i dress går over et fotgjengerfelt med markerte diagonale striper",
			imagePosition: "center",
			imageWidth: 4540,
			imageHeight: 6810,
			source: "https://unsplash.com/photos/man-in-black-formal-suit-jacket-and-pants-carrying-black-bag-while-walking-on-pedestrian-lane-during-daytime-wUZjnOv7t0g",
			credit: "Ryoji Iwata / Unsplash",
			note: "Et lysere og mer grafisk alternativ, med en tydelig person på vei videre.",
		},
		{
			...crosswalkPhoto,
			note: "Bildet du sendte: en tydelig person i en strøm av bevegelse. Grafisk svart-hvitt og markert retning.",
		},
		{
			image: "https://images.pexels.com/photos/29827126/pexels-photo-29827126.jpeg",
			imageAlt: "En person på en rulletrapp med tydelige geometriske skygger på veggen",
			imagePosition: "65% center",
			imageWidth: 4800,
			imageHeight: 3200,
			source: "https://www.pexels.com/photo/man-on-escalator-with-geometric-shadows-29827126/",
			credit: "JUNLIN ZOU / Pexels",
			note: "Nytt forslag fra referansene dine. En tydelig person, skarpe skygger og diagonal fremdrift, med mindre bevegelsesuskarphet.",
		},
		{
			image: "https://images.unsplash.com/photo-1557939480-ab458d01435e?auto=format&fit=max&q=90",
			imageAlt: "En person i dress går med veske gjennom lys og skygge foran en glassfasade, i svart-hvitt",
			imagePosition: "center",
			imageWidth: 5852,
			imageHeight: 8192,
			source: "https://unsplash.com/photos/grayscale-photography-of-man-carrying-bag-sZnZCf1QVJ0",
			credit: "OSPAN ALI / Unsplash",
			note: "Nytt forslag med en skarpere hovedperson og tydelig retning. Svart-hvitt, glass og store lysflater gir et mer grafisk uttrykk.",
		},
		{
			image: "https://images.pexels.com/photos/3760089/pexels-photo-3760089.jpeg",
			imageAlt: "En person forklarer med hendene under en samtale, sett gjennom glass med lysreflekser",
			imagePosition: "32% center",
			imageWidth: 7680,
			imageHeight: 5120,
			source: "https://www.pexels.com/photo/male-employer-gesticulating-and-explaining-idea-in-light-office-3760089/",
			credit: "Andrea Piacquadio / Pexels",
			note: "En person forklarer et oppdrag gjennom glass. Gesten og lysrefleksene gir AI- og agentarbeidet en tydelig retning mot neste steg.",
		},
		{
			image: "https://images.unsplash.com/photo-1511376979163-f804dff7ad7b?auto=format&fit=max&q=90",
			imageAlt: "Kollegaer sitter i en samtale ved et arbeidsbord, sett gjennom glass med varme refleksjoner",
			imagePosition: "center",
			imageWidth: 3565,
			imageHeight: 5347,
			source: "https://unsplash.com/photos/person-sitting-in-a-chair-in-front-of-a-man-rRWiVQzLm7k",
			credit: "charlesdeluvio / Unsplash",
			note: "Nytt forslag fra Unsplash. En samtale om arbeidet, med glass og tydelig dybde. Mer menneskelig enn transitmotivene, men mindre konkret enn en overlevering.",
		},
		{
			image: "https://images.pexels.com/photos/8872681/pexels-photo-8872681.jpeg",
			imageAlt: "En person forklarer dokumenter ved et langt arbeidsbord mens kollegaer følger med",
			imagePosition: "45% center",
			imageWidth: 5734,
			imageHeight: 3823,
			source: "https://www.pexels.com/nb-no/bilde/person-mennesker-kontor-menn-8872681/",
			credit: "Pexels / referansen din",
			note: "Fra den nye listen din. En person forklarer en konkret oppgave til andre. Papirer, mottakere og gesten gir delegeringen mer innhold.",
		},
		{
			image: "https://images.pexels.com/photos/5673467/pexels-photo-5673467.jpeg",
			imageAlt: "En dokumentmappe blir overlevert mellom kollegaer i et møte, sett gjennom glass",
			imagePosition: "50% center",
			imageWidth: 6000,
			imageHeight: 4000,
			source: "https://www.pexels.com/photo/diverse-businesspeople-discussing-project-and-documents-in-office-5673467/",
			credit: "Sora Shimazaki / Pexels",
			note: "Nytt forslag gjennom glass. En faktisk overlevering gjør neste steg tydelig. Motivet har naturlig mykhet og refleksjoner, ikke bare skarpe flater.",
		},
		{
			image: "https://images.pexels.com/photos/7964225/pexels-photo-7964225.jpeg",
			imageAlt: "To kollegaer går gjennom et dokument mens den ene gir det videre til den andre",
			imagePosition: "center",
			imageWidth: 6000,
			imageHeight: 4000,
			source: "https://www.pexels.com/photo/male-employee-handing-out-papers-on-his-colleague-7964225/",
			credit: "Felicity Tai / Pexels",
			note: "Uten glass. To tydelige personer og et dokument som gis videre. Samtalen og håndbevegelsen viser et konkret neste steg.",
		},
		{
			image: "https://images.pexels.com/photos/9052598/pexels-photo-9052598.jpeg",
			imageAlt: "En kollega rekker et dokument over arbeidsbordet til personen i forgrunnen",
			imagePosition: "100% center",
			imageWidth: 4761,
			imageHeight: 3473,
			source: "https://www.pexels.com/photo/a-man-handing-a-document-to-another-person-9052598/",
			credit: "SHVETS production / Pexels",
			note: "Uten glass. Selve overleveringen er hovedmotivet. En uskarp person i forgrunnen gir dybde, mens avsenderen og dokumentet er tydelige.",
		},
	],
	workspace: [
		{
			image: "https://images.unsplash.com/photo-1588534331431-95ee61de0302?auto=format&fit=max&q=90",
			imageAlt: "En person arbeider ved en dataskjerm, sett gjennom glass og grønne refleksjoner i varmt dagslys",
			imagePosition: "center",
			imageWidth: 3456,
			imageHeight: 5184,
			source: "https://unsplash.com/photos/woman-in-black-and-white-plaid-long-sleeve-shirt-sitting-on-chair-bIs-7gNi9s0",
			credit: "Nathana Rebouças / Unsplash",
			note: "Én person i konsentrert arbeid. Varmt dagslys, glass og planter gir dybde.",
		},
		{
			image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=max&q=90",
			imageAlt: "En person ved en bærbar datamaskin, sett gjennom glass i et svart-hvitt kontorfotografi",
			imagePosition: "center",
			imageWidth: 5418,
			imageHeight: 3612,
			source: "https://unsplash.com/photos/man-using-macbook-Lks7vei-eAg",
			credit: "charlesdeluvio / Unsplash",
			note: "Et roligere svart-hvitt alternativ med glass, tydelig arbeidsflate og mindre farge i rekken.",
		},
		{
			image: "https://images.unsplash.com/photo-1632835256917-9932799fee58?auto=format&fit=max&q=90",
			imageAlt: "En person med briller arbeider ved en bærbar datamaskin, med kollegaer og refleksjoner i bakgrunnen",
			imagePosition: "center",
			imageWidth: 6720,
			imageHeight: 4480,
			source: "https://unsplash.com/photos/a-man-sitting-in-front-of-a-laptop-computer-ZYt2ewyDh_4",
			credit: "Redmind Studio / Unsplash",
			note: "Kjøligere kontorlys og flere lag gjennom glasset. En konsentrert person gir motivet et tydelig fokus.",
		},
		{
			image: "/verevon-mood/problem-research/active/collaboration-laptops.jpg",
			imageAlt: "To personer samarbeider ved et bord med bærbare datamaskiner, mens en peker på skjermen",
			imagePosition: "center",
			imageWidth: 3407,
			imageHeight: 5111,
			source: "https://unsplash.com/photos/two-people-sitting-at-a-table-with-laptops-nNMBa7Y1Ymk",
			credit: "Priscilla Du Preez / Unsplash",
			note: "Tettere på selve arbeidsflaten: hender, datamaskiner og et felles fokus. Et mer samarbeidsorientert alternativ.",
		},
	],
	support: [
		{
			image: "https://images.pexels.com/photos/5453841/pexels-photo-5453841.jpeg",
			imageAlt: "Et supportteam arbeider bak lyse dataskjermer i et åpent kontor",
			imagePosition: "50% 72%",
			imageWidth: 2544,
			imageHeight: 3816,
			source: "https://www.pexels.com/photo/people-working-in-the-office-5453841/",
			credit: "Tima Miroshnichenko / Pexels",
			note: "Menneskene sees bak skjermene. Kjølige gråtoner og en tydelig teknisk arbeidssituasjon.",
		},
		{
			image: "https://images.unsplash.com/photo-1688380692117-63178554d76d?auto=format&fit=max&q=90",
			imageAlt: "Flere personer undersøker noe sammen ved en bærbar datamaskin og noterer på papir",
			imagePosition: "center",
			imageWidth: 6240,
			imageHeight: 4160,
			source: "https://unsplash.com/photos/a-group-of-people-sitting-around-a-laptop-computer-MnPWB-ybjHQ",
			credit: "Fatemeh Rezvani / Unsplash",
			note: "Tettere på samarbeidet: hender, notater og en felles skjerm. Mørkere og mer intimt.",
		},
		{
			image: "/verevon-mood/modules/support-team-user.png",
			imageAlt: "Tre kollegaer undersøker noe sammen bak en dataskjerm, mens en peker på skjermen",
			imagePosition: "center",
			imageWidth: 1024,
			imageHeight: 1536,
			source: "/verevon-mood/modules/support-team-user.png",
			credit: "Lokalt bilde fra deg",
			note: "Bildet du sendte: tre kollegaer undersøker noe sammen. Skjermen i forgrunnen rammer inn samarbeidet i et lyst kontormiljø.",
		},
		{
			image: "https://images.pexels.com/photos/3932229/pexels-photo-3932229.jpeg",
			imageAlt: "Tre kollegaer undersøker noe på en bærbar datamaskin ved et lyst kontorvindu",
			imagePosition: "center",
			imageWidth: 5760,
			imageHeight: 3840,
			source: "https://www.pexels.com/photo/focused-business-team-with-laptop-discussing-project-3932229/",
			credit: "Andrea Piacquadio / Pexels",
			note: "Fra den nye listen din. Et konsentrert team bak en felles skjerm, med vinduslys og rolige gråtoner.",
		},
		{
			image: "https://images.pexels.com/photos/7988201/pexels-photo-7988201.jpeg",
			imageAlt: "Fire kollegaer samler seg rundt en bærbar datamaskin ved et trebord i et lyst kontor",
			imagePosition: "center",
			imageWidth: 3619,
			imageHeight: 5422,
			source: "https://www.pexels.com/photo/man-in-white-shirt-using-silver-laptop-7988201/",
			credit: "Mikhail Nilov / Pexels",
			note: "Fra den nye listen din. Lysere og mer sosialt, med en tydelig felles oppgave og datamaskinen i forgrunnen.",
		},
	],
	control: [
		{
			image: "https://images.pexels.com/photos/3760089/pexels-photo-3760089.jpeg",
			imageAlt: "En person forklarer med hendene i et lyst kontor, sett gjennom glass med lysreflekser",
			imagePosition: "32% center",
			imageWidth: 7680,
			imageHeight: 5120,
			source: "https://www.pexels.com/photo/male-employer-gesticulating-and-explaining-idea-in-light-office-3760089/",
			credit: "Andrea Piacquadio / Pexels",
			note: "En avklart samtale, sett gjennom glass og en varm lysstripe. Refleksjonene gir motivet ro og dybde.",
		},
		{
			image: "https://images.unsplash.com/photo-1576250623225-2bd8b9493770?auto=format&fit=max&q=90",
			imageAlt: "En person teller opp punkter på fingrene under en samtale ved et kontorvindu",
			imagePosition: "center",
			imageWidth: 6000,
			imageHeight: 4000,
			source: "https://unsplash.com/photos/man-talking-and-touching-his-index-finger-indoors-M752yvn8oU4",
			credit: "Cody Board / Unsplash",
			note: "Et varmere og mer direkte alternativ: en person gjør vurderinger og neste steg tydelige.",
		},
	],
} as const satisfies Record<string, readonly [ModulePhoto, ModulePhoto, ...ModulePhoto[]]>;

export const modulePhotoOrder = ["knowledge", "agents", "workspace", "support", "control"] as const;
