package modalities

const idemPrefix = "fbc1d94e94d756ede12c527b3d59e2204f58a623e6bd5a3d679eb03d93f22637"

// catalog is the in-memory seed list of multimodal AI surfaces documented
// by the capability-core modalities registry. Every entry is scoped to the
// "triodelab" organization and carries a deterministic idempotency key.
var catalog = Catalog{
	Modalities: []Modality{
		{
			ID:             "modality.chat",
			IdempotencyKey: idemPrefix + ":modality.chat",
			OrgID:          "triodelab",
			Kind:           KindChat,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "inference-core",
			Inputs:         []string{"messages", "tools"},
			Outputs:        []string{"assistantMessage", "toolCalls"},
			Streaming:      true,
			PrimaryRoute:   "provider.openai.chat",
			Fallbacks:      []string{"provider.anthropic.chat", "provider.azure.chat"},
			Description:    "Conversational chat with tool-calling and token streaming.",
		},
		{
			ID:             "modality.completions",
			IdempotencyKey: idemPrefix + ":modality.completions",
			OrgID:          "triodelab",
			Kind:           KindCompletions,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "inference-core",
			Inputs:         []string{"prompt"},
			Outputs:        []string{"text"},
			Streaming:      true,
			PrimaryRoute:   "provider.openai.completions",
			Fallbacks:      []string{"provider.azure.completions"},
			Description:    "Single-turn text completion for legacy prompt workflows.",
		},
		{
			ID:             "modality.images",
			IdempotencyKey: idemPrefix + ":modality.images",
			OrgID:          "triodelab",
			Kind:           KindImages,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "inference-core",
			Inputs:         []string{"prompt", "referenceImage"},
			Outputs:        []string{"imageArtifact"},
			Streaming:      false,
			PrimaryRoute:   "provider.openai.images",
			Fallbacks:      []string{"provider.stability.images"},
			ArtifactStore:  "artifact.store.images",
			Description:    "Text-to-image and image-to-image synthesis; results offloaded to artifact store.",
		},
		{
			ID:             "modality.speech",
			IdempotencyKey: idemPrefix + ":modality.speech",
			OrgID:          "triodelab",
			Kind:           KindSpeech,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "inference-core",
			Inputs:         []string{"audio", "text"},
			Outputs:        []string{"transcript", "audioArtifact"},
			Streaming:      true,
			PrimaryRoute:   "provider.openai.speech",
			Fallbacks:      []string{"provider.azure.speech", "provider.deepgram.speech"},
			ArtifactStore:  "artifact.store.audio",
			Description:    "Speech-to-text and text-to-speech, including streaming transcription.",
		},
		{
			ID:             "modality.translation",
			IdempotencyKey: idemPrefix + ":modality.translation",
			OrgID:          "triodelab",
			Kind:           KindTranslation,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "inference-core",
			Inputs:         []string{"text", "sourceLang", "targetLang"},
			Outputs:        []string{"translatedText"},
			Streaming:      false,
			PrimaryRoute:   "provider.deepl.translate",
			Fallbacks:      []string{"provider.azure.translate", "provider.openai.chat"},
			Description:    "Text translation across language pairs with provider fallback.",
		},
		{
			ID:             "modality.documents",
			IdempotencyKey: idemPrefix + ":modality.documents",
			OrgID:          "triodelab",
			Kind:           KindDocuments,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "execution-core",
			Inputs:         []string{"documentRef"},
			Outputs:        []string{"parsedDocument", "extractedFields"},
			Streaming:      false,
			PrimaryRoute:   "provider.azure.documentintelligence",
			Fallbacks:      []string{"provider.openai.chat"},
			ArtifactStore:  "artifact.store.documents",
			Description:    "Document parsing, OCR, and structured field extraction.",
		},
		{
			ID:             "modality.video",
			IdempotencyKey: idemPrefix + ":modality.video",
			OrgID:          "triodelab",
			Kind:           KindVideo,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "execution-core",
			Inputs:         []string{"prompt", "referenceVideo"},
			Outputs:        []string{"videoArtifact"},
			Streaming:      false,
			PrimaryRoute:   "provider.fal.video",
			Fallbacks:      []string{"provider.runway.video"},
			ArtifactStore:  "artifact.store.video",
			Description:    "Text-to-video and video-to-video synthesis; long-running with artifact offload.",
		},
		{
			ID:             "modality.realtime",
			IdempotencyKey: idemPrefix + ":modality.realtime",
			OrgID:          "triodelab",
			Kind:           KindRealtime,
			PublicOwner:    "model-gateway",
			RuntimeOwner:   "inference-core",
			Inputs:         []string{"audioStream", "messages"},
			Outputs:        []string{"audioStream", "assistantMessage"},
			Streaming:      true,
			PrimaryRoute:   "provider.openai.realtime",
			Fallbacks:      []string{"provider.azure.realtime"},
			Description:    "Bidirectional realtime audio and message streaming for voice agents.",
		},
	},
}
