// Package mock provides a carrier.Adapter implementation returning
// realistic canned quotes instead of calling a real carrier API. This
// exists so the quote comparison table, and later the agent, can be built
// and demoed before any real carrier contract is in place (see
// docs/TASKS.md Fase 1) and so quoteengine's timeout/partial-result
// behavior can be tested deterministically via InjectedLatency/Err.
package mock

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"shipping-core/internal/carrier"
	"shipping-core/internal/docgen"
)

// Adapter is a configurable mock carrier.Adapter. Zero value is usable;
// InjectedLatency and InjectedErr let tests exercise quoteengine's
// timeout and error-handling paths deterministically.
type Adapter struct {
	info            carrier.Info
	basePriceCents  int64
	pricePerKgCents int64
	transitDays     int
	features        []string

	// InjectedLatency, if set, is slept before Quote returns — used to
	// simulate a slow carrier in fan-out tests.
	InjectedLatency time.Duration
	// InjectedErr, if set, is returned by Quote instead of a result —
	// used to simulate an upstream failure.
	InjectedErr error
}

func (a *Adapter) Info() carrier.Info { return a.info }

// Quote returns a single priced option scaled by package weight, or no
// options at all if the request's segment doesn't match this carrier's
// (e.g. a B2C-only mock given a business recipient).
func (a *Adapter) Quote(ctx context.Context, req carrier.QuoteRequest) ([]carrier.Quote, error) {
	if a.info.Segment != carrier.SegmentBoth && req.Segment != a.info.Segment {
		return nil, nil
	}

	if a.InjectedLatency > 0 {
		select {
		case <-time.After(a.InjectedLatency):
		case <-ctx.Done():
			return nil, ctx.Err()
		}
	}
	if a.InjectedErr != nil {
		return nil, a.InjectedErr
	}

	weight := req.Package.WeightKg
	if weight <= 0 {
		weight = 1
	}
	priceCents := a.basePriceCents + int64(weight*float64(a.pricePerKgCents))

	return []carrier.Quote{{
		CarrierCode:       a.info.Code,
		CarrierName:       a.info.Name,
		ServiceName:       fmt.Sprintf("%s Standard", a.info.Name),
		Price:             carrier.Money{AmountCents: priceCents, Currency: "NOK"},
		EstimatedDelivery: time.Now().AddDate(0, 0, a.transitDays),
		TransitDays:       a.transitDays,
		Features:          a.features,
		ReliabilityScore:  nil, // unknown until the reliability module exists
	}}, nil
}

// demoTransitScale compresses one "transit day" into 90 seconds of wall
// clock so a demo booking visibly progresses through its tracking states
// while someone is actually looking at the screen.
const demoTransitScale = 90 * time.Second

// Book accepts every confirmed request and returns deterministic demo
// references. The Unix booking time is encoded into the refs so Track can
// derive a realistic status progression later without any adapter state.
func (a *Adapter) Book(_ context.Context, req carrier.BookingRequest) (carrier.Booking, error) {
	if req.From.Country != req.To.Country && req.Customs == nil {
		return carrier.Booking{}, fmt.Errorf("mock adapter %s: cross-border booking requires a customs declaration", a.info.Code)
	}
	now := time.Now().UTC()
	return carrier.Booking{
		CarrierCode: a.info.Code,
		BookingRef:  fmt.Sprintf("%s-%d", a.info.Code, now.Unix()),
		TrackingNo:  fmt.Sprintf("VD%d%04d", now.Unix(), len(req.To.PostalCode)*731%9973),
		Price:       req.Price,
		CreatedAt:   now,
	}, nil
}

// Label renders a genuinely valid PDF demo label (clearly watermarked —
// real labels only ever come from carrier APIs).
func (a *Adapter) Label(_ context.Context, bookingRef string) (carrier.Label, error) {
	pdf := docgen.PDF(docgen.PageLabel, []docgen.Line{
		docgen.H1(a.info.Name),
		docgen.Txt("DEMO LABEL - NOT VALID FOR SHIPPING"),
		docgen.Txt(""),
		docgen.H2("Booking: " + bookingRef),
		docgen.Txt("Carrier code: " + a.info.Code),
		docgen.Txt("Segment: " + string(a.info.Segment)),
		docgen.Txt(""),
		docgen.Txt("Generated by Velion shipping-core (mock fleet)."),
	})
	return carrier.Label{ContentType: "application/pdf", Data: pdf}, nil
}

// ZPL returns the same demo label as ZPL, for thermal-printer flows.
func (a *Adapter) ZPL(bookingRef string) string {
	return fmt.Sprintf(
		"^XA\n^FO40,40^A0N,36,36^FD%s^FS\n^FO40,90^A0N,24,24^FDDEMO LABEL - NOT VALID^FS\n^FO40,130^A0N,24,24^FD%s^FS\n^FO40,180^BY2^BCN,80,Y,N,N^FD%s^FS\n^XZ\n",
		a.info.Name, bookingRef, bookingRef,
	)
}

// mockJourney is the simulated lifecycle every demo shipment follows, one
// stage per (scaled) transit interval.
var mockJourney = []struct {
	status      string
	description string
}{
	{"booked", "Shipment registered with carrier"},
	{"collected", "Parcel collected from sender"},
	{"in_transit", "In transit between terminals"},
	{"out_for_delivery", "Out for delivery"},
	{"delivered", "Delivered to recipient"},
}

// Track derives the shipment's progress from the Unix timestamp encoded in
// the tracking number at Book time: elapsed wall-clock time moves the demo
// shipment through the journey at demoTransitScale per stage.
func (a *Adapter) Track(_ context.Context, trackingNo string) (carrier.TrackingStatus, error) {
	bookedAt, err := parseMockTrackingTime(trackingNo)
	if err != nil {
		return carrier.TrackingStatus{}, fmt.Errorf("mock adapter %s: %w", a.info.Code, err)
	}

	elapsed := time.Since(bookedAt)
	stage := int(elapsed / demoTransitScale)
	if stage >= len(mockJourney) {
		stage = len(mockJourney) - 1
	}

	events := make([]carrier.TrackingEvent, 0, stage+1)
	for i := 0; i <= stage; i++ {
		events = append(events, carrier.TrackingEvent{
			Status:      mockJourney[i].status,
			Description: mockJourney[i].description,
			OccurredAt:  bookedAt.Add(time.Duration(i) * demoTransitScale),
		})
	}

	status := carrier.TrackingStatus{
		TrackingNo:    trackingNo,
		CurrentStatus: mockJourney[stage].status,
		Events:        events,
	}
	eta := bookedAt.Add(time.Duration(len(mockJourney)-1) * demoTransitScale)
	if status.CurrentStatus == "delivered" {
		status.ActualDelivery = &events[len(events)-1].OccurredAt
	} else {
		status.EstimatedDelivery = &eta
	}
	return status, nil
}

// SchedulePickup confirms any requested pickup window with a deterministic
// demo confirmation number.
func (a *Adapter) SchedulePickup(_ context.Context, req carrier.PickupRequest) (carrier.Pickup, error) {
	if req.Date.IsZero() {
		return carrier.Pickup{}, fmt.Errorf("mock adapter %s: pickup date is required", a.info.Code)
	}
	return carrier.Pickup{
		CarrierCode: a.info.Code,
		PickupRef:   fmt.Sprintf("PU-%s-%s", a.info.Code, req.Date.Format("20060102")),
		Date:        req.Date,
		TimeFrom:    req.TimeFrom,
		TimeTo:      req.TimeTo,
		ConfirmedAt: time.Now().UTC(),
	}, nil
}

// CancelBooking accepts every cancellation (demo fleet has no cutoff rules).
func (a *Adapter) CancelBooking(_ context.Context, _ string) error { return nil }

// parseMockTrackingTime extracts the Unix timestamp Book embedded in a
// "VD<unix><4 digits>" tracking number.
func parseMockTrackingTime(trackingNo string) (time.Time, error) {
	if len(trackingNo) < 7 || trackingNo[:2] != "VD" {
		return time.Time{}, fmt.Errorf("unrecognized demo tracking number %q", trackingNo)
	}
	digits := trackingNo[2 : len(trackingNo)-4]
	unix, err := strconv.ParseInt(digits, 10, 64)
	if err != nil {
		return time.Time{}, fmt.Errorf("unrecognized demo tracking number %q", trackingNo)
	}
	return time.Unix(unix, 0).UTC(), nil
}

// DefaultCarriers returns one mock Adapter per carrier named in
// docs/CARRIERS.md, spanning B2B and B2C, with plausible relative pricing
// and transit times (faster/home-delivery services cost more; freight
// aggregator services are cheaper but slower).
func DefaultCarriers() []carrier.Adapter {
	return []carrier.Adapter{
		&Adapter{
			info:            carrier.Info{Code: "mock-bring", Name: "Bring", Segment: carrier.SegmentBoth},
			basePriceCents:  8900,
			pricePerKgCents: 1200,
			transitDays:     2,
			features:        []string{"tracking", "pickup_point"},
		},
		&Adapter{
			info:            carrier.Info{Code: "mock-postnord", Name: "PostNord", Segment: carrier.SegmentBoth},
			basePriceCents:  8200,
			pricePerKgCents: 1100,
			transitDays:     3,
			features:        []string{"tracking", "pickup_point"},
		},
		&Adapter{
			info:            carrier.Info{Code: "mock-dhl", Name: "DHL Express", Segment: carrier.SegmentB2B},
			basePriceCents:  16500,
			pricePerKgCents: 2100,
			transitDays:     1,
			features:        []string{"tracking", "express", "international"},
		},
		&Adapter{
			info:            carrier.Info{Code: "mock-dsv", Name: "DSV", Segment: carrier.SegmentB2B},
			basePriceCents:  7500,
			pricePerKgCents: 900,
			transitDays:     4,
			features:        []string{"tracking", "pallet_freight"},
		},
		&Adapter{
			info:            carrier.Info{Code: "mock-helthjem", Name: "Helthjem", Segment: carrier.SegmentB2C},
			basePriceCents:  6900,
			pricePerKgCents: 800,
			transitDays:     2,
			features:        []string{"tracking", "home_delivery"},
		},
		&Adapter{
			info:            carrier.Info{Code: "mock-porterbuddy", Name: "Porterbuddy", Segment: carrier.SegmentB2C},
			basePriceCents:  12900,
			pricePerKgCents: 500,
			transitDays:     0,
			features:        []string{"tracking", "home_delivery", "same_day", "time_window"},
		},
	}
}
