// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/proto/database/v1/database.proto

package databasev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseService_CheckPostgreSQL_FullMethodName        = "/coresystem.gateway.database.v1.DatabaseService/CheckPostgreSQL"
	DatabaseService_CheckRedis_FullMethodName             = "/coresystem.gateway.database.v1.DatabaseService/CheckRedis"
	DatabaseService_GetPostgreSQLStats_FullMethodName     = "/coresystem.gateway.database.v1.DatabaseService/GetPostgreSQLStats"
	DatabaseService_GetRedisStats_FullMethodName          = "/coresystem.gateway.database.v1.DatabaseService/GetRedisStats"
	DatabaseService_GetConnectionPoolStats_FullMethodName = "/coresystem.gateway.database.v1.DatabaseService/GetConnectionPoolStats"
)

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DatabaseService provides database health and management for internal microservices
type DatabaseServiceClient interface {
	// CheckPostgreSQL performs PostgreSQL health check
	CheckPostgreSQL(ctx context.Context, in *CheckPostgreSQLRequest, opts ...grpc.CallOption) (*CheckPostgreSQLResponse, error)
	// CheckRedis performs Redis health check
	CheckRedis(ctx context.Context, in *CheckRedisRequest, opts ...grpc.CallOption) (*CheckRedisResponse, error)
	// GetPostgreSQLStats returns detailed PostgreSQL statistics
	GetPostgreSQLStats(ctx context.Context, in *GetPostgreSQLStatsRequest, opts ...grpc.CallOption) (*GetPostgreSQLStatsResponse, error)
	// GetRedisStats returns detailed Redis statistics
	GetRedisStats(ctx context.Context, in *GetRedisStatsRequest, opts ...grpc.CallOption) (*GetRedisStatsResponse, error)
	// GetConnectionPoolStats returns connection pool information
	GetConnectionPoolStats(ctx context.Context, in *GetConnectionPoolStatsRequest, opts ...grpc.CallOption) (*GetConnectionPoolStatsResponse, error)
}

type databaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseServiceClient(cc grpc.ClientConnInterface) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) CheckPostgreSQL(ctx context.Context, in *CheckPostgreSQLRequest, opts ...grpc.CallOption) (*CheckPostgreSQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPostgreSQLResponse)
	err := c.cc.Invoke(ctx, DatabaseService_CheckPostgreSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) CheckRedis(ctx context.Context, in *CheckRedisRequest, opts ...grpc.CallOption) (*CheckRedisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRedisResponse)
	err := c.cc.Invoke(ctx, DatabaseService_CheckRedis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetPostgreSQLStats(ctx context.Context, in *GetPostgreSQLStatsRequest, opts ...grpc.CallOption) (*GetPostgreSQLStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostgreSQLStatsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetPostgreSQLStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetRedisStats(ctx context.Context, in *GetRedisStatsRequest, opts ...grpc.CallOption) (*GetRedisStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedisStatsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetRedisStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetConnectionPoolStats(ctx context.Context, in *GetConnectionPoolStatsRequest, opts ...grpc.CallOption) (*GetConnectionPoolStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionPoolStatsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetConnectionPoolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
// All implementations must embed UnimplementedDatabaseServiceServer
// for forward compatibility.
//
// DatabaseService provides database health and management for internal microservices
type DatabaseServiceServer interface {
	// CheckPostgreSQL performs PostgreSQL health check
	CheckPostgreSQL(context.Context, *CheckPostgreSQLRequest) (*CheckPostgreSQLResponse, error)
	// CheckRedis performs Redis health check
	CheckRedis(context.Context, *CheckRedisRequest) (*CheckRedisResponse, error)
	// GetPostgreSQLStats returns detailed PostgreSQL statistics
	GetPostgreSQLStats(context.Context, *GetPostgreSQLStatsRequest) (*GetPostgreSQLStatsResponse, error)
	// GetRedisStats returns detailed Redis statistics
	GetRedisStats(context.Context, *GetRedisStatsRequest) (*GetRedisStatsResponse, error)
	// GetConnectionPoolStats returns connection pool information
	GetConnectionPoolStats(context.Context, *GetConnectionPoolStatsRequest) (*GetConnectionPoolStatsResponse, error)
	mustEmbedUnimplementedDatabaseServiceServer()
}

// UnimplementedDatabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseServiceServer struct{}

func (UnimplementedDatabaseServiceServer) CheckPostgreSQL(context.Context, *CheckPostgreSQLRequest) (*CheckPostgreSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPostgreSQL not implemented")
}
func (UnimplementedDatabaseServiceServer) CheckRedis(context.Context, *CheckRedisRequest) (*CheckRedisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRedis not implemented")
}
func (UnimplementedDatabaseServiceServer) GetPostgreSQLStats(context.Context, *GetPostgreSQLStatsRequest) (*GetPostgreSQLStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostgreSQLStats not implemented")
}
func (UnimplementedDatabaseServiceServer) GetRedisStats(context.Context, *GetRedisStatsRequest) (*GetRedisStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedisStats not implemented")
}
func (UnimplementedDatabaseServiceServer) GetConnectionPoolStats(context.Context, *GetConnectionPoolStatsRequest) (*GetConnectionPoolStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectionPoolStats not implemented")
}
func (UnimplementedDatabaseServiceServer) mustEmbedUnimplementedDatabaseServiceServer() {}
func (UnimplementedDatabaseServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseServiceServer will
// result in compilation errors.
type UnsafeDatabaseServiceServer interface {
	mustEmbedUnimplementedDatabaseServiceServer()
}

func RegisterDatabaseServiceServer(s grpc.ServiceRegistrar, srv DatabaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseService_ServiceDesc, srv)
}

func _DatabaseService_CheckPostgreSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPostgreSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CheckPostgreSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_CheckPostgreSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CheckPostgreSQL(ctx, req.(*CheckPostgreSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_CheckRedis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRedisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CheckRedis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_CheckRedis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CheckRedis(ctx, req.(*CheckRedisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetPostgreSQLStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostgreSQLStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetPostgreSQLStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetPostgreSQLStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetPostgreSQLStats(ctx, req.(*GetPostgreSQLStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetRedisStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedisStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetRedisStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetRedisStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetRedisStats(ctx, req.(*GetRedisStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetConnectionPoolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionPoolStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetConnectionPoolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetConnectionPoolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetConnectionPoolStats(ctx, req.(*GetConnectionPoolStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseService_ServiceDesc is the grpc.ServiceDesc for DatabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coresystem.gateway.database.v1.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPostgreSQL",
			Handler:    _DatabaseService_CheckPostgreSQL_Handler,
		},
		{
			MethodName: "CheckRedis",
			Handler:    _DatabaseService_CheckRedis_Handler,
		},
		{
			MethodName: "GetPostgreSQLStats",
			Handler:    _DatabaseService_GetPostgreSQLStats_Handler,
		},
		{
			MethodName: "GetRedisStats",
			Handler:    _DatabaseService_GetRedisStats_Handler,
		},
		{
			MethodName: "GetConnectionPoolStats",
			Handler:    _DatabaseService_GetConnectionPoolStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/database/v1/database.proto",
}
