// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/database/v1/database.proto

package databasev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DatabaseStatus enum for database health state
type DatabaseStatus int32

const (
	DatabaseStatus_DATABASE_STATUS_UNSPECIFIED DatabaseStatus = 0
	DatabaseStatus_DATABASE_STATUS_HEALTHY     DatabaseStatus = 1
	DatabaseStatus_DATABASE_STATUS_DEGRADED    DatabaseStatus = 2
	DatabaseStatus_DATABASE_STATUS_UNHEALTHY   DatabaseStatus = 3
	DatabaseStatus_DATABASE_STATUS_UNAVAILABLE DatabaseStatus = 4
)

// Enum value maps for DatabaseStatus.
var (
	DatabaseStatus_name = map[int32]string{
		0: "DATABASE_STATUS_UNSPECIFIED",
		1: "DATABASE_STATUS_HEALTHY",
		2: "DATABASE_STATUS_DEGRADED",
		3: "DATABASE_STATUS_UNHEALTHY",
		4: "DATABASE_STATUS_UNAVAILABLE",
	}
	DatabaseStatus_value = map[string]int32{
		"DATABASE_STATUS_UNSPECIFIED": 0,
		"DATABASE_STATUS_HEALTHY":     1,
		"DATABASE_STATUS_DEGRADED":    2,
		"DATABASE_STATUS_UNHEALTHY":   3,
		"DATABASE_STATUS_UNAVAILABLE": 4,
	}
)

func (x DatabaseStatus) Enum() *DatabaseStatus {
	p := new(DatabaseStatus)
	*p = x
	return p
}

func (x DatabaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_database_v1_database_proto_enumTypes[0].Descriptor()
}

func (DatabaseStatus) Type() protoreflect.EnumType {
	return &file_api_proto_database_v1_database_proto_enumTypes[0]
}

func (x DatabaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseStatus.Descriptor instead.
func (DatabaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{0}
}

// CheckPostgreSQLRequest for PostgreSQL health check
type CheckPostgreSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"` // Optional: specific database to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPostgreSQLRequest) Reset() {
	*x = CheckPostgreSQLRequest{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostgreSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostgreSQLRequest) ProtoMessage() {}

func (x *CheckPostgreSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostgreSQLRequest.ProtoReflect.Descriptor instead.
func (*CheckPostgreSQLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPostgreSQLRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

// CheckPostgreSQLResponse contains PostgreSQL health status
type CheckPostgreSQLResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            DatabaseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=coresystem.gateway.database.v1.DatabaseStatus" json:"status,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	MaxConnections    int32                  `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	DatabaseSizeBytes int64                  `protobuf:"varint,5,opt,name=database_size_bytes,json=databaseSizeBytes,proto3" json:"database_size_bytes,omitempty"`
	ResponseTimeMs    int64                  `protobuf:"varint,6,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	CheckedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Error             string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckPostgreSQLResponse) Reset() {
	*x = CheckPostgreSQLResponse{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPostgreSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPostgreSQLResponse) ProtoMessage() {}

func (x *CheckPostgreSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPostgreSQLResponse.ProtoReflect.Descriptor instead.
func (*CheckPostgreSQLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPostgreSQLResponse) GetStatus() DatabaseStatus {
	if x != nil {
		return x.Status
	}
	return DatabaseStatus_DATABASE_STATUS_UNSPECIFIED
}

func (x *CheckPostgreSQLResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckPostgreSQLResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *CheckPostgreSQLResponse) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *CheckPostgreSQLResponse) GetDatabaseSizeBytes() int64 {
	if x != nil {
		return x.DatabaseSizeBytes
	}
	return 0
}

func (x *CheckPostgreSQLResponse) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *CheckPostgreSQLResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *CheckPostgreSQLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CheckRedisRequest for Redis health check
type CheckRedisRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectionName string                 `protobuf:"bytes,1,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"` // Optional: specific connection to check
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckRedisRequest) Reset() {
	*x = CheckRedisRequest{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRedisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRedisRequest) ProtoMessage() {}

func (x *CheckRedisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRedisRequest.ProtoReflect.Descriptor instead.
func (*CheckRedisRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRedisRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

// CheckRedisResponse contains Redis health status
type CheckRedisResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           DatabaseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=coresystem.gateway.database.v1.DatabaseStatus" json:"status,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ConnectedClients int32                  `protobuf:"varint,3,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	UsedMemoryBytes  int64                  `protobuf:"varint,4,opt,name=used_memory_bytes,json=usedMemoryBytes,proto3" json:"used_memory_bytes,omitempty"`
	MaxMemoryBytes   int64                  `protobuf:"varint,5,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	ResponseTimeMs   int64                  `protobuf:"varint,6,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	CheckedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Error            string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckRedisResponse) Reset() {
	*x = CheckRedisResponse{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRedisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRedisResponse) ProtoMessage() {}

func (x *CheckRedisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRedisResponse.ProtoReflect.Descriptor instead.
func (*CheckRedisResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{3}
}

func (x *CheckRedisResponse) GetStatus() DatabaseStatus {
	if x != nil {
		return x.Status
	}
	return DatabaseStatus_DATABASE_STATUS_UNSPECIFIED
}

func (x *CheckRedisResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckRedisResponse) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *CheckRedisResponse) GetUsedMemoryBytes() int64 {
	if x != nil {
		return x.UsedMemoryBytes
	}
	return 0
}

func (x *CheckRedisResponse) GetMaxMemoryBytes() int64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *CheckRedisResponse) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *CheckRedisResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *CheckRedisResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetPostgreSQLStatsRequest for detailed stats
type GetPostgreSQLStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostgreSQLStatsRequest) Reset() {
	*x = GetPostgreSQLStatsRequest{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostgreSQLStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostgreSQLStatsRequest) ProtoMessage() {}

func (x *GetPostgreSQLStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostgreSQLStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPostgreSQLStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{4}
}

func (x *GetPostgreSQLStatsRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

// GetPostgreSQLStatsResponse contains detailed PostgreSQL statistics
type GetPostgreSQLStatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Version                string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	TotalConnections       int32                  `protobuf:"varint,2,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	ActiveConnections      int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	IdleConnections        int32                  `protobuf:"varint,4,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	MaxConnections         int32                  `protobuf:"varint,5,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	DatabaseSizeBytes      int64                  `protobuf:"varint,6,opt,name=database_size_bytes,json=databaseSizeBytes,proto3" json:"database_size_bytes,omitempty"`
	TableCount             int64                  `protobuf:"varint,7,opt,name=table_count,json=tableCount,proto3" json:"table_count,omitempty"`
	IndexCount             int64                  `protobuf:"varint,8,opt,name=index_count,json=indexCount,proto3" json:"index_count,omitempty"`
	CacheHitRatio          int64                  `protobuf:"varint,9,opt,name=cache_hit_ratio,json=cacheHitRatio,proto3" json:"cache_hit_ratio,omitempty"` // Percentage
	TransactionsCommitted  int64                  `protobuf:"varint,10,opt,name=transactions_committed,json=transactionsCommitted,proto3" json:"transactions_committed,omitempty"`
	TransactionsRolledBack int64                  `protobuf:"varint,11,opt,name=transactions_rolled_back,json=transactionsRolledBack,proto3" json:"transactions_rolled_back,omitempty"`
	UptimeSince            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	TableStats             []*TableStats          `protobuf:"bytes,13,rep,name=table_stats,json=tableStats,proto3" json:"table_stats,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetPostgreSQLStatsResponse) Reset() {
	*x = GetPostgreSQLStatsResponse{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostgreSQLStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostgreSQLStatsResponse) ProtoMessage() {}

func (x *GetPostgreSQLStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostgreSQLStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPostgreSQLStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostgreSQLStatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetPostgreSQLStatsResponse) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetIdleConnections() int32 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetDatabaseSizeBytes() int64 {
	if x != nil {
		return x.DatabaseSizeBytes
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetTableCount() int64 {
	if x != nil {
		return x.TableCount
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetIndexCount() int64 {
	if x != nil {
		return x.IndexCount
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetCacheHitRatio() int64 {
	if x != nil {
		return x.CacheHitRatio
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetTransactionsCommitted() int64 {
	if x != nil {
		return x.TransactionsCommitted
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetTransactionsRolledBack() int64 {
	if x != nil {
		return x.TransactionsRolledBack
	}
	return 0
}

func (x *GetPostgreSQLStatsResponse) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

func (x *GetPostgreSQLStatsResponse) GetTableStats() []*TableStats {
	if x != nil {
		return x.TableStats
	}
	return nil
}

// GetRedisStatsRequest for detailed stats
type GetRedisStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectionName string                 `protobuf:"bytes,1,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRedisStatsRequest) Reset() {
	*x = GetRedisStatsRequest{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedisStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisStatsRequest) ProtoMessage() {}

func (x *GetRedisStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisStatsRequest.ProtoReflect.Descriptor instead.
func (*GetRedisStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{6}
}

func (x *GetRedisStatsRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

// GetRedisStatsResponse contains detailed Redis statistics
type GetRedisStatsResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Version                  string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Mode                     string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // standalone, cluster, sentinel
	ConnectedClients         int32                  `protobuf:"varint,3,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	BlockedClients           int32                  `protobuf:"varint,4,opt,name=blocked_clients,json=blockedClients,proto3" json:"blocked_clients,omitempty"`
	UsedMemoryBytes          int64                  `protobuf:"varint,5,opt,name=used_memory_bytes,json=usedMemoryBytes,proto3" json:"used_memory_bytes,omitempty"`
	UsedMemoryPeakBytes      int64                  `protobuf:"varint,6,opt,name=used_memory_peak_bytes,json=usedMemoryPeakBytes,proto3" json:"used_memory_peak_bytes,omitempty"`
	MaxMemoryBytes           int64                  `protobuf:"varint,7,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	MemoryFragmentationRatio float64                `protobuf:"fixed64,8,opt,name=memory_fragmentation_ratio,json=memoryFragmentationRatio,proto3" json:"memory_fragmentation_ratio,omitempty"`
	TotalKeys                int64                  `protobuf:"varint,9,opt,name=total_keys,json=totalKeys,proto3" json:"total_keys,omitempty"`
	ExpiredKeys              int64                  `protobuf:"varint,10,opt,name=expired_keys,json=expiredKeys,proto3" json:"expired_keys,omitempty"`
	EvictedKeys              int64                  `protobuf:"varint,11,opt,name=evicted_keys,json=evictedKeys,proto3" json:"evicted_keys,omitempty"`
	KeyspaceHits             int64                  `protobuf:"varint,12,opt,name=keyspace_hits,json=keyspaceHits,proto3" json:"keyspace_hits,omitempty"`
	KeyspaceMisses           int64                  `protobuf:"varint,13,opt,name=keyspace_misses,json=keyspaceMisses,proto3" json:"keyspace_misses,omitempty"`
	HitRate                  float64                `protobuf:"fixed64,14,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"` // Percentage
	UptimeSince              *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetRedisStatsResponse) Reset() {
	*x = GetRedisStatsResponse{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedisStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisStatsResponse) ProtoMessage() {}

func (x *GetRedisStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisStatsResponse.ProtoReflect.Descriptor instead.
func (*GetRedisStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{7}
}

func (x *GetRedisStatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetRedisStatsResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetRedisStatsResponse) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *GetRedisStatsResponse) GetBlockedClients() int32 {
	if x != nil {
		return x.BlockedClients
	}
	return 0
}

func (x *GetRedisStatsResponse) GetUsedMemoryBytes() int64 {
	if x != nil {
		return x.UsedMemoryBytes
	}
	return 0
}

func (x *GetRedisStatsResponse) GetUsedMemoryPeakBytes() int64 {
	if x != nil {
		return x.UsedMemoryPeakBytes
	}
	return 0
}

func (x *GetRedisStatsResponse) GetMaxMemoryBytes() int64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *GetRedisStatsResponse) GetMemoryFragmentationRatio() float64 {
	if x != nil {
		return x.MemoryFragmentationRatio
	}
	return 0
}

func (x *GetRedisStatsResponse) GetTotalKeys() int64 {
	if x != nil {
		return x.TotalKeys
	}
	return 0
}

func (x *GetRedisStatsResponse) GetExpiredKeys() int64 {
	if x != nil {
		return x.ExpiredKeys
	}
	return 0
}

func (x *GetRedisStatsResponse) GetEvictedKeys() int64 {
	if x != nil {
		return x.EvictedKeys
	}
	return 0
}

func (x *GetRedisStatsResponse) GetKeyspaceHits() int64 {
	if x != nil {
		return x.KeyspaceHits
	}
	return 0
}

func (x *GetRedisStatsResponse) GetKeyspaceMisses() int64 {
	if x != nil {
		return x.KeyspaceMisses
	}
	return 0
}

func (x *GetRedisStatsResponse) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *GetRedisStatsResponse) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

// GetConnectionPoolStatsRequest for pool information
type GetConnectionPoolStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolName      string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"` // "postgresql" or "redis"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionPoolStatsRequest) Reset() {
	*x = GetConnectionPoolStatsRequest{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionPoolStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionPoolStatsRequest) ProtoMessage() {}

func (x *GetConnectionPoolStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionPoolStatsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionPoolStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{8}
}

func (x *GetConnectionPoolStatsRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

// GetConnectionPoolStatsResponse contains pool statistics
type GetConnectionPoolStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PoolName          string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	TotalConnections  int32                  `protobuf:"varint,2,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	IdleConnections   int32                  `protobuf:"varint,3,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	MaxConnections    int32                  `protobuf:"varint,5,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	WaitCount         int32                  `protobuf:"varint,6,opt,name=wait_count,json=waitCount,proto3" json:"wait_count,omitempty"`
	WaitDurationMs    int64                  `protobuf:"varint,7,opt,name=wait_duration_ms,json=waitDurationMs,proto3" json:"wait_duration_ms,omitempty"`
	MaxIdleClosed     int64                  `protobuf:"varint,8,opt,name=max_idle_closed,json=maxIdleClosed,proto3" json:"max_idle_closed,omitempty"`
	MaxLifetimeClosed int64                  `protobuf:"varint,9,opt,name=max_lifetime_closed,json=maxLifetimeClosed,proto3" json:"max_lifetime_closed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetConnectionPoolStatsResponse) Reset() {
	*x = GetConnectionPoolStatsResponse{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionPoolStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionPoolStatsResponse) ProtoMessage() {}

func (x *GetConnectionPoolStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionPoolStatsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionPoolStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{9}
}

func (x *GetConnectionPoolStatsResponse) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *GetConnectionPoolStatsResponse) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *GetConnectionPoolStatsResponse) GetIdleConnections() int32 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *GetConnectionPoolStatsResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GetConnectionPoolStatsResponse) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *GetConnectionPoolStatsResponse) GetWaitCount() int32 {
	if x != nil {
		return x.WaitCount
	}
	return 0
}

func (x *GetConnectionPoolStatsResponse) GetWaitDurationMs() int64 {
	if x != nil {
		return x.WaitDurationMs
	}
	return 0
}

func (x *GetConnectionPoolStatsResponse) GetMaxIdleClosed() int64 {
	if x != nil {
		return x.MaxIdleClosed
	}
	return 0
}

func (x *GetConnectionPoolStatsResponse) GetMaxLifetimeClosed() int64 {
	if x != nil {
		return x.MaxLifetimeClosed
	}
	return 0
}

// TableStats represents PostgreSQL table statistics
type TableStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TableName      string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	RowCount       int64                  `protobuf:"varint,2,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	TableSizeBytes int64                  `protobuf:"varint,3,opt,name=table_size_bytes,json=tableSizeBytes,proto3" json:"table_size_bytes,omitempty"`
	IndexSizeBytes int64                  `protobuf:"varint,4,opt,name=index_size_bytes,json=indexSizeBytes,proto3" json:"index_size_bytes,omitempty"`
	TotalSizeBytes int64                  `protobuf:"varint,5,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TableStats) Reset() {
	*x = TableStats{}
	mi := &file_api_proto_database_v1_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableStats) ProtoMessage() {}

func (x *TableStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_database_v1_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableStats.ProtoReflect.Descriptor instead.
func (*TableStats) Descriptor() ([]byte, []int) {
	return file_api_proto_database_v1_database_proto_rawDescGZIP(), []int{10}
}

func (x *TableStats) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableStats) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *TableStats) GetTableSizeBytes() int64 {
	if x != nil {
		return x.TableSizeBytes
	}
	return 0
}

func (x *TableStats) GetIndexSizeBytes() int64 {
	if x != nil {
		return x.IndexSizeBytes
	}
	return 0
}

func (x *TableStats) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

var File_api_proto_database_v1_database_proto protoreflect.FileDescriptor

const file_api_proto_database_v1_database_proto_rawDesc = "" +
	"\n" +
	"$api/proto/database/v1/database.proto\x12\x1bcoresystem.gateway.database.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\x16CheckPostgreSQLRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\"\xfb\x02\n" +
	"\x17CheckPostgreSQLResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.coresystem.gateway.database.v1.DatabaseStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12'\n" +
	"\x0fmax_connections\x18\x04 \x01(\x05R\x0emaxConnections\x12.\n" +
	"\x13database_size_bytes\x18\x05 \x01(\x03R\x11databaseSizeBytes\x12(\n" +
	"\x10response_time_ms\x18\x06 \x01(\x03R\x0eresponseTimeMs\x129\n" +
	"\n" +
	"checked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"<\n" +
	"\x11CheckRedisRequest\x12'\n" +
	"\x0fconnection_name\x18\x01 \x01(\tR\x0econnectionName\"\xf1\x02\n" +
	"\x12CheckRedisResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.coresystem.gateway.database.v1.DatabaseStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12+\n" +
	"\x11connected_clients\x18\x03 \x01(\x05R\x10connectedClients\x12*\n" +
	"\x11used_memory_bytes\x18\x04 \x01(\x03R\x0fusedMemoryBytes\x12(\n" +
	"\x10max_memory_bytes\x18\x05 \x01(\x03R\x0emaxMemoryBytes\x12(\n" +
	"\x10response_time_ms\x18\x06 \x01(\x03R\x0eresponseTimeMs\x129\n" +
	"\n" +
	"checked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"@\n" +
	"\x19GetPostgreSQLStatsRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\"\xfa\x04\n" +
	"\x1aGetPostgreSQLStatsResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12+\n" +
	"\x11total_connections\x18\x02 \x01(\x05R\x10totalConnections\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x10idle_connections\x18\x04 \x01(\x05R\x0fidleConnections\x12'\n" +
	"\x0fmax_connections\x18\x05 \x01(\x05R\x0emaxConnections\x12.\n" +
	"\x13database_size_bytes\x18\x06 \x01(\x03R\x11databaseSizeBytes\x12\x1f\n" +
	"\vtable_count\x18\a \x01(\x03R\n" +
	"tableCount\x12\x1f\n" +
	"\vindex_count\x18\b \x01(\x03R\n" +
	"indexCount\x12&\n" +
	"\x0fcache_hit_ratio\x18\t \x01(\x03R\rcacheHitRatio\x125\n" +
	"\x16transactions_committed\x18\n" +
	" \x01(\x03R\x15transactionsCommitted\x128\n" +
	"\x18transactions_rolled_back\x18\v \x01(\x03R\x16transactionsRolledBack\x12=\n" +
	"\fuptime_since\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\x12H\n" +
	"\vtable_stats\x18\r \x03(\v2'.coresystem.gateway.database.v1.TableStatsR\n" +
	"tableStats\"?\n" +
	"\x14GetRedisStatsRequest\x12'\n" +
	"\x0fconnection_name\x18\x01 \x01(\tR\x0econnectionName\"\xf1\x04\n" +
	"\x15GetRedisStatsResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12+\n" +
	"\x11connected_clients\x18\x03 \x01(\x05R\x10connectedClients\x12'\n" +
	"\x0fblocked_clients\x18\x04 \x01(\x05R\x0eblockedClients\x12*\n" +
	"\x11used_memory_bytes\x18\x05 \x01(\x03R\x0fusedMemoryBytes\x123\n" +
	"\x16used_memory_peak_bytes\x18\x06 \x01(\x03R\x13usedMemoryPeakBytes\x12(\n" +
	"\x10max_memory_bytes\x18\a \x01(\x03R\x0emaxMemoryBytes\x12<\n" +
	"\x1amemory_fragmentation_ratio\x18\b \x01(\x01R\x18memoryFragmentationRatio\x12\x1d\n" +
	"\n" +
	"total_keys\x18\t \x01(\x03R\ttotalKeys\x12!\n" +
	"\fexpired_keys\x18\n" +
	" \x01(\x03R\vexpiredKeys\x12!\n" +
	"\fevicted_keys\x18\v \x01(\x03R\vevictedKeys\x12#\n" +
	"\rkeyspace_hits\x18\f \x01(\x03R\fkeyspaceHits\x12'\n" +
	"\x0fkeyspace_misses\x18\r \x01(\x03R\x0ekeyspaceMisses\x12\x19\n" +
	"\bhit_rate\x18\x0e \x01(\x01R\ahitRate\x12=\n" +
	"\fuptime_since\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\"<\n" +
	"\x1dGetConnectionPoolStatsRequest\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\"\x8e\x03\n" +
	"\x1eGetConnectionPoolStatsResponse\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12+\n" +
	"\x11total_connections\x18\x02 \x01(\x05R\x10totalConnections\x12)\n" +
	"\x10idle_connections\x18\x03 \x01(\x05R\x0fidleConnections\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x12'\n" +
	"\x0fmax_connections\x18\x05 \x01(\x05R\x0emaxConnections\x12\x1d\n" +
	"\n" +
	"wait_count\x18\x06 \x01(\x05R\twaitCount\x12(\n" +
	"\x10wait_duration_ms\x18\a \x01(\x03R\x0ewaitDurationMs\x12&\n" +
	"\x0fmax_idle_closed\x18\b \x01(\x03R\rmaxIdleClosed\x12.\n" +
	"\x13max_lifetime_closed\x18\t \x01(\x03R\x11maxLifetimeClosed\"\xc6\x01\n" +
	"\n" +
	"TableStats\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1b\n" +
	"\trow_count\x18\x02 \x01(\x03R\browCount\x12(\n" +
	"\x10table_size_bytes\x18\x03 \x01(\x03R\x0etableSizeBytes\x12(\n" +
	"\x10index_size_bytes\x18\x04 \x01(\x03R\x0eindexSizeBytes\x12(\n" +
	"\x10total_size_bytes\x18\x05 \x01(\x03R\x0etotalSizeBytes*\xac\x01\n" +
	"\x0eDatabaseStatus\x12\x1f\n" +
	"\x1bDATABASE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DATABASE_STATUS_HEALTHY\x10\x01\x12\x1c\n" +
	"\x18DATABASE_STATUS_DEGRADED\x10\x02\x12\x1d\n" +
	"\x19DATABASE_STATUS_UNHEALTHY\x10\x03\x12\x1f\n" +
	"\x1bDATABASE_STATUS_UNAVAILABLE\x10\x042\x92\x05\n" +
	"\x0fDatabaseService\x12|\n" +
	"\x0fCheckPostgreSQL\x123.coresystem.gateway.database.v1.CheckPostgreSQLRequest\x1a4.coresystem.gateway.database.v1.CheckPostgreSQLResponse\x12m\n" +
	"\n" +
	"CheckRedis\x12..coresystem.gateway.database.v1.CheckRedisRequest\x1a/.coresystem.gateway.database.v1.CheckRedisResponse\x12\x85\x01\n" +
	"\x12GetPostgreSQLStats\x126.coresystem.gateway.database.v1.GetPostgreSQLStatsRequest\x1a7.coresystem.gateway.database.v1.GetPostgreSQLStatsResponse\x12v\n" +
	"\rGetRedisStats\x121.coresystem.gateway.database.v1.GetRedisStatsRequest\x1a2.coresystem.gateway.database.v1.GetRedisStatsResponse\x12\x91\x01\n" +
	"\x16GetConnectionPoolStats\x12:.coresystem.gateway.database.v1.GetConnectionPoolStatsRequest\x1a;.coresystem.gateway.database.v1.GetConnectionPoolStatsResponseBIZGgithub.com/coresystem/integration-gateway/api/proto/database/v1;databasev1b\x06proto3"

var (
	file_api_proto_database_v1_database_proto_rawDescOnce sync.Once
	file_api_proto_database_v1_database_proto_rawDescData []byte
)

func file_api_proto_database_v1_database_proto_rawDescGZIP() []byte {
	file_api_proto_database_v1_database_proto_rawDescOnce.Do(func() {
		file_api_proto_database_v1_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_database_v1_database_proto_rawDesc), len(file_api_proto_database_v1_database_proto_rawDesc)))
	})
	return file_api_proto_database_v1_database_proto_rawDescData
}

var file_api_proto_database_v1_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_database_v1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_database_v1_database_proto_goTypes = []any{
	(DatabaseStatus)(0),                    // 0: coresystem.gateway.database.v1.DatabaseStatus
	(*CheckPostgreSQLRequest)(nil),         // 1: coresystem.gateway.database.v1.CheckPostgreSQLRequest
	(*CheckPostgreSQLResponse)(nil),        // 2: coresystem.gateway.database.v1.CheckPostgreSQLResponse
	(*CheckRedisRequest)(nil),              // 3: coresystem.gateway.database.v1.CheckRedisRequest
	(*CheckRedisResponse)(nil),             // 4: coresystem.gateway.database.v1.CheckRedisResponse
	(*GetPostgreSQLStatsRequest)(nil),      // 5: coresystem.gateway.database.v1.GetPostgreSQLStatsRequest
	(*GetPostgreSQLStatsResponse)(nil),     // 6: coresystem.gateway.database.v1.GetPostgreSQLStatsResponse
	(*GetRedisStatsRequest)(nil),           // 7: coresystem.gateway.database.v1.GetRedisStatsRequest
	(*GetRedisStatsResponse)(nil),          // 8: coresystem.gateway.database.v1.GetRedisStatsResponse
	(*GetConnectionPoolStatsRequest)(nil),  // 9: coresystem.gateway.database.v1.GetConnectionPoolStatsRequest
	(*GetConnectionPoolStatsResponse)(nil), // 10: coresystem.gateway.database.v1.GetConnectionPoolStatsResponse
	(*TableStats)(nil),                     // 11: coresystem.gateway.database.v1.TableStats
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
}
var file_api_proto_database_v1_database_proto_depIdxs = []int32{
	0,  // 0: coresystem.gateway.database.v1.CheckPostgreSQLResponse.status:type_name -> coresystem.gateway.database.v1.DatabaseStatus
	12, // 1: coresystem.gateway.database.v1.CheckPostgreSQLResponse.checked_at:type_name -> google.protobuf.Timestamp
	0,  // 2: coresystem.gateway.database.v1.CheckRedisResponse.status:type_name -> coresystem.gateway.database.v1.DatabaseStatus
	12, // 3: coresystem.gateway.database.v1.CheckRedisResponse.checked_at:type_name -> google.protobuf.Timestamp
	12, // 4: coresystem.gateway.database.v1.GetPostgreSQLStatsResponse.uptime_since:type_name -> google.protobuf.Timestamp
	11, // 5: coresystem.gateway.database.v1.GetPostgreSQLStatsResponse.table_stats:type_name -> coresystem.gateway.database.v1.TableStats
	12, // 6: coresystem.gateway.database.v1.GetRedisStatsResponse.uptime_since:type_name -> google.protobuf.Timestamp
	1,  // 7: coresystem.gateway.database.v1.DatabaseService.CheckPostgreSQL:input_type -> coresystem.gateway.database.v1.CheckPostgreSQLRequest
	3,  // 8: coresystem.gateway.database.v1.DatabaseService.CheckRedis:input_type -> coresystem.gateway.database.v1.CheckRedisRequest
	5,  // 9: coresystem.gateway.database.v1.DatabaseService.GetPostgreSQLStats:input_type -> coresystem.gateway.database.v1.GetPostgreSQLStatsRequest
	7,  // 10: coresystem.gateway.database.v1.DatabaseService.GetRedisStats:input_type -> coresystem.gateway.database.v1.GetRedisStatsRequest
	9,  // 11: coresystem.gateway.database.v1.DatabaseService.GetConnectionPoolStats:input_type -> coresystem.gateway.database.v1.GetConnectionPoolStatsRequest
	2,  // 12: coresystem.gateway.database.v1.DatabaseService.CheckPostgreSQL:output_type -> coresystem.gateway.database.v1.CheckPostgreSQLResponse
	4,  // 13: coresystem.gateway.database.v1.DatabaseService.CheckRedis:output_type -> coresystem.gateway.database.v1.CheckRedisResponse
	6,  // 14: coresystem.gateway.database.v1.DatabaseService.GetPostgreSQLStats:output_type -> coresystem.gateway.database.v1.GetPostgreSQLStatsResponse
	8,  // 15: coresystem.gateway.database.v1.DatabaseService.GetRedisStats:output_type -> coresystem.gateway.database.v1.GetRedisStatsResponse
	10, // 16: coresystem.gateway.database.v1.DatabaseService.GetConnectionPoolStats:output_type -> coresystem.gateway.database.v1.GetConnectionPoolStatsResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_database_v1_database_proto_init() }
func file_api_proto_database_v1_database_proto_init() {
	if File_api_proto_database_v1_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_database_v1_database_proto_rawDesc), len(file_api_proto_database_v1_database_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_database_v1_database_proto_goTypes,
		DependencyIndexes: file_api_proto_database_v1_database_proto_depIdxs,
		EnumInfos:         file_api_proto_database_v1_database_proto_enumTypes,
		MessageInfos:      file_api_proto_database_v1_database_proto_msgTypes,
	}.Build()
	File_api_proto_database_v1_database_proto = out.File
	file_api_proto_database_v1_database_proto_goTypes = nil
	file_api_proto_database_v1_database_proto_depIdxs = nil
}
