"""
Data Plane shared authentication middleware.

Validates Bearer tokens against auth-core's TokenValidationService via gRPC.
Caches validated sessions in Redis to avoid round-tripping on every request.

Usage in FastAPI:
    from shared.auth_middleware import require_auth, AuthContext
    app.middleware("http")(require_auth)
"""
from __future__ import annotations

import hashlib
import json
import logging
import time
from dataclasses import dataclass, asdict
from typing import Optional

import grpc
from fastapi import Request, Response
from starlette.middleware.base import RequestResponseEndpoint
from starlette.responses import JSONResponse

logger = logging.getLogger(__name__)

# ── Auth context injected into request.state ───────────────────────────────────

@dataclass(frozen=True, slots=True)
class AuthContext:
    user_id: str
    org_id: str
    email: str
    name: str
    role: str          # global role: "admin" | "user"
    session_id: str
    permissions: tuple[str, ...]

    def has_permission(self, perm: str) -> bool:
        return perm in self.permissions

    def is_admin(self) -> bool:
        return self.role == "admin"


# ── Paths excluded from auth ──────────────────────────────────────────────────

_PUBLIC_PREFIXES = ("/health", "/readyz", "/metrics", "/docs", "/openapi.json", "/internal/")


def _is_public(path: str) -> bool:
    return any(path.startswith(prefix) for prefix in _PUBLIC_PREFIXES)


# ── gRPC stub (lazy singleton) ────────────────────────────────────────────────

_grpc_channel: Optional[grpc.aio.Channel] = None
_grpc_stub: Optional[object] = None


async def _get_stub(auth_grpc_url: str, internal_api_key: str):
    """Lazy-init async gRPC channel + stub for TokenValidationService."""
    global _grpc_channel, _grpc_stub
    if _grpc_stub is not None:
        return _grpc_stub

    # Import generated proto modules at runtime (generated by grpc_runtime)
    from shared.grpc_runtime import load_auth_proto_modules
    auth_pb2, auth_pb2_grpc = load_auth_proto_modules()

    _grpc_channel = grpc.aio.insecure_channel(auth_grpc_url)
    _grpc_stub = auth_pb2_grpc.TokenValidationServiceStub(_grpc_channel)
    return _grpc_stub


async def close_auth_channel() -> None:
    """Call on shutdown to clean up the gRPC channel."""
    global _grpc_channel, _grpc_stub
    if _grpc_channel:
        await _grpc_channel.close()
        _grpc_channel = None
        _grpc_stub = None


# ── Redis cache helpers ────────────────────────────────────────────────────────

def _cache_key(token: str) -> str:
    """SHA-256 hash of token so we never store raw tokens in Redis."""
    return f"auth:token:{hashlib.sha256(token.encode()).hexdigest()}"


async def _get_cached(redis_client, token: str) -> Optional[AuthContext]:
    try:
        raw = await redis_client.get(_cache_key(token))
        if raw is None:
            return None
        data = json.loads(raw)
        return AuthContext(
            user_id=data["user_id"],
            org_id=data["org_id"],
            email=data["email"],
            name=data["name"],
            role=data["role"],
            session_id=data["session_id"],
            permissions=tuple(data["permissions"]),
        )
    except Exception as exc:
        logger.debug("auth cache read failed (non-fatal): %s", exc)
        return None


async def _set_cached(redis_client, token: str, ctx: AuthContext, ttl: int = 60) -> None:
    try:
        payload = {
            "user_id": ctx.user_id,
            "org_id": ctx.org_id,
            "email": ctx.email,
            "name": ctx.name,
            "role": ctx.role,
            "session_id": ctx.session_id,
            "permissions": list(ctx.permissions),
        }
        await redis_client.set(_cache_key(token), json.dumps(payload), ex=ttl)
    except Exception as exc:
        logger.debug("auth cache write failed (non-fatal): %s", exc)


# ── Redis cache invalidation (pub/sub) ─────────────────────────────────────────

async def invalidate_user_cache(redis_client, user_id: str) -> None:
    """Publish cache invalidation for a specific user (called by NATS event handlers)."""
    try:
        await redis_client.publish(
            "dataplane:cache:invalidate",
            json.dumps({"type": "user", "user_id": user_id}),
        )
    except Exception as exc:
        logger.debug("cache invalidation publish failed (non-fatal): %s", exc)


async def invalidate_org_cache(redis_client, org_id: str) -> None:
    """Publish cache invalidation for an org (membership changes)."""
    try:
        await redis_client.publish(
            "dataplane:cache:invalidate",
            json.dumps({"type": "org", "org_id": org_id}),
        )
    except Exception as exc:
        logger.debug("cache invalidation publish failed (non-fatal): %s", exc)


# ── Middleware factory ─────────────────────────────────────────────────────────


def create_auth_middleware(
    auth_grpc_url: str,
    internal_api_key: str,
    redis_getter,
    cache_ttl: int = 60,
):
    """
    Returns a FastAPI middleware function that validates Bearer tokens.

    Args:
        auth_grpc_url:  e.g. "auth-core:50011"
        internal_api_key:  INTERNAL_API_KEY env var value
        redis_getter:  async callable returning a Redis client
        cache_ttl:  seconds to cache validation results (default 60)
    """
    if not internal_api_key:
        raise RuntimeError(
            "INTERNAL_API_KEY is required for auth middleware. "
            "Refusing to start without service-to-service authentication."
        )

    async def auth_middleware(request: Request, call_next: RequestResponseEndpoint) -> Response:
        # Skip auth for public endpoints
        if _is_public(request.url.path):
            return await call_next(request)

        # Extract Bearer token
        auth_header = request.headers.get("authorization", "")
        if not auth_header.startswith("Bearer "):
            return JSONResponse(
                status_code=401,
                content={"detail": "Missing or invalid Authorization header"},
            )
        token = auth_header[7:]  # strip "Bearer "
        if not token:
            return JSONResponse(
                status_code=401,
                content={"detail": "Empty Bearer token"},
            )

        # Check Redis cache first
        redis_client = None
        try:
            redis_client = await redis_getter()
        except Exception:
            pass  # Redis unavailable — fall through to gRPC call

        if redis_client:
            cached = await _get_cached(redis_client, token)
            if cached is not None:
                request.state.auth = cached
                return await call_next(request)

        # Call auth-core gRPC ValidateToken
        try:
            stub = await _get_stub(auth_grpc_url, internal_api_key)
            from shared.grpc_runtime import load_auth_proto_modules
            auth_pb2, _ = load_auth_proto_modules()

            metadata = [("x-service-auth", internal_api_key)]
            resp = await stub.ValidateToken(
                auth_pb2.ValidateTokenRequest(token=token),
                metadata=metadata,
                timeout=5.0,
            )
        except grpc.aio.AioRpcError as exc:
            logger.error("auth-core gRPC unreachable: %s", exc)
            return JSONResponse(
                status_code=503,
                content={"detail": "Authentication service unavailable"},
            )
        except Exception as exc:
            logger.error("auth validation error: %s", exc)
            return JSONResponse(
                status_code=503,
                content={"detail": "Authentication service error"},
            )

        if not resp.valid:
            return JSONResponse(
                status_code=401,
                content={"detail": "Invalid or expired token"},
            )

        ctx = AuthContext(
            user_id=resp.user_id,
            org_id=resp.org_id,
            email=resp.email,
            name=resp.name,
            role=resp.role,
            session_id=resp.session_id,
            permissions=tuple(resp.permissions),
        )

        # Cache successful validation
        if redis_client:
            await _set_cached(redis_client, token, ctx, ttl=cache_ttl)

        request.state.auth = ctx
        return await call_next(request)

    return auth_middleware


def get_auth_context(request: Request) -> AuthContext:
    """Extract AuthContext from request. Raises 401 if not present."""
    ctx = getattr(request.state, "auth", None)
    if ctx is None:
        from fastapi import HTTPException
        raise HTTPException(status_code=401, detail="Not authenticated")
    return ctx
