package commands

// catalog is the in-memory seed list of built-in slash commands. All entries
// are scoped to the "triodelab" organization and classified as system commands.
var catalog = Catalog{
	Commands: []Command{
		{
			ID:          "cmd.system.compact",
			OrgID:       "triodelab",
			Name:        "/compact",
			Description: "Compact conversation context",
			Category:    CategorySystem,
			Handler:     "builtin.compact",
			Enabled:     true,
			Scope:       "session",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.resume",
			OrgID:       "triodelab",
			Name:        "/resume",
			Description: "Resume previous session",
			Category:    CategorySystem,
			Handler:     "builtin.resume",
			Enabled:     true,
			Scope:       "session",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.memory",
			OrgID:       "triodelab",
			Name:        "/memory",
			Description: "Manage agent memory",
			Category:    CategorySystem,
			Handler:     "builtin.memory",
			Enabled:     true,
			Scope:       "agent",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.tasks",
			OrgID:       "triodelab",
			Name:        "/tasks",
			Description: "List and manage tasks",
			Category:    CategorySystem,
			Handler:     "builtin.tasks",
			Enabled:     true,
			Scope:       "org",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.cron",
			OrgID:       "triodelab",
			Name:        "/cron",
			Description: "Manage scheduled jobs",
			Category:    CategorySystem,
			Handler:     "builtin.cron",
			Enabled:     true,
			Scope:       "org",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.skills",
			OrgID:       "triodelab",
			Name:        "/skills",
			Description: "List available skills",
			Category:    CategorySystem,
			Handler:     "builtin.skills",
			Enabled:     true,
			Scope:       "org",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.models",
			OrgID:       "triodelab",
			Name:        "/models",
			Description: "List available models",
			Category:    CategorySystem,
			Handler:     "builtin.models",
			Enabled:     true,
			Scope:       "org",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.budget",
			OrgID:       "triodelab",
			Name:        "/budget",
			Description: "Show usage and budget",
			Category:    CategorySystem,
			Handler:     "builtin.budget",
			Enabled:     true,
			Scope:       "org",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
		{
			ID:          "cmd.system.help",
			OrgID:       "triodelab",
			Name:        "/help",
			Description: "Show available commands",
			Category:    CategorySystem,
			Handler:     "builtin.help",
			Enabled:     true,
			Scope:       "global",
			CreatedAt:   "2025-01-01T00:00:00Z",
			UpdatedAt:   "2025-01-01T00:00:00Z",
		},
	},
}
