/* tslint:disable */
/* eslint-disable */
/**
 * Model Plane API
 * Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/_* endpoints require a Bearer JWT issued by auth-core. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AiChatRequest,
    AiChatRequestFromJSON,
    AiChatRequestToJSON,
} from '../models/AiChatRequest';
import {
    type AiChatResponse,
    AiChatResponseFromJSON,
    AiChatResponseToJSON,
} from '../models/AiChatResponse';
import {
    type AiDocumentsRequest,
    AiDocumentsRequestFromJSON,
    AiDocumentsRequestToJSON,
} from '../models/AiDocumentsRequest';
import {
    type AiImagesRequest,
    AiImagesRequestFromJSON,
    AiImagesRequestToJSON,
} from '../models/AiImagesRequest';
import {
    type AiRealtimeRequest,
    AiRealtimeRequestFromJSON,
    AiRealtimeRequestToJSON,
} from '../models/AiRealtimeRequest';
import {
    type AiSpeechRequest,
    AiSpeechRequestFromJSON,
    AiSpeechRequestToJSON,
} from '../models/AiSpeechRequest';
import {
    type AiTranslateRequest,
    AiTranslateRequestFromJSON,
    AiTranslateRequestToJSON,
} from '../models/AiTranslateRequest';
import {
    type QueuedResponse,
    QueuedResponseFromJSON,
    QueuedResponseToJSON,
} from '../models/QueuedResponse';

export interface AiChatOperationRequest {
    aiChatRequest: AiChatRequest;
}

export interface AiDocumentsOperationRequest {
    aiDocumentsRequest: AiDocumentsRequest;
}

export interface AiImagesOperationRequest {
    aiImagesRequest: AiImagesRequest;
}

export interface AiRealtimeOperationRequest {
    aiRealtimeRequest: AiRealtimeRequest;
}

export interface AiSpeechOperationRequest {
    aiSpeechRequest: AiSpeechRequest;
}

export interface AiTranslateOperationRequest {
    aiTranslateRequest: AiTranslateRequest;
}

/**
 * 
 */
export class AiApi extends runtime.BaseAPI {

    /**
     * Creates request options for aiChat without sending the request
     */
    async aiChatRequestOpts(requestParameters: AiChatOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiChatRequest'] == null) {
            throw new runtime.RequiredError(
                'aiChatRequest',
                'Required parameter "aiChatRequest" was null or undefined when calling aiChat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/chat`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiChatRequestToJSON(requestParameters['aiChatRequest']),
        };
    }

    /**
     * Chat completion via inference-core
     */
    async aiChatRaw(requestParameters: AiChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChatResponse>> {
        const requestOptions = await this.aiChatRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiChatResponseFromJSON(jsonValue));
    }

    /**
     * Chat completion via inference-core
     */
    async aiChat(requestParameters: AiChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChatResponse> {
        const response = await this.aiChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for aiDocuments without sending the request
     */
    async aiDocumentsRequestOpts(requestParameters: AiDocumentsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiDocumentsRequest'] == null) {
            throw new runtime.RequiredError(
                'aiDocumentsRequest',
                'Required parameter "aiDocumentsRequest" was null or undefined when calling aiDocuments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/documents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiDocumentsRequestToJSON(requestParameters['aiDocumentsRequest']),
        };
    }

    /**
     * Document processing (queued)
     */
    async aiDocumentsRaw(requestParameters: AiDocumentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueuedResponse>> {
        const requestOptions = await this.aiDocumentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueuedResponseFromJSON(jsonValue));
    }

    /**
     * Document processing (queued)
     */
    async aiDocuments(requestParameters: AiDocumentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueuedResponse> {
        const response = await this.aiDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for aiImages without sending the request
     */
    async aiImagesRequestOpts(requestParameters: AiImagesOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiImagesRequest'] == null) {
            throw new runtime.RequiredError(
                'aiImagesRequest',
                'Required parameter "aiImagesRequest" was null or undefined when calling aiImages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/images`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiImagesRequestToJSON(requestParameters['aiImagesRequest']),
        };
    }

    /**
     * Image generation (queued)
     */
    async aiImagesRaw(requestParameters: AiImagesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueuedResponse>> {
        const requestOptions = await this.aiImagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueuedResponseFromJSON(jsonValue));
    }

    /**
     * Image generation (queued)
     */
    async aiImages(requestParameters: AiImagesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueuedResponse> {
        const response = await this.aiImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for aiRealtime without sending the request
     */
    async aiRealtimeRequestOpts(requestParameters: AiRealtimeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiRealtimeRequest'] == null) {
            throw new runtime.RequiredError(
                'aiRealtimeRequest',
                'Required parameter "aiRealtimeRequest" was null or undefined when calling aiRealtime().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/realtime`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiRealtimeRequestToJSON(requestParameters['aiRealtimeRequest']),
        };
    }

    /**
     * Realtime sessions require WebSocket upgrade. Use /v1/invoke/stream for SSE streaming instead. 
     * Realtime session placeholder
     */
    async aiRealtimeRaw(requestParameters: AiRealtimeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueuedResponse>> {
        const requestOptions = await this.aiRealtimeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueuedResponseFromJSON(jsonValue));
    }

    /**
     * Realtime sessions require WebSocket upgrade. Use /v1/invoke/stream for SSE streaming instead. 
     * Realtime session placeholder
     */
    async aiRealtime(requestParameters: AiRealtimeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueuedResponse> {
        const response = await this.aiRealtimeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for aiSpeech without sending the request
     */
    async aiSpeechRequestOpts(requestParameters: AiSpeechOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiSpeechRequest'] == null) {
            throw new runtime.RequiredError(
                'aiSpeechRequest',
                'Required parameter "aiSpeechRequest" was null or undefined when calling aiSpeech().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/speech`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiSpeechRequestToJSON(requestParameters['aiSpeechRequest']),
        };
    }

    /**
     * Text-to-speech synthesis (queued)
     */
    async aiSpeechRaw(requestParameters: AiSpeechOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueuedResponse>> {
        const requestOptions = await this.aiSpeechRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueuedResponseFromJSON(jsonValue));
    }

    /**
     * Text-to-speech synthesis (queued)
     */
    async aiSpeech(requestParameters: AiSpeechOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueuedResponse> {
        const response = await this.aiSpeechRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for aiTranslate without sending the request
     */
    async aiTranslateRequestOpts(requestParameters: AiTranslateOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiTranslateRequest'] == null) {
            throw new runtime.RequiredError(
                'aiTranslateRequest',
                'Required parameter "aiTranslateRequest" was null or undefined when calling aiTranslate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ai/translate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiTranslateRequestToJSON(requestParameters['aiTranslateRequest']),
        };
    }

    /**
     * Text translation (queued)
     */
    async aiTranslateRaw(requestParameters: AiTranslateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueuedResponse>> {
        const requestOptions = await this.aiTranslateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueuedResponseFromJSON(jsonValue));
    }

    /**
     * Text translation (queued)
     */
    async aiTranslate(requestParameters: AiTranslateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueuedResponse> {
        const response = await this.aiTranslateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
