# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InvokeRequest(BaseModel):
    """
    InvokeRequest
    """ # noqa: E501
    content: Annotated[str, Field(strict=True, max_length=102400)] = Field(description="User message content (max 100 KB)")
    model: Optional[StrictStr] = Field(default=None, description="Model identifier. Falls back to DEFAULT_MODEL env.")
    session_key: Optional[StrictStr] = Field(default=None, description="Optional session key for context continuity.")
    thread_id: Optional[StrictStr] = Field(default=None, description="Optional thread ID for conversation threading.")
    structured_output_schema: Optional[StrictStr] = Field(default=None, description="JSON Schema string for structured output.")
    zdr: Optional[StrictBool] = Field(default=False, description="Zero data retention — if true, no data is persisted.")
    max_cost_usd: Optional[Union[Annotated[float, Field(strict=True, gt=0)], Annotated[int, Field(strict=True, gt=0)]]] = Field(default=None, description="Maximum cost in USD for this request.")
    max_tokens: Optional[Annotated[int, Field(strict=True, gt=0)]] = Field(default=None, description="Maximum output tokens.")
    __properties: ClassVar[List[str]] = ["content", "model", "session_key", "thread_id", "structured_output_schema", "zdr", "max_cost_usd", "max_tokens"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvokeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvokeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "content": obj.get("content"),
            "model": obj.get("model"),
            "session_key": obj.get("session_key"),
            "thread_id": obj.get("thread_id"),
            "structured_output_schema": obj.get("structured_output_schema"),
            "zdr": obj.get("zdr") if obj.get("zdr") is not None else False,
            "max_cost_usd": obj.get("max_cost_usd"),
            "max_tokens": obj.get("max_tokens")
        })
        return _obj


