# coding: utf-8

"""
    Model Plane API

    Public HTTP API for the Model Plane runtime, served by model-gateway on :8080. All /v1/* endpoints require a Bearer JWT issued by auth-core. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PlanState(str, Enum):
    """
    PlanState
    """

    """
    allowed enum values
    """
    UNSPECIFIED = 'UNSPECIFIED'
    DRAFT = 'DRAFT'
    PROPOSED = 'PROPOSED'
    APPROVED = 'APPROVED'
    EXECUTING = 'EXECUTING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    REJECTED = 'REJECTED'
    SUPERSEDED = 'SUPERSEDED'
    ARCHIVED = 'ARCHIVED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PlanState from a JSON string"""
        return cls(json.loads(json_str))


