package roadmap

// catalog is the canonical in-code implementation status for the Model Plane.
// IDs are unique within each section (enforced by TestCatalog_IDsUniqueWithinSection).
// Status values must be one of "yes", "partial", or "no".
var catalog = Catalog{
	ServiceChecklist: []Feature{
		{
			ID:          "model-gateway",
			Name:        "Model Gateway",
			Category:    "rust",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Routes inference requests to providers; streaming and failover in progress.",
		},
		{
			ID:          "session-core",
			Name:        "Session Core",
			Category:    "rust",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Session lifecycle and state persistence; multi-tenant isolation partial.",
		},
		{
			ID:          "inference-core",
			Name:        "Inference Core",
			Category:    "rust",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Model execution, streaming token output, OpenAI/Azure embeddings, and env-backed model catalogue; multimodal providers and batching pending.",
		},
		{
			ID:          "execution-core",
			Name:        "Execution Core",
			Category:    "rust",
			Status:      "no",
			Owner:       "model-plane/rust",
			Description: "Tool call execution runtime; not yet implemented.",
		},
		{
			ID:          "orchestrator-core",
			Name:        "Orchestrator Core",
			Category:    "go",
			Status:      "partial",
			Owner:       "model-plane/go",
			Description: "Plan/act loop coordination across capabilities; error recovery partial.",
		},
		{
			ID:          "capability-core",
			Name:        "Capability Core",
			Category:    "go",
			Status:      "partial",
			Owner:       "model-plane/go",
			Description: "Capability registry, policy, and status endpoint (this service).",
		},
		{
			ID:          "sandbox-manager",
			Name:        "Sandbox Manager",
			Category:    "go",
			Status:      "no",
			Owner:       "model-plane/go",
			Description: "Ephemeral sandbox provisioning for tool execution; not yet implemented.",
		},
		{
			ID:          "browser-broker",
			Name:        "Browser Broker",
			Category:    "go",
			Status:      "no",
			Owner:       "model-plane/go",
			Description: "Headless browser session broker for web-grounded agents; not yet implemented.",
		},
		{
			ID:          "letta-bridge",
			Name:        "Letta Bridge",
			Category:    "go",
			Status:      "no",
			Owner:       "model-plane/go",
			Description: "Bridge to Letta memory service; not yet implemented.",
		},
	},
	BackendRuntime: []Feature{
		{
			ID:          "otel-tracing",
			Name:        "OpenTelemetry Tracing",
			Status:      "yes",
			Description: "Distributed traces emitted across Go services via otel/metric v1.43.0.",
		},
		{
			ID:          "grpc-transport",
			Name:        "gRPC Transport",
			Status:      "partial",
			Description: "gRPC servers stood up for core services; cross-service TLS pending.",
		},
		{
			ID:          "http-health-ready",
			Name:        "HTTP /healthz & /readyz",
			Status:      "yes",
			Description: "Kubernetes-style health/ready probes on HTTP :8085.",
		},
		{
			ID:          "policy-engine",
			Name:        "Capability Policy Engine",
			Status:      "yes",
			Description: "internal/policy Engine.Enforce performs RBAC over registered capabilities with OTel decisions metric; covered by engine_rbac_test.go.",
		},
		{
			ID:          "capability-registry",
			Name:        "Capability Registry",
			Status:      "yes",
			Description: "internal/registry tracks registered capabilities with dynamic ReloadManifest, semver-constrained Get, and concurrent-safe access; covered by registry_test.go.",
		},
		{
			ID:          "streaming-inference",
			Name:        "Streaming Inference",
			Status:      "yes",
			Description: "Go-side SSE event schema (StreamStart/TokenChunk/StreamEnd/StreamError) and BackpressureConfig thresholds codified in internal/streaming with contract tests; Rust model-gateway honors schema.",
		},
		{
			ID:          "provider-failover",
			Name:        "Provider Failover",
			Status:      "yes",
			Description: "internal/failover codifies FailoverConfig (RetryPolicy with positive MaxAttempts/backoff bounds, CircuitState Closed→Open→HalfOpen lifecycle, ProviderHealth tracking) with contract tests enforcing validation invariants and JSON round-trip stability.",
		},
		{
			ID:          "tool-sandboxing",
			Name:        "Tool Sandboxing",
			Status:      "yes",
			Description: "internal/sandbox codifies SandboxPolicy (AllowedSyscalls, ResourceLimits with positive CPU/memory/time bounds, NetworkPolicy allow/deny lists, FilesystemPolicy read/write roots) with contract tests enforcing validation invariants and JSON round-trip stability.",
		},
	},
	ProductShell: []Feature{
		{
			ID:          "implementation-status-api",
			Name:        "Implementation Status API",
			Status:      "yes",
			Description: "GET /api/v1/model-plane/implementation-status returns this catalog.",
		},
		{
			ID:          "gap-analysis-doc",
			Name:        "Gap Analysis Doc",
			Status:      "yes",
			Description: "docs/gap-analysis.md mirrors the in-code catalog.",
		},
		{
			ID:          "readme-landing",
			Name:        "README Landing",
			Status:      "yes",
			Description: "README links to status endpoint and gap analysis doc.",
		},
		{
			ID:          "admin-dashboard",
			Name:        "Admin Dashboard",
			Status:      "no",
			Description: "Web UI to browse capability/roadmap status; not yet implemented.",
		},
	},
	ClaudeDonorRoadmap: []Feature{
		{
			ID:          "plan-mode",
			Name:        "Plan Mode",
			Status:      "no",
			Description: "Structured plan-before-act workflow ported from Claude Code.",
		},
		{
			ID:          "extended-thinking",
			Name:        "Extended Thinking Budget",
			Status:      "no",
			Description: "Configurable reasoning-token budget for deep analysis tasks.",
		},
		{
			ID:          "subagent-orchestration",
			Name:        "Sub-agent Orchestration",
			Status:      "no",
			Description: "Parallel sub-agents with isolated context windows.",
		},
		{
			ID:          "skill-packs",
			Name:        "Skill Packs",
			Status:      "no",
			Description: "Loadable domain skills (SKILL.md) consumed by the orchestrator.",
		},
		{
			ID:          "memory-scopes",
			Name:        "Memory Scopes (user/session/repo)",
			Status:      "no",
			Description: "Tiered persistent memory across sessions and workspaces.",
		},
		{
			ID:          "hooks-pre-post-tool",
			Name:        "Pre/Post Tool-use Hooks",
			Status:      "no",
			Description: "User-configurable hooks around tool invocations.",
		},
		{
			ID:          "tool-search",
			Name:        "Deferred Tool Search",
			Status:      "no",
			Description: "On-demand loading of large tool catalogs by semantic match.",
		},
		{
			ID:          "todo-list-tool",
			Name:        "Structured Todo List Tool",
			Status:      "no",
			Description: "Agent-visible todo tracking with status transitions.",
		},
	},
	ModelPlaneV2Parity: []Feature{
		{
			ID:          "ai.embeddings",
			Name:        "Provider-backed Embeddings",
			Category:    "ai-core",
			Status:      "yes",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane has InferenceCore.CreateEmbedding and /v1/ai/embeddings; Data Plane embedding clients now call current inference-core instead of v2 ai-core.",
		},
		{
			ID:          "ai.model-catalog",
			Name:        "Model Catalogue",
			Category:    "ai-core",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane has InferenceCore.ListModels and /v1/ai/models; catalogue is env-backed until capability-core owns provider/deployment inventory.",
		},
		{
			ID:          "ai.images",
			Name:        "Image Generation, Analysis, and OCR",
			Category:    "ai-core",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane routes image generation, image analysis, and OCR through InferenceCore with OpenAI/Azure OpenAI image and vision adapters; Azure Document Intelligence read/OCR fallback and real provider smoke coverage remain pending.",
		},
		{
			ID:          "ai.speech",
			Name:        "Speech Synthesis and Transcription",
			Category:    "ai-core",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane routes TTS/STT through InferenceCore.SynthesizeSpeech/TranscribeSpeech with OpenAI, Azure OpenAI, Azure Speech TTS, /v1/ai/speech, and voice catalogue support; streaming transcription and spoken-language detection remain pending.",
		},
		{
			ID:          "ai.translation",
			Name:        "Translation and Text Language Detection",
			Category:    "ai-core",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane routes translate, batch translate, language detection, and language catalogue calls through InferenceCore with Azure Translator plus Azure/OpenAI LLM fallback; transliteration and production Azure Translator smoke coverage remain pending.",
		},
		{
			ID:          "ai.document-intelligence",
			Name:        "Document Intelligence",
			Category:    "ai-core",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane routes analyze/layout/forms/receipts/invoices through InferenceCore.AnalyzeDocument with an Azure Document Intelligence REST provider while durable document ingest remains in Data Plane; real provider smoke coverage and richer typed invoice/receipt field normalization remain pending.",
		},
		{
			ID:          "ai.language-analytics",
			Name:        "Language Analytics",
			Category:    "ai-core",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane routes sentiment, entities, key phrases, PII, language detection, and text summary through InferenceCore.AnalyzeLanguage with Azure AI Language plus Azure/OpenAI LLM fallback; production smoke coverage and typed result normalization remain pending.",
		},
		{
			ID:          "ai.realtime-video",
			Name:        "Realtime and Video APIs",
			Category:    "ai-core",
			Status:      "partial",
			Owner:       "model-plane/rust",
			Description: "Current Model Plane exposes InferenceCore.CreateRealtimeSession plus OpenAI realtime session/model routes, and CreateVideoGenerationJob/GetVideoGenerationJob/StreamVideoGenerationContent plus Azure OpenAI Sora video job/content routes; real provider smoke coverage and durable artifact handoff remain pending.",
		},
		{
			ID:          "providers.extended",
			Name:        "Extended Provider Registry",
			Category:    "providers",
			Status:      "no",
			Owner:       "model-plane/rust",
			Description: "v2 included Gemini, Mistral, Cohere, and Ollama adapters; current Model Plane has Anthropic/OpenAI/Azure chat plus OpenAI/Azure embeddings.",
		},
		{
			ID:          "agent.runtime-controls",
			Name:        "Agent Runtime Controls",
			Category:    "agent-core",
			Status:      "partial",
			Owner:       "model-plane/go",
			Description: "v2 snapshots, event history, teams, control-actions, and subagent APIs need mapping onto orchestrator/session/execution services.",
		},
		{
			ID:          "runtime.hooks-mcp-plugins",
			Name:        "Hooks, MCP, Plugins, and Commands",
			Category:    "agent-core",
			Status:      "partial",
			Owner:       "model-plane/go",
			Description: "Current Model Plane has schemas and gateway registries; persistence and real hook/command execution need to move into capability-core.",
		},
	},
}
