import {
  BarChart3,
  Bot,
  BriefcaseBusiness,
  CalendarClock,
  CheckCircle2,
  Code2,
  CreditCard,
  Database,
  FileText,
  GitBranch,
  Globe2,
  Inbox,
  MessageSquareText,
  Play,
  Rocket,
  Search,
  Settings2,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Split,
  TicketCheck,
  UsersRound,
  Workflow,
  Zap,
} from '@/shared/icons'
import {
  ChatbotVisual,
  EcommerceVisual,
  SalesVisual,
  ServiceVisual,
  WorkflowVisual,
} from '@/features/agents/components/AgentsVisuals'
import type {
  AgentFeatureId,
  AgentRoleId,
  AgentStageId,
  CoreAgentRoleId,
} from '@/features/agents/lib/agent-roles'
import type {
  AgentBlueprint,
  RoleOperatingModel,
  StageSystem,
} from '@/features/agents/lib/verevon-agent-page-types'

const roleSystems: Record<AgentRoleId, Record<AgentStageId, StageSystem>> = {
  service: {
    train: {
      eyebrow: 'Train',
      title: 'Train Service on answers, policies, and support actions',
      description: 'Model the Fin-style training flywheel around content, guidance, and tasks so the service agent knows what to say and what it can do.',
      primaryAction: 'Add help content',
      secondaryAction: 'Write guidance',
      previewTitle: 'Customer support preview',
      previewDescription: 'The preview stays beside training so teams can test an answer, inspect the source, and adjust guidance before launch.',
      checklist: ['Help center connected', 'Escalation policy drafted', 'Ticket creation allowed', 'Tone locked'],
      cards: [
        { title: 'Content', description: 'Approved sources the agent can cite.', items: ['Help center', 'Policy PDFs', 'Resolved tickets'], icon: Database },
        { title: 'Guidance', description: 'Natural-language behavior rules.', items: ['Brand voice', 'Refund boundaries', 'When to ask clarifying questions'], icon: FileText },
        { title: 'Tasks', description: 'Controlled tools for service work.', items: ['Create ticket', 'Check customer context', 'Route to team'], icon: TicketCheck },
      ],
    },
    test: {
      eyebrow: 'Test',
      title: 'Simulate full support conversations before going live',
      description: 'Run common and edge-case customer questions through a test bench, then review confidence, sources, and handoff behavior.',
      primaryAction: 'Run simulation',
      secondaryAction: 'Open test set',
      previewTitle: 'Simulation transcript',
      previewDescription: 'Each test shows the proposed answer, selected source, actions attempted, and the reason for any escalation.',
      checklist: ['Shipping question passes', 'Refund edge case escalates', 'Low confidence blocked', 'Ticket context retained'],
      cards: [
        { title: 'Batch questions', description: 'Replay support demand patterns.', items: ['Order delay', 'Refund status', 'Plan downgrade'], icon: Play },
        { title: 'Answer review', description: 'Inspect quality before deploy.', items: ['Source coverage', 'Confidence', 'Policy match'], icon: Search },
        { title: 'Handoff test', description: 'Check transfer quality.', items: ['Summary', 'Intent', 'Attempted actions'], icon: Split },
      ],
    },
    deploy: {
      eyebrow: 'Deploy',
      title: 'Deploy Service across customer support channels',
      description: 'Turn the trained agent on for the right audiences and channels while keeping escalation rules explicit.',
      primaryAction: 'Publish service agent',
      secondaryAction: 'Configure channels',
      previewTitle: 'Channel rollout',
      previewDescription: 'Start with a limited audience, then expand to live chat, email, social, and inbox routing as confidence improves.',
      checklist: ['Web chat audience selected', 'Email routing paused', 'Inbox handoff mapped', 'Auto-close reviewed'],
      cards: [
        { title: 'Chat', description: 'Answer customers in the widget.', items: ['Messenger', 'Website', 'Authenticated users'], icon: MessageSquareText },
        { title: 'Email', description: 'Handle asynchronous requests.', items: ['Inbound queue', 'Thread summary', 'Escalation inbox'], icon: Inbox },
        { title: 'Social', description: 'Support public and private channels.', items: ['WhatsApp', 'Instagram', 'SMS'], icon: Globe2 },
      ],
    },
    analyze: {
      eyebrow: 'Analyze',
      title: 'Improve Service with insight loops',
      description: 'Use performance, unresolved questions, and topic trends to decide what to train next.',
      primaryAction: 'Open insights',
      secondaryAction: 'Create improvement task',
      previewTitle: 'Service insights',
      previewDescription: 'The analysis view shows automation rate, handoff reasons, missing content, and recommended training work.',
      checklist: ['Resolution metric planned', 'Topic explorer mapped', 'Missing article list', 'CX trend baseline'],
      cards: [
        { title: 'Performance', description: 'Track operational outcomes.', items: ['Resolution rate', 'CX score', 'Handoff rate'], icon: BarChart3 },
        { title: 'Topics', description: 'Find volume drivers.', items: ['Billing', 'Shipping', 'Technical issues'], icon: Search },
        { title: 'Optimize', description: 'Convert gaps into fixes.', items: ['New content', 'Guidance edits', 'Workflow changes'], icon: Sparkles },
      ],
    },
  },
  sales: {
    train: {
      eyebrow: 'Train',
      title: 'Train Sales on qualification, objections, and booking rules',
      description: 'Give the sales agent a clear ICP, product positioning, and approved next actions before it starts engaging visitors.',
      primaryAction: 'Define ICP',
      secondaryAction: 'Add sales playbook',
      previewTitle: 'Lead qualification preview',
      previewDescription: 'Test how the agent qualifies intent, answers objections, and moves qualified buyers to a meeting.',
      checklist: ['ICP fields set', 'Objections mapped', 'Calendar connected', 'CRM write access scoped'],
      cards: [
        { title: 'Audience', description: 'Who Sales should engage.', items: ['Firmographics', 'Intent signals', 'Disqualifiers'], icon: BriefcaseBusiness },
        { title: 'Discovery', description: 'Questions the agent can ask.', items: ['Use case', 'Company size', 'Timeline'], icon: MessageSquareText },
        { title: 'Actions', description: 'Tools for handoff and booking.', items: ['Book demo', 'Create lead', 'Route account'], icon: CalendarClock },
      ],
    },
    test: {
      eyebrow: 'Test',
      title: 'Test buyer journeys before routing leads',
      description: 'Simulate first-touch, pricing, and objection flows to see when Sales should engage, qualify, or step aside.',
      primaryAction: 'Run lead tests',
      secondaryAction: 'Review CRM payload',
      previewTitle: 'Buyer simulation',
      previewDescription: 'The transcript shows qualification fields, objection handling, and the final meeting or handoff decision.',
      checklist: ['Pricing answer approved', 'Demo path works', 'Competitor objection handled', 'Low-fit lead disqualified'],
      cards: [
        { title: 'Engage', description: 'Start at the right moment.', items: ['High intent page', 'Repeat visitor', 'Campaign source'], icon: Zap },
        { title: 'Qualify', description: 'Collect useful context.', items: ['Budget', 'Timeline', 'Pain point'], icon: Search },
        { title: 'Handoff', description: 'Prepare sales-ready leads.', items: ['Owner', 'Summary', 'Next step'], icon: Split },
      ],
    },
    deploy: {
      eyebrow: 'Deploy',
      title: 'Deploy Sales where demand appears',
      description: 'Launch on high-intent pages first, then connect CRM routing and calendar ownership.',
      primaryAction: 'Publish sales agent',
      secondaryAction: 'Set targeting',
      previewTitle: 'Sales rollout',
      previewDescription: 'Target pricing, demo, and product pages while keeping CRM writes and booking actions controlled.',
      checklist: ['Pricing page targeted', 'Round robin set', 'CRM fields mapped', 'Demo calendar enabled'],
      cards: [
        { title: 'Website', description: 'Start conversations on key pages.', items: ['Pricing', 'Demo', 'Product'], icon: Globe2 },
        { title: 'CRM', description: 'Write structured lead context.', items: ['Lifecycle stage', 'Owner', 'Notes'], icon: Database },
        { title: 'Calendar', description: 'Convert intent into meetings.', items: ['Availability', 'Routing', 'Confirmation'], icon: CalendarClock },
      ],
    },
    analyze: {
      eyebrow: 'Analyze',
      title: 'Measure Sales quality and conversion',
      description: 'Track which conversations became qualified leads, booked meetings, and pipeline.',
      primaryAction: 'Open sales insights',
      secondaryAction: 'Tune qualification',
      previewTitle: 'Sales performance',
      previewDescription: 'Analyze lead quality, conversion paths, objections, and handoff accuracy.',
      checklist: ['Qualified metric planned', 'Booking metric planned', 'Objection topics grouped', 'Pipeline attribution mapped'],
      cards: [
        { title: 'Conversion', description: 'Measure funnel impact.', items: ['Engaged visitors', 'Qualified leads', 'Meetings booked'], icon: BarChart3 },
        { title: 'Objections', description: 'Learn why buyers hesitate.', items: ['Pricing', 'Security', 'Integrations'], icon: Search },
        { title: 'Optimization', description: 'Improve the sales playbook.', items: ['Better answers', 'New routing', 'Retargeting'], icon: Sparkles },
      ],
    },
  },
  ecommerce: {
    train: {
      eyebrow: 'Train',
      title: 'Train Ecommerce on catalog, policies, and shopper guidance',
      description: 'Connect product data and store rules so the agent can guide discovery without inventing inventory or return terms.',
      primaryAction: 'Connect catalog',
      secondaryAction: 'Add store policies',
      previewTitle: 'Shopper preview',
      previewDescription: 'Preview product recommendations, comparison answers, and return-policy boundaries before deploy.',
      checklist: ['Catalog synced', 'Return policy loaded', 'Size guide added', 'Escalation path set'],
      cards: [
        { title: 'Catalog', description: 'Products the agent can recommend.', items: ['Variants', 'Inventory', 'Collections'], icon: ShoppingBag },
        { title: 'Policies', description: 'Store rules and constraints.', items: ['Returns', 'Shipping', 'Discounts'], icon: FileText },
        { title: 'Guidance', description: 'How recommendations should work.', items: ['Preferences', 'Use case', 'Budget'], icon: Sparkles },
      ],
    },
    test: {
      eyebrow: 'Test',
      title: 'Test product discovery and cart flows',
      description: 'Run realistic shopper questions to verify recommendations, comparisons, and fallback behavior.',
      primaryAction: 'Run shopper tests',
      secondaryAction: 'Compare recommendations',
      previewTitle: 'Shopper simulation',
      previewDescription: 'The test view shows recommended products, data used, and why an item was suggested or rejected.',
      checklist: ['Specific product request passes', 'Out-of-stock fallback works', 'Return question answered', 'Cart handoff ready'],
      cards: [
        { title: 'Discover', description: 'Find the right product.', items: ['Need', 'Preference', 'Budget'], icon: Search },
        { title: 'Compare', description: 'Help shoppers choose.', items: ['Features', 'Price', 'Fit'], icon: Split },
        { title: 'Recover', description: 'Reduce buying friction.', items: ['Cart question', 'Discount rules', 'Checkout issue'], icon: TicketCheck },
      ],
    },
    deploy: {
      eyebrow: 'Deploy',
      title: 'Deploy Ecommerce on store touchpoints',
      description: 'Launch on product pages and cart paths where guidance can reduce friction and increase purchase confidence.',
      primaryAction: 'Publish store agent',
      secondaryAction: 'Set store targeting',
      previewTitle: 'Store rollout',
      previewDescription: 'Deploy to product pages, cart, and post-purchase support while protecting live inventory and order APIs.',
      checklist: ['Product-page rules mapped', 'Cart targeting set', 'Order lookup scoped', 'Support fallback mapped'],
      cards: [
        { title: 'Storefront', description: 'Help shoppers browse.', items: ['Home', 'Collection', 'Product'], icon: Globe2 },
        { title: 'Cart', description: 'Reduce checkout uncertainty.', items: ['Shipping estimate', 'Promo terms', 'Returns'], icon: ShoppingBag },
        { title: 'Order support', description: 'Handle after-purchase questions.', items: ['Status', 'Refund', 'Exchange'], icon: Inbox },
      ],
    },
    analyze: {
      eyebrow: 'Analyze',
      title: 'Analyze shopper outcomes and catalog gaps',
      description: 'Track product questions, recommendation clicks, cart saves, and unresolved store-policy issues.',
      primaryAction: 'Open commerce insights',
      secondaryAction: 'Improve catalog guidance',
      previewTitle: 'Commerce insights',
      previewDescription: 'Use discovery questions and failed recommendations to improve catalog data and shopper guidance.',
      checklist: ['Top questions grouped', 'Recommendation events mapped', 'Cart recovery metric planned', 'Policy gaps surfaced'],
      cards: [
        { title: 'Discovery', description: 'Understand shopper demand.', items: ['Top products', 'Missing attributes', 'Search intent'], icon: Search },
        { title: 'Conversion', description: 'Measure purchase support.', items: ['Clicks', 'Cart saves', 'Checkout starts'], icon: BarChart3 },
        { title: 'Gaps', description: 'Fix store data quality.', items: ['Missing sizes', 'Weak descriptions', 'Policy conflicts'], icon: Sparkles },
      ],
    },
  },
  chatbot: {
    train: {
      eyebrow: 'Train',
      title: 'Build the chatbot with data sources, instructions, and actions',
      description: 'Use the Chatbase-style builder pattern: train the agent from sources, tune instructions, then attach controlled actions.',
      primaryAction: 'Add data source',
      secondaryAction: 'Edit base instructions',
      previewTitle: 'Chatbot builder',
      previewDescription: 'A playground-style preview stays next to configuration so every source or instruction change can be tested immediately.',
      checklist: ['Website source added', 'Files indexed', 'Base prompt written', 'One action enabled'],
      cards: [
        { title: 'Data sources', description: 'Train from approved material.', items: ['Website', 'Files', 'Q&A snippets'], icon: Database },
        { title: 'Instructions', description: 'Define tone and boundaries.', items: ['Role', 'Voice', 'Blocked topics'], icon: FileText },
        { title: 'AI Actions', description: 'Let the chatbot do useful work.', items: ['Order lookup', 'Create ticket', 'Lead capture'], icon: Zap },
      ],
    },
    test: {
      eyebrow: 'Test',
      title: 'Use a playground to compare chatbot behavior',
      description: 'Mirror the Chatbase testing loop with a playground, repeatable prompts, source inspection, and answer comparison.',
      primaryAction: 'Open playground',
      secondaryAction: 'Compare variants',
      previewTitle: 'Playground compare',
      previewDescription: 'Send the same prompt across model, prompt, or action settings to choose the best behavior before deploy.',
      checklist: ['Greeting checked', 'Source citation reviewed', 'Action call tested', 'Fallback response approved'],
      cards: [
        { title: 'Prompt tests', description: 'Replay realistic questions.', items: ['Pricing', 'Setup', 'Troubleshooting'], icon: Play },
        { title: 'Compare', description: 'Evaluate variants side by side.', items: ['Model', 'Tone', 'Source scope'], icon: Split },
        { title: 'Debug', description: 'Inspect why an answer happened.', items: ['Sources', 'System prompt', 'Action logs'], icon: Search },
      ],
    },
    deploy: {
      eyebrow: 'Deploy',
      title: 'Deploy the chatbot as a branded web widget',
      description: 'Generate the embed, choose widget behavior, and define when conversations transfer into support workflows.',
      primaryAction: 'Copy embed script',
      secondaryAction: 'Customize widget',
      previewTitle: 'Widget deploy',
      previewDescription: 'Preview the launcher, opening message, conversation position, and escalation target before publishing.',
      checklist: ['Public visibility set', 'Widget theme selected', 'Domain allowlist added', 'Escalation inbox connected'],
      cards: [
        { title: 'Chat widget', description: 'Install the agent on the site.', items: ['Embed script', 'Allowed domains', 'Launcher'], icon: Code2 },
        { title: 'Appearance', description: 'Brand the experience.', items: ['Logo', 'Accent', 'Welcome text'], icon: Settings2 },
        { title: 'Handoff', description: 'Move conversations to humans.', items: ['Inbox', 'Email', 'Webhook'], icon: Split },
      ],
    },
    analyze: {
      eyebrow: 'Analyze',
      title: 'Improve the chatbot from unanswered questions',
      description: 'Track missing answers, source gaps, action errors, and customer outcomes to decide what to train next.',
      primaryAction: 'Open chatbot analytics',
      secondaryAction: 'Create training task',
      previewTitle: 'Chatbot analytics',
      previewDescription: 'Review unresolved questions, weak sources, and action failures from the same operational view.',
      checklist: ['Unanswered questions grouped', 'Source gaps ranked', 'Action errors queued', 'Handoff topics reviewed'],
      cards: [
        { title: 'Questions', description: 'Find what users ask.', items: ['Top prompts', 'No-answer prompts', 'Repeat topics'], icon: Search },
        { title: 'Quality', description: 'Measure answer health.', items: ['Resolution', 'Source use', 'Fallback rate'], icon: BarChart3 },
        { title: 'Training loop', description: 'Turn gaps into improvements.', items: ['Add source', 'Edit prompt', 'Fix action'], icon: Sparkles },
      ],
    },
  },
  workflow: {
    train: {
      eyebrow: 'Train',
      title: 'Define workflow triggers, blocks, and tool permissions',
      description: 'Treat the workflow builder as an operational agent: define the trigger, what context it can inspect, and which tools it may call.',
      primaryAction: 'Choose trigger',
      secondaryAction: 'Add tool block',
      previewTitle: 'Workflow canvas',
      previewDescription: 'A canvas preview shows trigger, AI step, branch, and merge blocks before the workflow is tested.',
      checklist: ['Trigger selected', 'AI block configured', 'Tool permissions scoped', 'Fallback branch set'],
      cards: [
        { title: 'Trigger', description: 'What starts the workflow.', items: ['Schedule', 'New conversation', 'Webhook'], icon: CalendarClock },
        { title: 'AI block', description: 'Reason over context.', items: ['Classify', 'Generate', 'Summarize'], icon: Bot },
        { title: 'Tools', description: 'Perform controlled work.', items: ['Sheets', 'CRM', 'Slack'], icon: Workflow },
      ],
    },
    test: {
      eyebrow: 'Test',
      title: 'Run workflow simulations before publishing',
      description: 'Use test runs to inspect every node, output, branch decision, and tool payload.',
      primaryAction: 'Run workflow test',
      secondaryAction: 'Inspect node logs',
      previewTitle: 'Test run trace',
      previewDescription: 'Each node shows input, output, latency, and error state so failures can be fixed without guessing.',
      checklist: ['Trigger payload valid', 'Branch decision correct', 'Tool output shaped', 'Error path tested'],
      cards: [
        { title: 'Node trace', description: 'Inspect every step.', items: ['Input', 'Output', 'Latency'], icon: Search },
        { title: 'Branches', description: 'Validate routing.', items: ['If qualified', 'If missing data', 'If failed'], icon: GitBranch },
        { title: 'Outputs', description: 'Check final artifacts.', items: ['Caption', 'Ticket', 'Status update'], icon: TicketCheck },
      ],
    },
    deploy: {
      eyebrow: 'Deploy',
      title: 'Publish workflows with version control',
      description: 'Deploy a tested workflow with a clear owner, rollback path, and runtime guardrails.',
      primaryAction: 'Publish workflow',
      secondaryAction: 'Create version',
      previewTitle: 'Publish controls',
      previewDescription: 'Publish only when the workflow has passed tests and every external action has a scoped credential.',
      checklist: ['Version named', 'Owner assigned', 'Credentials scoped', 'Rollback ready'],
      cards: [
        { title: 'Version', description: 'Control what is live.', items: ['Draft', 'Published', 'Rollback'], icon: Rocket },
        { title: 'Runtime', description: 'Set execution rules.', items: ['Rate limits', 'Retries', 'Timeouts'], icon: Settings2 },
        { title: 'Notifications', description: 'Keep teams in the loop.', items: ['Slack', 'Email', 'Inbox'], icon: Inbox },
      ],
    },
    analyze: {
      eyebrow: 'Analyze',
      title: 'Analyze workflow throughput and failures',
      description: 'Monitor runs, errors, saved time, and branch distribution to tune the workflow over time.',
      primaryAction: 'Open run analytics',
      secondaryAction: 'Tune workflow',
      previewTitle: 'Workflow analytics',
      previewDescription: 'Use run history and failure clustering to decide which node or prompt needs improvement.',
      checklist: ['Run success metric planned', 'Failure reasons grouped', 'Latency target visible', 'Manual saves estimated'],
      cards: [
        { title: 'Runs', description: 'Track workflow activity.', items: ['Started', 'Completed', 'Failed'], icon: BarChart3 },
        { title: 'Failures', description: 'Find fragile nodes.', items: ['Auth', 'Timeout', 'Bad output'], icon: Search },
        { title: 'Impact', description: 'Measure operational value.', items: ['Time saved', 'Tasks closed', 'Manual reviews'], icon: Sparkles },
      ],
    },
  },
}

const roleFeatureWorkspaces: Record<CoreAgentRoleId, Partial<Record<AgentFeatureId, StageSystem>>> = {
  service: {
    'service-resolution': {
      eyebrow: 'Resolution queue',
      title: 'Service agent resolution workspace',
      description: 'Run a Fin, Zendesk, and Ada-inspired service desk where every conversation moves through answer, action, verified review, and handoff states.',
      primaryAction: 'Review queue',
      secondaryAction: 'Open routing rules',
      previewTitle: 'Customer support preview',
      previewDescription: 'The preview shows how Verevon answers with context, cites policy, and escalates when the promise is risky.',
      checklist: ['Priority queue mapped', 'Verified resolution QA required', 'Human handoff rules required', 'Ticket summary scoped', 'Escalation reasons mapped'],
      cards: [
        { title: 'Intake queue', description: 'Classify support demand before answering.', items: ['Billing', 'Shipping', 'Security'], icon: Inbox },
        { title: 'Action state', description: 'Only approved procedures and tools can run.', items: ['Create ticket', 'Lookup order', 'Route owner', 'Verify outcome'], icon: TicketCheck },
        { title: 'Handoff', description: 'Give teammates a clean summary.', items: ['Intent', 'Customer context', 'Attempted actions'], icon: Split },
      ],
    },
    'service-knowledge': {
      eyebrow: 'Knowledge',
      title: 'Ground Service in trusted support content',
      description: 'Use Intercom Fin-style content, guidance, attributes, tone, answer length, and resolved conversations to answer without inventing details.',
      primaryAction: 'Add source',
      secondaryAction: 'Inspect coverage',
      previewTitle: 'Source-grounded answer',
      previewDescription: 'Each answer links back to approved content or a tool result so support leads can audit quality.',
      checklist: ['Help center mapped', 'Fin guidance scoped', 'Attributes mapped', 'Policy docs mapped', 'Missing article queue scoped'],
      cards: [
        { title: 'Help center', description: 'Approved public support content.', items: ['FAQs', 'Troubleshooting', 'Product docs'], icon: Database },
        { title: 'Guidance library', description: 'Rules the agent must obey.', items: ['Refunds', 'Privacy', 'Tone', 'Answer length'], icon: FileText },
        { title: 'Answer gaps', description: 'Questions with weak coverage.', items: ['Missing source', 'Low confidence', 'No matching policy'], icon: Search },
      ],
    },
    'service-actions': {
      eyebrow: 'Service actions',
      title: 'Control what Service can do for customers',
      description: 'Give the agent Ada-style Actions, Processes, and Coaching for tickets, account reads, diagnostics, and safe routing.',
      primaryAction: 'Add action',
      secondaryAction: 'Edit permissions',
      previewTitle: 'Action run preview',
      previewDescription: 'The agent explains what it can do, asks before sensitive actions, and logs every tool attempt.',
      checklist: ['Ticket tool scoped', 'Process steps approved', 'Order lookup read-only', 'Refund approval required', 'PII fields hidden'],
      cards: [
        { title: 'Create ticket', description: 'Package context for support.', items: ['Transcript', 'Priority', 'Intent', 'Outcome'], icon: TicketCheck },
        { title: 'Run process', description: 'Read state without leaking data.', items: ['Plan', 'Order', 'Diagnostic', 'Status'], icon: Search },
        { title: 'Route work', description: 'Send sensitive issues to humans.', items: ['Billing', 'Security', 'Angry customer'], icon: Split },
      ],
    },
    'service-channels': {
      eyebrow: 'Channels',
      title: 'Launch Service across support channels',
      description: 'Map confidence, handoff, and reply behavior for chat, email, voice, WhatsApp, Instagram, Discord, and inbox queues.',
      primaryAction: 'Configure channel',
      secondaryAction: 'Open rollout',
      previewTitle: 'Channel rollout',
      previewDescription: 'Start with web chat, then expand once answer quality and handoff accuracy are stable.',
      checklist: ['Web chat ready', 'Email drafts enabled', 'Voice path mapped', 'Social tone mapped', 'Inbox handoff tested'],
      cards: [
        { title: 'Messenger', description: 'Fast authenticated support.', items: ['Website', 'App', 'Logged-in users'], icon: MessageSquareText },
        { title: 'Email + voice', description: 'Policy-aware drafts and calls.', items: ['Queue', 'Thread summary', 'Voice handoff'], icon: Inbox },
        { title: 'Social', description: 'Consistent private replies.', items: ['WhatsApp', 'Instagram', 'Discord', 'SMS'], icon: Globe2 },
      ],
    },
    'service-quality': {
      eyebrow: 'Quality supervisor',
      title: 'Score every service answer before scaling',
      description: 'Monitor source coverage, policy fit, confidence, sentiment, verified resolution, and escalation risk in one review surface.',
      primaryAction: 'Review answers',
      secondaryAction: 'Edit QA rules',
      previewTitle: 'QA review',
      previewDescription: 'Low-confidence answers are blocked or routed instead of being treated as deflection wins.',
      checklist: ['Source required', 'Verified resolution sampled', 'Refund boundary required', 'Low confidence blocked', 'Audit samples queued'],
      cards: [
        { title: 'Source fit', description: 'Answer must be grounded.', items: ['Cited', 'Current', 'Relevant'], icon: FileText },
        { title: 'Resolution fit', description: 'Rules are checked before reply.', items: ['Refund', 'Warranty', 'Privacy', 'Solved'], icon: CheckCircle2 },
        { title: 'Risk review', description: 'Sensitive cases are escalated.', items: ['Security', 'Legal', 'Payment'], icon: ShieldCheck },
      ],
    },
    'service-insights': {
      eyebrow: 'Insights',
      title: 'Improve Service with conversation intelligence',
      description: 'Turn Fin-style suggestions, Zendesk trend detection, unresolved topics, repeated escalations, and missing content into the next support improvements.',
      primaryAction: 'Open insights',
      secondaryAction: 'Create training task',
      previewTitle: 'Service insights',
      previewDescription: 'The agent shows which answers saved time and which topics need better content or actions.',
      checklist: ['Suggestions generated', 'Topic clusters live', 'Missing sources listed', 'Escalation reasons grouped', 'Automation rate measured'],
      cards: [
        { title: 'Automation', description: 'Measure resolved conversations.', items: ['Deflection', 'CSAT', 'AHT'], icon: BarChart3 },
        { title: 'Recommendations', description: 'Find missing knowledge.', items: ['No source', 'Weak policy', 'Repeated handoff', 'Next content'], icon: Search },
        { title: 'Next work', description: 'Prioritize improvements.', items: ['Article', 'Tool', 'Guardrail'], icon: Sparkles },
      ],
    },
  },
  sales: {
    'sales-lead-capture': {
      eyebrow: 'Lead capture',
      title: 'Sales agent intent capture workspace',
      description: 'Use Qualified Piper and Drift-style engagement to identify high-intent visitors, proactively greet them, guide the website journey, and keep rep handoff clean.',
      primaryAction: 'Tune triggers',
      secondaryAction: 'Open playbook',
      previewTitle: 'Lead qualification preview',
      previewDescription: 'Verevon engages when buying intent is visible, not after the visitor has left the page.',
      checklist: ['Pricing trigger mapped', 'Proactive greeting drafted', 'Guided tour prompts mapped', 'Campaign context mapped', 'Low-fit path mapped'],
      cards: [
        { title: 'Intent', description: 'Behavior that starts a conversation.', items: ['Pricing views', 'Return visit', 'Security page', 'High-fit account'], icon: Zap },
        { title: 'Message', description: 'Contextual opening prompts.', items: ['Plan fit', 'Use case', 'Guided tour', 'Next step'], icon: MessageSquareText },
        { title: 'Route', description: 'Lead moves to the right owner.', items: ['Region', 'Segment', 'Account', 'Rep handoff'], icon: Split },
      ],
    },
    'sales-qualification': {
      eyebrow: 'Qualification',
      title: 'Qualify leads before booking a meeting',
      description: 'Use Drift-style visitor intelligence and account data to collect fit, urgency, budget, company size, and pain before routing.',
      primaryAction: 'Edit scorecard',
      secondaryAction: 'Open routing',
      previewTitle: 'Qualification preview',
      previewDescription: 'The agent asks compact discovery questions and explains why a visitor is sales-ready.',
      checklist: ['Fit score required', 'Account data mapped', 'Required fields mapped', 'Disqualifiers written', 'Enterprise route scoped'],
      cards: [
        { title: 'Fit', description: 'Who should talk to sales.', items: ['Size', 'Use case', 'Budget', 'Account history'], icon: BriefcaseBusiness },
        { title: 'Urgency', description: 'How soon they need help.', items: ['Timeline', 'Trigger', 'Risk', 'Buying signal'], icon: CalendarClock },
        { title: 'Score', description: 'Confidence before handoff.', items: ['High', 'Medium', 'Self-serve', 'Fast lane'], icon: BarChart3 },
      ],
    },
    'sales-objections': {
      eyebrow: 'Objections',
      title: 'Answer objections with approved sales guidance',
      description: 'Use Agentforce SDR-style product answers and objection handling for pricing, implementation, security, and migration without inventing discounts or terms.',
      primaryAction: 'Add objection',
      secondaryAction: 'Review answers',
      previewTitle: 'Objection handling',
      previewDescription: 'The agent can answer common concerns and route deal-sensitive questions to the owner.',
      checklist: ['Product answers approved', 'Pricing boundaries set', 'Security pack linked', 'Competitor claims approved', 'Discount escalation required'],
      cards: [
        { title: 'Pricing', description: 'Stay within approved plan language.', items: ['Plan', 'Contract', 'Discount'], icon: CreditCard },
        { title: 'Security', description: 'Give vetted trust answers.', items: ['SOC2', 'DPA', 'SSO', 'Procurement'], icon: ShieldCheck },
        { title: 'Migration', description: 'Explain onboarding effort.', items: ['Data', 'Team', 'Timeline'], icon: Database },
      ],
    },
    'sales-booking': {
      eyebrow: 'Meeting booking',
      title: 'Route qualified buyers into the right calendar',
      description: 'Show meeting slots only after qualification, then book through the record owner calendar or send the owner meeting link.',
      primaryAction: 'Connect calendar',
      secondaryAction: 'Edit routing',
      previewTitle: 'Booking preview',
      previewDescription: 'Qualified buyers can book without waiting for a rep, while low-fit visitors get self-serve next steps.',
      checklist: ['Owner calendar connection planned', 'Owner routing scoped', 'Meeting link fallback scoped', 'Meeting types mapped', 'No-show recap scoped'],
      cards: [
        { title: 'Owner', description: 'Route by account context.', items: ['AE', 'Founder', 'CS'], icon: UsersRound },
        { title: 'Meeting type', description: 'Match the buying motion.', items: ['Demo', 'Consult', 'Technical', 'Live chat'], icon: CalendarClock },
        { title: 'Prep', description: 'Send context to the rep.', items: ['Pain', 'Pages', 'Objections'], icon: FileText },
      ],
    },
    'sales-crm': {
      eyebrow: 'CRM handoff',
      title: 'Write structured CRM handoffs for every lead',
      description: 'Use HubSpot Breeze-style account research, buying signals, personalized outreach context, page history, campaign context, and objections in every handoff.',
      primaryAction: 'Map fields',
      secondaryAction: 'Preview handoff',
      previewTitle: 'CRM summary',
      previewDescription: 'Every booked meeting includes source page, buying intent, qualification fields, and recommended follow-up.',
      checklist: ['CRM connected', 'Buying signals attached', 'Research notes generated', 'Owner field synced', 'Handoff template approved'],
      cards: [
        { title: 'Lead', description: 'Capture the buyer context.', items: ['Company', 'Role', 'Need', 'Research'], icon: BriefcaseBusiness },
        { title: 'Activity', description: 'Attach behavior.', items: ['Pages', 'Campaign', 'Chat', 'Signal'], icon: BarChart3 },
        { title: 'Next step', description: 'Make the handoff actionable.', items: ['Meeting', 'Owner', 'Summary', 'Outreach'], icon: Split },
      ],
    },
    'sales-insights': {
      eyebrow: 'Pipeline insights',
      title: 'Improve conversion with sales-agent analytics',
      description: 'See which triggers, visitor signals, objections, routes, and automation controls create qualified meetings instead of empty conversations.',
      primaryAction: 'Open analytics',
      secondaryAction: 'Tune triggers',
      previewTitle: 'Sales insights',
      previewDescription: 'The agent reports lead quality, conversion paths, objections, and handoff accuracy.',
      checklist: ['Qualified meeting metric planned', 'Audit trail required', 'Objections clustered', 'Drop-off page mapped', 'Routing quality metric planned'],
      cards: [
        { title: 'Conversion', description: 'Measure meetings and fit.', items: ['Visitors', 'Qualified', 'Booked'], icon: BarChart3 },
        { title: 'Objections', description: 'Find what slows buyers.', items: ['Pricing', 'Security', 'Timing', 'Implementation'], icon: Search },
        { title: 'Routing', description: 'Improve owner assignment.', items: ['Region', 'Segment', 'Tier', 'Audit'], icon: Split },
      ],
    },
  },
  ecommerce: {
    'commerce-shopping': {
      eyebrow: 'Shopping assistant',
      title: 'Ecommerce shopping assistant workspace',
      description: 'Blend Gorgias-style shopping assistance with product recommendations, proactive quick replies, upsells, and product-page FAQs.',
      primaryAction: 'Tune assistant',
      secondaryAction: 'Open catalog rules',
      previewTitle: 'Shopper preview',
      previewDescription: 'The agent guides discovery with catalog-grounded answers, product cards, and safe conversion nudges.',
      checklist: ['Catalog mapped', 'AI FAQs drafted', 'Quick replies mapped', 'Upsell rules scoped', 'Human handoff mapped'],
      cards: [
        { title: 'Product questions', description: 'Answer from live product data.', items: ['Sizing', 'Materials', 'Availability'], icon: ShoppingBag },
        { title: 'Recommendations', description: 'Match shopper need to inventory.', items: ['Budget', 'Fit', 'Use case', 'One-tap replies'], icon: Sparkles },
        { title: 'Conversion', description: 'Nudge without overpromising.', items: ['Compare', 'Add-on', 'Offer'], icon: Rocket },
      ],
    },
    'commerce-support': {
      eyebrow: 'Support & orders',
      title: 'Resolve post-purchase ecommerce requests',
      description: 'Use Gorgias-style order support for tracking, returns, exchanges, subscription changes, and damaged-item workflows.',
      primaryAction: 'Connect orders',
      secondaryAction: 'Edit return rules',
      previewTitle: 'Order support preview',
      previewDescription: 'Verevon checks order state before answering and starts only the allowed post-purchase path.',
      checklist: ['Order lookup read-only', 'Return portal connection planned', 'Subscription rules scoped', 'Damaged item flow scoped'],
      cards: [
        { title: 'Order tracking', description: 'Answer WISMO from live status.', items: ['Carrier', 'ETA', 'Delay'], icon: Search },
        { title: 'Returns', description: 'Start the allowed workflow.', items: ['Window', 'Reason', 'Label'], icon: TicketCheck },
        { title: 'Subscriptions', description: 'Handle common account requests.', items: ['Pause', 'Cancel', 'Update'], icon: Settings2 },
      ],
    },
    'commerce-product-finder': {
      eyebrow: 'Product finder',
      title: 'Guide shoppers through product discovery',
      description: 'Use Rep AI-style Guided Search, product cards, and shopper intelligence to move from open-ended intent to fit.',
      primaryAction: 'Edit finder',
      secondaryAction: 'Open shopper signals',
      previewTitle: 'Product finder preview',
      previewDescription: 'The assistant asks one focused question, filters the catalog, and explains why each product fits.',
      checklist: ['Finder questions approved', 'Variant filters mapped', 'Comparison cards ready', 'Shopper profile live'],
      cards: [
        { title: 'Ask', description: 'Collect shopper preference.', items: ['Need', 'Budget', 'Constraint'], icon: MessageSquareText },
        { title: 'Filter', description: 'Use catalog attributes.', items: ['Fit', 'Stock', 'Material'], icon: Search },
        { title: 'Compare', description: 'Explain differences clearly.', items: ['Pros', 'Tradeoffs', 'Return terms'], icon: Split },
      ],
    },
    'commerce-cart': {
      eyebrow: 'Cart recovery',
      title: 'Recover carts with controlled conversion nudges',
      description: 'Detect checkout friction, answer final concerns, and apply only approved offers or shipping guidance.',
      primaryAction: 'Tune recovery',
      secondaryAction: 'Review offers',
      previewTitle: 'Cart recovery preview',
      previewDescription: 'The agent reacts to hesitation with a relevant answer, not a generic popup.',
      checklist: ['Exit intent mapped', 'Discount policy scoped', 'Shipping concerns mapped', 'Recovery events planned'],
      cards: [
        { title: 'Friction', description: 'Detect hesitation signals.', items: ['Exit intent', 'Shipping', 'Coupon'], icon: Search },
        { title: 'Answer', description: 'Resolve blockers quickly.', items: ['Delivery', 'Returns', 'Warranty'], icon: MessageSquareText },
        { title: 'Nudge', description: 'Offer only approved next steps.', items: ['Compare', 'Save cart', 'Apply offer'], icon: Rocket },
      ],
    },
    'commerce-brand': {
      eyebrow: 'Brand voice',
      title: 'Keep autonomous commerce CX on brand',
      description: 'Borrow Siena-style AI Personas and brand voice controls for chat, email, WhatsApp, Instagram, and social comments.',
      primaryAction: 'Edit voice',
      secondaryAction: 'Review channels',
      previewTitle: 'Brand voice preview',
      previewDescription: 'Replies stay empathetic and commerce-aware while following channel-specific tone rules.',
      checklist: ['AI persona drafted', 'Tone guide drafted', 'Social channels mapped', 'Channel-specific rules scoped', 'VOC tags mapped'],
      cards: [
        { title: 'AI Persona', description: 'Consistent brand tone.', items: ['Empathic', 'Concise', 'Customer language'], icon: Sparkles },
        { title: 'Social', description: 'Reply where shoppers ask.', items: ['Instagram', 'WhatsApp', 'Email', 'Comments'], icon: Globe2 },
        { title: 'Escalation', description: 'Know when to stop.', items: ['Angry', 'VIP', 'Payment'], icon: Split },
      ],
    },
    'commerce-store': {
      eyebrow: 'Store actions',
      title: 'Sidekick-style store command center',
      description: 'Let operators ask for guidance, content, app generation, and store tasks in plain language, then inspect and approve changes.',
      primaryAction: 'Run command',
      secondaryAction: 'Open approvals',
      previewTitle: 'Store command preview',
      previewDescription: 'Commands can draft product content, inspect inventory, build automations, or suggest admin actions before approval.',
      checklist: ['Shopify data connected', 'Approval required', 'Inventory actions scoped', 'Generated content reviewed', 'Admin app drafts gated'],
      cards: [
        { title: 'Ask', description: 'Everyday-language admin command.', items: ['Products', 'Orders', 'Analytics', 'Guidance'], icon: MessageSquareText },
        { title: 'Review', description: 'Inspect planned changes.', items: ['Diff', 'Risk', 'Owner'], icon: CheckCircle2 },
        { title: 'Apply', description: 'Approve controlled actions.', items: ['Content', 'Tags', 'Flow', 'App draft'], icon: Settings2 },
      ],
    },
    'commerce-insights': {
      eyebrow: 'Shopper insights',
      title: 'Turn shopper conversations into revenue insights',
      description: 'Track questions, drop-offs, product gaps, cart blockers, and what the assistant did to convert or resolve them.',
      primaryAction: 'Open insights',
      secondaryAction: 'Create action',
      previewTitle: 'Shopper intelligence',
      previewDescription: 'Verevon shows what shoppers ask before buying and what policies or products create friction.',
      checklist: ['Intent stages planned', 'Product gaps clustered', 'Cart blockers ranked', 'Revenue attribution planned'],
      cards: [
        { title: 'Intent', description: 'Understand where shoppers are.', items: ['Discovery', 'Compare', 'Ready'], icon: BarChart3 },
        { title: 'Gaps', description: 'See missing catalog answers.', items: ['Sizing', 'Stock', 'Compatibility'], icon: Search },
        { title: 'Revenue', description: 'Attribute assists and saves.', items: ['AOV', 'Recovered', 'Assisted'], icon: ShoppingBag },
      ],
    },
  },
}

const roleOperatingModels: Record<'service' | 'sales' | 'ecommerce', RoleOperatingModel> = {
  service: {
    activationLabel: 'Activate service agent',
    activationStatus: 'Blueprint ready for assisted launch',
    activationSummary: 'Defines the support sources, ticket actions, and guarded human handoff required before activation.',
    model: 'Verevon CX Reasoner',
    confidence: 'Confidence policy required',
    automationTarget: 'Live automation rate appears after launch',
    metrics: [
      { label: 'Sources', value: 'Scope', detail: 'Help center, policy PDFs, resolved tickets' },
      { label: 'Actions', value: 'Guarded', detail: 'Ticket, refund status, order lookup, routing' },
      { label: 'Guardrails', value: 'Policy', detail: 'Refund limits, PII, source citations, handoff rules' },
    ],
    knowledge: [
      { title: 'Help center', description: 'Approved answers, troubleshooting guides, and product docs.', status: 'Map', icon: Database },
      { title: 'Resolved tickets', description: 'Reusable patterns from prior high-quality human replies.', status: 'Review', icon: Inbox },
      { title: 'Policy library', description: 'Refund, cancellation, privacy, and SLA guidance.', status: 'Policy', icon: FileText },
    ],
    actions: [
      { title: 'Create support ticket', description: 'Creates a ticket with transcript, intent, priority, and customer context.', status: 'Scoped', icon: TicketCheck },
      { title: 'Check order or account', description: 'Reads customer status without exposing private fields in chat.', status: 'Read-only', icon: Search },
      { title: 'Route to teammate', description: 'Hands off billing, security, and angry-customer cases with a summary.', status: 'Scoped', icon: Split },
    ],
    channels: [
      { title: 'Web messenger', description: 'Answers authenticated and anonymous visitors from the Verevon widget.', status: 'Plan', icon: MessageSquareText },
      { title: 'Email queue', description: 'Drafts policy-aware replies and escalates low-confidence threads.', status: 'Review', icon: Inbox },
      { title: 'Social messaging', description: 'Keeps WhatsApp and Instagram replies consistent with support policy.', status: 'Mapped', icon: Globe2 },
    ],
    guardrails: [
      { title: 'Confidence handoff', description: 'Escalates below threshold instead of guessing.', status: 'Required', icon: CheckCircle2 },
      { title: 'Refund boundary', description: 'Can explain rules, but needs approval above the configured cap.', status: 'Required', icon: Settings2 },
      { title: 'Source required', description: 'Answers service policies only when a source or tool result supports them.', status: 'Required', icon: FileText },
    ],
    conversation: {
      customer: 'My order is late and I need it before Friday.',
      agent: 'I found the shipment and the carrier scan is delayed. I can create a priority ticket with the tracking details or show the current delivery window.',
      note: 'Uses order lookup, cites shipping policy, and escalates if delivery promise risk is high.',
      quickReplies: ['Create priority ticket', 'Show delivery window', 'Hand off to support'],
    },
  },
  sales: {
    activationLabel: 'Activate sales agent',
    activationStatus: 'Blueprint ready for pricing and demo pages',
    activationSummary: 'Defines qualification criteria, objection handling, CRM handoff, and calendar booking before activation.',
    model: 'Verevon Revenue Reasoner',
    confidence: 'Qualification policy required',
    automationTarget: 'Live conversion rate appears after launch',
    metrics: [
      { label: 'ICP fields', value: 'Plan', detail: 'Company size, use case, urgency, fit, budget' },
      { label: 'Routing rules', value: 'Scope', detail: 'Owner, region, account tier, enterprise intent' },
      { label: 'Booking paths', value: 'Review', detail: 'Demo, founder call, solution consult' },
    ],
    knowledge: [
      { title: 'Product positioning', description: 'Use cases, differentiators, pricing notes, and competitor answers.', status: 'Plan', icon: BriefcaseBusiness },
      { title: 'Sales playbook', description: 'Discovery questions, disqualifiers, and approved objection handling.', status: 'Review', icon: FileText },
      { title: 'CRM context', description: 'Campaign touches, prior forms, account owner, and lifecycle stage.', status: 'Connect', icon: Database },
    ],
    actions: [
      { title: 'Qualify lead', description: 'Collects pain, urgency, size, budget range, and buying committee signals.', status: 'Scope', icon: Search },
      { title: 'Book meeting', description: 'Finds the right calendar by region, segment, and account owner.', status: 'Connect', icon: CalendarClock },
      { title: 'Create CRM handoff', description: 'Writes a structured summary with source page, objections, and next step.', status: 'Scoped', icon: Split },
    ],
    channels: [
      { title: 'Pricing page', description: 'Engages visitors comparing plans or asking contract questions.', status: 'Plan', icon: Globe2 },
      { title: 'Demo flow', description: 'Turns active demand into a booked meeting without waiting for a form reply.', status: 'Plan', icon: CalendarClock },
      { title: 'Follow-up email', description: 'Sends rep-approved recap and meeting details after qualification.', status: 'Draft', icon: Inbox },
    ],
    guardrails: [
      { title: 'No unauthorized discounts', description: 'Explains pricing only from approved plans and routes exceptions.', status: 'Required', icon: CheckCircle2 },
      { title: 'Low-fit disqualification', description: 'Politely redirects low-fit visitors to self-serve resources.', status: 'Required', icon: Split },
      { title: 'Enterprise handoff', description: 'Routes procurement, security, and legal questions to the right owner.', status: 'Required', icon: BriefcaseBusiness },
    ],
    conversation: {
      customer: 'We are evaluating Verevon for support automation. Can we compare plan fit and book time?',
      agent: 'Yes. I can outline the plan fit, ask two qualification questions, and route you to the enterprise calendar with your context attached.',
      note: 'Qualifies company size, use case, and urgency before booking a sales-owned slot.',
      quickReplies: ['Ask qualification questions', 'Show plan fit', 'Book enterprise demo'],
    },
  },
  ecommerce: {
    activationLabel: 'Activate ecommerce agent',
    activationStatus: 'Blueprint ready for store journeys',
    activationSummary: 'Defines catalog grounding, product guidance, order help, and cart recovery controls before activation.',
    model: 'Verevon Commerce Reasoner',
    confidence: 'Product confidence policy required',
    automationTarget: 'Live assisted revenue appears after launch',
    metrics: [
      { label: 'Catalog fields', value: 'Scope', detail: 'Variants, inventory, fit, materials, collections' },
      { label: 'Store actions', value: 'Guarded', detail: 'Recommend, compare, order lookup, return start' },
      { label: 'Intent stages', value: 'Plan', detail: 'Discovery, interested, ready to buy' },
    ],
    knowledge: [
      { title: 'Product catalog', description: 'Live products, variants, availability, collections, and metadata.', status: 'Connect', icon: ShoppingBag },
      { title: 'Shopper context', description: 'Viewed products, cart contents, purchase history, and current page.', status: 'Map', icon: Search },
      { title: 'Store policies', description: 'Shipping, returns, exchanges, discounts, and warranty rules.', status: 'Review', icon: FileText },
    ],
    actions: [
      { title: 'Recommend products', description: 'Suggests items from needs, budget, browsing activity, and live stock.', status: 'Scope', icon: Sparkles },
      { title: 'Recover cart', description: 'Answers checkout concerns and applies only approved discount guidance.', status: 'Controlled', icon: ShoppingBag },
      { title: 'Start return or exchange', description: 'Checks order status and starts the allowed post-purchase path.', status: 'Scoped', icon: TicketCheck },
    ],
    channels: [
      { title: 'Product pages', description: 'Answers sizing, compatibility, availability, and comparison questions.', status: 'Plan', icon: Globe2 },
      { title: 'Cart and checkout', description: 'Handles shipping, discount, and return concerns before abandonment.', status: 'Plan', icon: ShoppingBag },
      { title: 'Post-purchase chat', description: 'Resolves order status, returns, exchanges, and subscription questions.', status: 'Mapped', icon: MessageSquareText },
    ],
    guardrails: [
      { title: 'Live inventory required', description: 'Checks product data before promising availability or variants.', status: 'Required', icon: Database },
      { title: 'Discount policy', description: 'Can surface active offers but cannot invent or overpromise discounts.', status: 'Required', icon: Settings2 },
      { title: 'Payment fallback', description: 'Routes payment failures and fraud-sensitive cases to a human.', status: 'Required', icon: Split },
    ],
    conversation: {
      customer: 'I need shoes for winter runs and want to compare reliable options.',
      agent: 'I can ask one fit question, check the live catalog, then compare matching options with stock and return terms before checkout.',
      note: 'Combines shopper intent, catalog attributes, inventory, and return policy in one flow.',
      quickReplies: ['Compare options', 'Show in-stock sizes', 'Explain returns'],
    },
  },
}

export const agentBlueprints: AgentBlueprint[] = [
  {
    id: 'service',
    title: 'Service agent',
    shortTitle: 'Service',
    eyebrow: 'Support your customers',
    description: 'Answer questions, resolve issues, create tickets, and hand off sensitive conversations.',
    detailIntro: 'Turn support volume into handled conversations with source-grounded answers and controlled escalation.',
    cta: 'Set up service',
    accentClass: 'bg-[#EA6B22]',
    iconClass: 'text-[#EA6B22]',
    ringClass: 'ring-[#EA6B22]/20',
    Icon: Inbox,
    Visual: ServiceVisual,
    capabilities: ['Instant support', 'Complex query resolution', 'Human handoff'],
    system: roleSystems.service,
    featureWorkspaces: roleFeatureWorkspaces.service,
    operatingModel: roleOperatingModels.service,
  },
  {
    id: 'sales',
    title: 'Sales agent',
    shortTitle: 'Sales',
    eyebrow: 'Acquire new customers',
    description: 'Engage visitors, qualify intent, answer objections, and book meetings for the team.',
    detailIntro: 'Capture demand while buyers are active, then route qualified opportunities into your sales flow.',
    cta: 'Set up sales',
    accentClass: 'bg-[#EE7A50]',
    iconClass: 'text-[#EE7A50]',
    ringClass: 'ring-[#EE7A50]/20',
    Icon: BriefcaseBusiness,
    Visual: SalesVisual,
    capabilities: ['Lead qualification', 'Product discovery', 'Calendar booking'],
    system: roleSystems.sales,
    featureWorkspaces: roleFeatureWorkspaces.sales,
    operatingModel: roleOperatingModels.sales,
  },
  {
    id: 'ecommerce',
    title: 'Ecommerce agent',
    shortTitle: 'Ecommerce',
    eyebrow: 'Engage your shoppers',
    description: 'Guide product discovery, compare items, recover carts, and handle store questions.',
    detailIntro: 'Connect shoppers with the right products and reduce buying friction across the store journey.',
    cta: 'Set up ecommerce',
    accentClass: 'bg-[#53B75A]',
    iconClass: 'text-[#53B75A]',
    ringClass: 'ring-[#53B75A]/20',
    Icon: ShoppingBag,
    Visual: EcommerceVisual,
    capabilities: ['Catalog guidance', 'Cart recovery', 'Shopify-ready setup'],
    system: roleSystems.ecommerce,
    featureWorkspaces: roleFeatureWorkspaces.ecommerce,
    operatingModel: roleOperatingModels.ecommerce,
  },
  {
    id: 'chatbot',
    title: 'Build your own chatbot',
    shortTitle: 'Chatbot',
    eyebrow: 'Custom assistant',
    description: 'Design a branded AI chat agent with training sources, tone, actions, and deploy settings.',
    detailIntro: 'Build a Chatbase-inspired playground for a custom Verevon agent, from prompt to deployable widget.',
    cta: 'Build chatbot',
    accentClass: 'bg-[#111111]',
    iconClass: 'text-[#111111] dark:text-white',
    ringClass: 'ring-[#111111]/15 dark:ring-white/20',
    Icon: Bot,
    Visual: ChatbotVisual,
    capabilities: ['Custom prompt', 'Data sources', 'Web chat preview'],
    system: roleSystems.chatbot,
  },
  {
    id: 'workflow',
    title: 'Workflow builder',
    shortTitle: 'Workflow builder',
    eyebrow: 'Automate operations',
    description: 'Orchestrate triggers, AI steps, branches, and handoffs on a visual workflow canvas.',
    detailIntro: 'Orchestrate triggers, AI steps, branches, and handoffs without leaving the Verevon workspace.',
    cta: 'Open workflow builder',
    accentClass: 'bg-[#B94F9B]',
    iconClass: 'text-[#B94F9B]',
    ringClass: 'ring-[#B94F9B]/20',
    Icon: Workflow,
    Visual: WorkflowVisual,
    capabilities: ['Visual canvas', 'AI app blocks', 'Branch and merge logic'],
    system: roleSystems.workflow,
  },
]
